#pragma once
#include "..\Common.hpp"
#include "..\Hook\Hook.hpp"
#include "..\Utils\Logger.hpp"

namespace IGI {

// ---------------------------------------------------------------------------
// Retail IGI.EXE runtime-logging hooks.
//
// IGI (2000) has no in-game logging facility of its own: it does not import
// msvcrt.dll (the MSVC CRT is statically linked) and the only debug outlets
// are a handful of Win32 imports plus the static CRT output path. This module
// hooks those outlets so every runtime write, file open and debug-string call
// made by the retail executable is captured to a trace file.
//
// Captured surfaces (all verified in retail IGI.EXE via r2mcp/radare2):
//   0x004ABEC7  static CRT _write()  -> printf/puts Runtime-Error output
//   KERNEL32!OutputDebugStringA      -> per-process debug strings
//   KERNEL32!CreateFileA             -> every file the game opens/creates
//   KERNEL32!WriteFile               -> every byte stream the game writes
//   (GameOpenFile 0x004A5350 and GameOpenQFile 0x004B1510 are registered
//    from Hook.cpp next to the existing retail-hook table.)
// ---------------------------------------------------------------------------

// Re-entrancy guard (thread-local): raised around our own logging/file work so
// the API + native I/O hooks never capture traffic generated by the logger.
class RuntimeLogGuard {
public:
  RuntimeLogGuard() { prev_ = s_active; s_active = true; }
  ~RuntimeLogGuard() { s_active = prev_; }

  static bool Active() { return s_active; }

private:
  bool prev_{false};
  inline static thread_local bool s_active{false};
};

// Set to false at any time to stop capturing (hooks stay installed, detours
// become cheap pass-throughs). Defaults: enabled.
inline std::atomic<bool> g_RuntimeLogEnabled{true};
// When true, CRT-write and WriteFile captures also print a hex/text preview of
// the first bytes instead of only the byte count.
inline std::atomic<bool> g_RuntimeLogVerbose{false};

// Retail native + Win32 API signatures.
using CrtWrite_t = int(__cdecl*)(int fd, const void* buffer, unsigned int count);
using OutputDebugStringA_t = void(WINAPI*)(LPCSTR lpOutputString);
using CreateFileA_t = HANDLE(WINAPI*)(LPCSTR lpFileName, DWORD dwDesiredAccess,
                                      DWORD dwShareMode,
                                      LPSECURITY_ATTRIBUTES lpSecurityAttributes,
                                      DWORD dwCreationDisposition,
                                      DWORD dwFlagsAndAttributes,
                                      HANDLE hTemplateFile);
using WriteFile_t = BOOL(WINAPI*)(HANDLE hFile, LPCVOID lpBuffer,
                                  DWORD nNumberOfBytesToWrite,
                                  LPDWORD lpNumberOfBytesWritten,
                                  LPOVERLAPPED lpOverlapped);

// Original trampolines (filled in by MinHook when the hooks are installed).
extern CrtWrite_t CrtWriteOut;
extern OutputDebugStringA_t OutputDebugStringAOut;
extern CreateFileA_t CreateFileAOut;
extern WriteFile_t WriteFileOut;

// Detour entry points (installed by InstallRuntimeLogHooks).
int __cdecl CrtWriteDetour(int fd, const void* buffer, unsigned int count);
void WINAPI OutputDebugStringADetour(LPCSTR lpOutputString);
HANDLE WINAPI CreateFileADetour(LPCSTR lpFileName, DWORD dwDesiredAccess,
                                DWORD dwShareMode,
                                LPSECURITY_ATTRIBUTES lpSecurityAttributes,
                                DWORD dwCreationDisposition,
                                DWORD dwFlagsAndAttributes, HANDLE hTemplateFile);
BOOL WINAPI WriteFileDetour(HANDLE hFile, LPCVOID lpBuffer,
                            DWORD nNumberOfBytesToWrite,
                            LPDWORD lpNumberOfBytesWritten,
                            LPOVERLAPPED lpOverlapped);

// Read the IGI_RUNTIME_LOG / IGI_RUNTIME_LOG_VERBOSE environment overrides.
void RuntimeLogReadConfig();
// Flush + close the trace stream (safe to call repeatedly).
void RuntimeLogShutdown();
// Full path of the trace file (<game folder>\igi.log).
const string RuntimeLogFilePath();
// Record a verified game-level event in the runtime trace.
void RuntimeLogRecord(const string& line);
// Enable/disable capture at runtime (hotkey-friendly). Records the transition
// into the trace file itself and returns the new state.
bool RuntimeLogSetEnabled(bool enable);
// Select concise normal capture (false) or high-frequency verbose capture (true).
// The selected mode is recorded in igi.log.
bool RuntimeLogSetVerbose(bool enable);
// Install CRT-write + Win32 API hooks. Returns the combined first_error value
// in the repo's hook-registration style; individual failures are LOG_ERROR'd.
MH_STATUS InstallRuntimeLogHooks(Hook* hook);

} // namespace IGI