# Ghidra script (Python): apply verified IGI1 native names + comments.
# Run in Script Manager with igi.exe open.
from ghidra.program.model.symbol import SourceType
fm = currentProgram.getFunctionManager()
af = currentProgram.getAddressFactory().getDefaultAddressSpace()
st = currentProgram.getSymbolTable()
NATIVES = {
    "00401B20": ("QtaskUpdateList", "Update all QTask list, Params: p1 ??"),
    "00402780": ("Flow_RequestEvent", "Requests a flow-task event by id (drives the level's flow state machine). Param: eventId = flow event number used in the level flow script. Use from mission flo"),
    "00402820": ("FramesSet", "Set game frames, Params: 30,60 max 240FPS."),
    "004036B0": ("GOPlayer", "Adds a player profile named 'name' to the config while a .cfg/GO script block is being read; subsequent GO_* settings apply to this profile. Param: name = profi"),
    "00403750": ("GOActiveMission", "Sets the active (last-played) mission number for the current player profile. Param: mission = mission index 1..14. Use in profile/config scripts after GO_Player"),
    "004037C0": ("GOInRemap", "Adds one input binding (key remap) to the current profile. Params: key1 = primary key code, key2 = secondary key code, action = in-game action id being bound. U"),
    "00403870": ("GOInMouInv", "Toggles inverted mouse-look for the current profile. Param: invert = 1 invert Y axis, 0 normal. Use in config scripts. Returns 1."),
    "004038E0": ("GOInMouSens", "Sets mouse sensitivity for the current profile. Param: sensitivity = float multiplier as saved by the options screen. Use in config scripts. Returns 1."),
    "00403950": ("GOGfxDisp", "Sets display-mode selection for the current profile. Param: displayMode = mode index from the retail display list (see Display_GetActiveMode/display table). Use"),
    "00403A00": ("GOGameLang", "Sets game language for the current profile. Param: language = language index (retail ships English=0 and German builds use their own index). Use in config scrip"),
    "00403AC0": ("GOGameDiff", "Sets game difficulty for the current profile. Param: difficulty = 0 easy, 1 medium, 2 hard (retail order). Use in config scripts. Returns 1."),
    "00403B30": ("Config_IsGermany", "RETURNS 1 when running the GERMAN retail build (censored variant), 0 otherwise. Takes no args. German builds gate blood/gore - check before forcing such effects"),
    "00403B70": ("Config_ResetGraphicOptions", "Resets the ACTIVE PROFILE's graphic options to defaults (display mode, gamma, transparency, performance flags). Takes no script args (registrar argc=0 at site 0"),
    "00403C10": ("GO_ContentControlPW", "Config-writer form (argc=1): sets the content-control password while a config file is parsed. Param: password = string. Returns 1."),
    "00403C70": ("Config_GetContentControlPassword", "RETURNS the stored content-control (parental lock) password string. Takes no args. Compare against user input or pass to Config_VerifyContentControlPassword."),
    "00403CC0": ("Config_VerifyContentControlPassword", "Checks a password attempt against the stored content-control password. Param: password = string to test. RETURNS non-zero when correct, 0 when wrong. Use before"),
    "00403D90": ("Config_IsContentControlPasswordEnabled", "RETURNS 1 if a content-control password is SET (parental lock active), else 0. Takes no args. Use to decide whether to ask for the password."),
    "00403DF0": ("GOIsBlood", "Toggles blood effects for the current profile. Param: blood = 1 on, 0 off. Use in config scripts. Returns 1."),
    "00403E60": ("GOSoundSpeech", "Sets speech volume for the current profile. Param: volume = float 0.0-1.0. Use in config scripts. Returns 1."),
    "00403EF0": ("GOSoundMusic", "Sets music volume for the current profile. Param: volume = float 0.0-1.0. Use in config scripts. Returns 1."),
    "00403F80": ("GOSoundFX", "Sets sound-effects volume for the current profile. Param: volume = float 0.0-1.0. Use in config scripts. Returns 1."),
    "00404010": ("GOGfxDevice", "Sets render-device (D3D device/GUID) selection for the current profile. Param: deviceIndex = index into the render-device list filled by Config_FillRenderDevice"),
    "00404080": ("GOGfxGamma", "Sets gamma for the current profile. Param: gamma = float, retail default 1.0 (range ~0.5-3.0 clamped elsewhere). Use in config scripts. Returns 1."),
    "004040F0": ("GOGfxPerformance", "Sets graphics performance/detail flags for the current profile. Param: flags = bitmask from the detail-level mapping (see Config_GraphicOptionsGetPerfFlagsFromL"),
    "00404160": ("Config_GameOptionsInputSetInvertMouse", "Sets invert-mouse in the GAME-OPTIONS block while a config file is parsed (the GO_* writer side; runtime getter/setter pair lives on the profile). Param: invert"),
    "004041D0": ("Config_GameOptionsInputGetInvertMouse", "RETURNS the invert-mouse setting when the engine writes/reads a config game-options block (1 = inverted, 0 = normal). Takes no args. Pairs with Config_GameOptio"),
    "00404230": ("Config_GameOptionsInputSetMouseSensitivity", "Sets mouse-sensitivity in the config game-options write-out context. Param: value = sensitivity as stored by the options screen (integer scale)."),
    "00404290": ("Config_GameOptionsInputGetMouseSensitivity", "RETURNS the stored mouse-sensitivity integer from the game-options config context. Takes no args."),
    "004042E0": ("Config_GameOptionsInputSetBloodEnabled", "Sets blood-enabled in the config game-options write-out context. Param: blood = 1 on, 0 off."),
    "00404340": ("Config_GameOptionsInputGetBloodEnabled", "RETURNS the blood-enabled flag from the game-options config context (1/0). Takes no args."),
    "00404450": ("Config_FillScreenResolutionListBox", "Fills the currently-active menu list box with the screen resolutions available for a device. Param: deviceIndex = render-device index. Use only inside a menu li"),
    "00404510": ("Config_GraphicOptionsSetResolution", "Applies a screen resolution to the active profile and re-initialises the display. Param: modeIndex = index from Config_FillScreenResolutionListBox entries. Use "),
    "00404590": ("ConfigGetActiveGraphicOptions", "Returns a pointer to the ACTIVE PROFILE's graphic-options record inside the global config array. The record base is 0xBC2394 + 0xD14 * activeProfileIndex (verif"),
    "004045B0": ("Config_GraphicOptionsGetResolution", "Returns the active profile's display-mode/resolution index (same index space as Config_GraphicOptionsSetResolution). Use in video-options UI scripts to preselec"),
    "004046A0": ("Config_FillRenderDeviceListBox", "Fills the currently-active menu list box with installed render devices (Direct3D device GUIDs/names). Use inside a list box collect-items script on the video-op"),
    "00404710": ("Config_GraphicOptionsGetDevice", "Returns the active profile's render-device index (index into the device list). Use in video-options UI scripts."),
    "004047F0": ("Config_GraphicOptionsSetDevice", "Applies a render device to the active profile. Param: deviceIndex = index from Config_FillRenderDeviceListBox. Use in video-options screen script."),
    "004048B0": ("Config_GraphicOptionsSetGamma", "Sets and immediately applies gamma to the active profile (also feeds the live lighting math through the profile record +0x220). Param: gamma = float (retail def"),
    "00404910": ("Config_GraphicOptionsGetGamma", "Returns the active profile's gamma as a float. Use to initialise your own gamma slider/UI."),
    "00404960": ("Config_GraphicOptionsSetTransparency", "Toggles transparency for the active profile. Param: onOff = 1 enable, 0 disable. Video-options screen."),
    "004049C0": ("Config_GraphicOptionsGetTransparency", "Returns 1 if transparency is enabled for the active profile, else 0."),
    "00404A10": ("Config_SoundOptionsSetSoundsEffects", "Enables/disables sound effects for the active profile. Param: onOff = 1 on, 0 off."),
    "00404A90": ("Config_SoundOptionsGetSoundsEffects", "Returns 1 if sound effects are enabled for the active profile, else 0."),
    "00404AE0": ("Config_SoundOptionsSetSoundsEffectsVolume", "Sets SFX volume for the active profile. Param: volume = float 0.0-1.0."),
    "00404B40": ("Config_SoundOptionsGetSoundsEffectsVolume", "Returns the active profile's SFX volume (0.0-1.0)."),
    "00404B90": ("Config_SoundOptionsSetMusic", "Enables/disables music for the active profile. Param: onOff = 1 on, 0 off."),
    "00404BF0": ("Config_SoundOptionsGetMusic", "Returns 1 if music is enabled for the active profile, else 0."),
    "00404C40": ("Config_SoundOptionsSetMusicVolume", "Sets music volume for the active profile. Param: volume = float 0.0-1.0 (pops a float arg - pass a float!)."),
    "00404CA0": ("Config_SoundOptionsGetMusicVolume", "Returns the active profile's music volume (0.0-1.0)."),
    "00404CF0": ("Config_SoundOptionsSetSpeech", "Enables/disables radio speech for the active profile. Param: onOff = 1 on, 0 off."),
    "00404D50": ("Config_SoundOptionsGetSpeech", "Returns 1 if speech is enabled for the active profile, else 0."),
    "00404DA0": ("Config_SoundOptionsSetSpeechVolume", "Sets speech volume for the active profile. Param: volume = float 0.0-1.0."),
    "00404E00": ("Config_SoundOptionsGetSpeechVolume", "Returns the active profile's speech volume (0.0-1.0)."),
    "00404E50": ("Config_SoundOptionsSetReverseStereo", "Toggles reversed stereo channels for the active profile. Param: onOff = 1 reverse, 0 normal."),
    "00404EB0": ("Config_SoundOptionsGetReverseStereo", "Returns 1 if stereo is reversed for the active profile, else 0."),
    "00404F00": ("Config_GraphicOptionsSetPerformanceFlags", "Sets the raw graphics performance/detail flag bits on the active profile. Param: flags = bitmask (get a valid one from Config_GraphicOptionsGetPerfFlagsFromLeve"),
    "00404F60": ("Config_GraphicOptionsGetPerformanceFlags", "Returns the active profile's graphics performance flag bitmask."),
    "00404FA0": ("Config_FillPlayerProfileListBox", "Fills the current menu list box with all player profiles (name per row, row index = profile index). Use inside the profile-selection list box collect-items scri"),
    "00405010": ("Config_GetActivePlayerProfileIndex", "RETURNS the index of the currently-active player profile (0-based). Takes no arguments. Use whenever you need which profile is selected, e.g. before Config_Dele"),
    "00405050": ("Config_SetActivePlayerProfileIndex", "Makes 'index' the active player profile. Param: index = 0-based profile index (must exist; see Config_GetNumberOfPlayerProfiles)."),
    "004050A0": ("Config_CreateNewPlayerProfile", "Creates a new player profile. Params: name = new profile name (string), sourceIndex = existing profile index to copy initial settings from. RETURNS 1 on success"),
    "00405400": ("Config_DeletePlayerProfile", "Deletes a player profile. Param: index = 0-based profile index to delete. RETURNS 1 on success, 0 on failure. Do not delete the last remaining profile; refresh "),
    "004054F0": ("Config_GetNumberOfPlayerProfiles", "RETURNS how many player profiles exist. Use to bounds-check indexes and to size profile lists."),
    "00405530": ("Config_GraphicOptionsGetPerfLevelFromFlags", "Converts a performance-flag bitmask back into its detail LEVEL number. Param: flags = bitmask from the profile/performance setting. Use to show the current deta"),
    "004055C0": ("Config_GraphicOptionsGetPerfFlagsFromLevel", "Converts a detail LEVEL number into its performance-flag bitmask. Param: level = 0..Config_GraphicOptionsNumPerfLevels()-1. Use when the user picks a named deta"),
    "00405620": ("Config_GraphicOptionsNumPerfLevels", "RETURNS the number of graphics detail levels the engine supports (constant). Use to build the detail-level slider/list."),
    "00405660": ("Config_FillMissionSelectionBox", "Fills the current menu list box with missions selectable for the active profile (respects unlocked progress). Use inside the mission-selection list box collect-"),
    "004056F0": ("Config_FillMissionPictureBox", "Fills the current picture box with the selected mission's briefing image. Use inside the mission-picture control's script right after a mission row is chosen."),
    "00405760": ("Config_FillMissionTextBox", "Fills the current text box with the selected mission's briefing text. Use inside the mission-briefing text control's script."),
    "004057D0": ("Config_PlayerGetActiveMission", "Returns the active (reached) mission number of ANY profile. Param: profileIndex = 0-based profile index. Use on the profile/mission screens to show progress wit"),
    "00405850": ("ConfigRead", "Read game config file, Params:  File: 'LOCAL:config.qsc'"),
    "00405BD0": ("ConfigWrite", "Write game config file, Params: File: 'LOCAL:config.qsc'"),
    "00406220": ("Config_GetActivePlayerProfileRecord", "RETURNS pointer to the ACTIVE PROFILE's graphic-options/config record: computed as 0xBC2388 + 0xD14*[0xBC2384] (verified against retail defaults-reset fcn.00403"),
    "004071E0": ("WeaponConfigRead", "Reads/compiles a WEAPON CONFIG text: strlen-copies cfgText into the engine's static config buffer (0x5690F0) then hands it to ConfigCompile (0x4F0CF0) - the com"),
    "00407E30": ("DefineQMaterial", "Defines a Q-material (surface material) entry while a material definition block is parsed. Called BY the engine's own define-block parser - call only from mater"),
    "00407F50": ("DefineGameMaterial", "Defines a GameMaterial entry during a game-material definition block (855-byte parser function). Call only from gamematerial .qsc definition contexts; arg layou"),
    "00408350": ("GameMaterial_LoadParameters", "Name from igi.exe error string inside function: \"GameMaterial_LoadParameters: Couldn't load script \\\"%s\\\"\". Loads game-material parameters from its script."),
    "004101C0": ("DefineHumanPlayerWeaponCycle", "Collects the weapon-cycle list for the human player: loops the parsed entries and stores them into the cycle table at 0x56DF1C with count at 0x56DF18 (verified "),
    "00410240": ("DefineHumanPlayerWeaponCategory", "Registers one weapon-category entry for the human player during a humanplayer definition block (argc unknown - parser context). Pairs with DefineHumanPlayerWeap"),
    "004102D0": ("DefineHumanPlayerAmmoLimit", "Registers an ammo-limit entry (max carried ammo class) for the human player during a humanplayer definition block (argc unknown - parser context)."),
    "004137A0": ("HumanPlayer_LoadParameters", "Name from igi.exe error string inside function: \"HumanPlayer_LoadParameters: Couldn't load script \\\"%s\\\"\". Loads humanplayer parameters (weapons/ammo/cycle defi"),
    "00413B70": ("WeaponTypeOpen", "Open all weapons defined in .qsc file for Humanplayer."),
    "00413BB0": ("WeaponsCountGet", "RETURNS the number of weapons defined for the human player: reads global counter 0x57B18C (exactly `mov eax,[0x57B18C]; ret`). That counter is written by the De"),
    "00415020": ("DEBUG_KEYS_ENABLE_INVALID", "TOMBSTONE - DO NOT INVOKE. The retail debug-keys native address is UNKNOWN. The old value 0x0041502 lies outside .text (0x401000-0x532510) and would crash on in"),
    "004151E0": ("MovieSubtitle_RegisterFont", "Registers a font used by in-game movie subtitles (16 callsites in body; argc unknown - parser context). Call from subtitle/font definition blocks before any Mov"),
    "00415260": ("MovieSubtitle_RegisterText", "Registers one subtitle text entry (string + timing) shown over movies/briefings (argc unknown - parser context). Call after the font registration it should use."),
    "004157D0": ("Game_DisablePlayerInput", "Disables ALL player input (keyboard+mouse) - used by cutscenes/menus. Re-enable with Game_EnablePlayerInput."),
    "00415830": ("Game_EnablePlayerInput", "Re-enables player input after Game_DisablePlayerInput. Takes no args."),
    "00415890": ("Game_SetMission", "Selects the mission the game will run/load next. Param: mission = mission index 1..14. Use before Level_Start/level load flow when jumping straight into a missi"),
    "004158E0": ("Game_UpdateVolume", "Applies current profile music/sfx volumes to the live audio engines. Takes no args."),
    "00415950": ("Game_SetMusicVolume", "Live-sets music volume through the profile real-value setter (fcn.004B8A50): retail body constructs 1.0f (0x3FF00000) and stores via fstp. Param: volume = float"),
    "004159B0": ("Game_SetSFXVolume", "Live-sets sound-effects volume through the profile real-value setter (fcn.004B8A50), same 1.0f construction pattern. Param: volume = float 0.0-1.0. Called by in"),
    "00415A10": ("Game_EnableMusic", "Starts/resumes the music engine. Takes no args."),
    "00415A60": ("Game_DisableMusic", "Stops the music engine. Takes no args."),
    "00415AB0": ("Game_CutsceneDelete", "Deletes/ends the running cutscene and frees its resources. Takes no args."),
    "00415B30": ("LevelStart", "Start new level, Params:  p1: 0057BABC"),
    "00416550": ("Game_DeleteHandler", "The game's DELETE handler - runs when a level/game session is torn down (quit path), releasing entities and session state. Takes no args. Engine-internal teardo"),
    "00416D80": ("Human_HitDamage", "Reads the player XP/hit byte: returns byte [PlayerPtr+0xE1]. Takes no args. Documented alias of HUMAN_HIT_DAMAGE - same address."),
    "00416FE0": ("Game_Restart", "Restarts the CURRENT LEVEL/session: tears down and reloads the running game state (the Ctrl+F4-style restart path). Takes no args. Use to reset the mission with"),
    "004174A0": ("MenuManager_RequestScreen", "Requests a menu screen by id through the menu manager (queued request). Params: screenId = retail screen resource id, flags = request modifier (0 = normal). Use"),
    "00417690": ("MenuManager_PushScreen", "Pushes a screen onto the menu stack: allocates the screen object (objsize 0x2898) and stores it in the manager's screen stack at mgr+0x27EC (verified in igi.exe"),
    "00417710": ("MenuManager_PopScreen", "Pops the top screen off the menu stack (destroys it) revealing the one beneath. Param: param = pass-through argument observed in retail calls (pass 0). Pair wit"),
    "00417790": ("MenuManager_LeaveMenus", "Leaves/closes the whole menu system returning to gameplay. Params: two ints observed in retail calls (pass 0,0). Use to exit from custom menus."),
    "00417810": ("MenuManager_SetLanguage", "Switches menu/UI language at runtime. Param: langIndex = language index matching the LANGUAGE\\ folder tables. Call before pushing screens so texts load in the r"),
    "00417880": ("MenuManager_ForceUpdateWindow", "Forces the menu manager to redraw/update its windows this frame. Param: observed retail value 0. Use after changing control contents from script."),
    "00417900": ("MenuManager_ActivatePopupScreen", "Activates a popup screen on top of the current menus (e.g. confirmation dialogs; retail scripts call MenuManager_ActivatePopupScreen(930)). Param: popupId = ret"),
    "00417960": ("MenuManager_DeactivatePopuScreen", "Deactivates the currently-active popup screen and returns to the screen beneath. Takes no args. Pair with MenuManager_ActivatePopupScreen. NOTE: name mirrors th"),
    "004179B0": ("MenuManager_SetEnabled", "Enables/disables menu-manager input processing. Param: enabled = 1 menus react to input, 0 frozen. Use to freeze menus during scripted sequences."),
    "00418B00": ("MenuManager", "MenuManager load for inagame or Mainmenu,Params:  p1: 0057BABC ,p3,p4,p5: 0."),
    "004231E0": ("ControlsMenu_ConvertFloatFromOffset", "Converts a controls-menu slider/storage OFFSET into its float value (0.0-1.0 range used by the control configuration bars). Param: offset = raw integer offset s"),
    "00423240": ("ControlsMenu_ConvertOffsetFromFloat", "Inverse of ControlsMenu_ConvertFloatFromOffset: converts a float control value into the raw storage offset. Param: value = float 0.0-1.0. Use when saving a modi"),
    "0044D0E0": ("AIAction_Patrol", "Orders the AI into PATROL behaviour. Params: target = patrol goal/node reference from your script, mustBeZero = retail template always passes 0, flags = AIACTIO"),
    "0044D160": ("AIAction_Combat", "Orders the AI into COMBAT behaviour vs its current enemy. Param: param = combat argument from the calling script (retail guard scripts pass their combat target/"),
    "0044D260": ("AIAction_Dead", "Runs the DEATH handling action for the AI (plays death, releases tasks). Param: param = death context value passed by retail scripts. Use in AIEVENT_DEAD handle"),
    "0044D2C0": ("AIAction_FallFlat", "Knocks the AI flat on the ground (ragdoll-ish fall, e.g. after explosion/surrender). Params: two ints observed in retail calls (pass 0,0 unless mapping specific"),
    "0044D420": ("AIAction_Activate", "Generic ACTIVATE action: sends the AI to activate/use an object (switch, door, alarm...). Params: target = object/task reference, param2 = secondary value (reta"),
    "0044D4A0": ("AIAction_WalkToNode", "Walks the AI to a nav node. Params: nodeId = graph/node id from the level nav data, flags = AIACTIONFLAG (NONE=0/PUSHABLE=1). Use for calm movement in AI script"),
    "0044D510": ("AIAction_RunToNode", "Runs the AI to a nav node (fast). Same params as AIAction_WalkToNode: nodeId = node id, flags = AIACTIONFLAG (NONE=0/PUSHABLE=1)."),
    "0044D580": ("AIAction_FireAtNode", "Makes the AI fire AT a nav-node position. Params: nodeId = target node id, remaining 4 args = firing stance/behaviour values observed in retail AI scripts (map "),
    "0044D630": ("AIAction_FireAtTask", "Makes the AI fire AT a task/object entity. Params: taskId = target task/entity id, remaining 4 args = firing behaviour values (same layout family as FireAtNode)"),
    "0044D6E0": ("AIAction_PlayAnimation", "Plays an animation on the AI. Params: animationId = animation entry id (see AIFunction_AddAnimationEntry), flags = AIACTIONFLAG (NONE=0/PUSHABLE=1)."),
    "0044D750": ("AIAction_PlaySound", "Plays a sound from the AI (voice barks etc.). Params: soundId = sound/event id, param2 = observed 0 in retail, flags = AIACTIONFLAG (NONE=0/PUSHABLE=1)."),
    "0044D7D0": ("AIAction_MoveToEvent", "Moves the AI toward the source position of an EVENT it received. Params: eventId = AIEVENT_* whose position to move to, flags = AIACTIONFLAG (NONE=0/PUSHABLE=1)"),
    "0044D870": ("AIAction_LookAtEvent", "Turns the AI to LOOK toward an event's source without moving. Params: eventId = AIEVENT_* value, flags = AIACTIONFLAG (NONE=0/PUSHABLE=1)."),
    "0044D8F0": ("AIAction_Stunned", "Stuns the AI (flashbang/knockout reaction). Params: param1 = stun duration/context value, flags = AIACTIONFLAG (NONE=0/PUSHABLE=1)."),
    "0044D960": ("AIAction_KickGrenade", "Kicks a nearby live grenade away (retail soldier behaviour). Param: param = grenade/context reference from the event. Use in grenade-event handlers."),
    "0044DA00": ("AIAction_RunPanicking", "Sends the AI into PANIC running (civilians under fire). Params: param1 = panic target/context, flags = AIACTIONFLAG (NONE=0/PUSHABLE=1)."),
    "0044DA80": ("AIAction_Idle", "Puts the AI into IDLE (stands, resumes idle animation countdown). Param: idle context value (retail scripts pass their idle value). Use in AIEVENT_IDLE handler "),
    "0044DAE0": ("AIAction_SetCombat", "Force-sets the AI's COMBAT ENEMY/target. Param: enemyId = enemy entity/id to engage. Use to make an AI attack a specific target regardless of detection."),
    "0044DBC0": ("AIFunction_RemoveAlarmActions", "Removes all queued ALARM-related actions from this AI (calms it down). Takes no args. Use to de-escalate an NPC you control."),
    "0044DC40": ("AIFunction_SetViewLength", "Sets this AI's VIEW LENGTH - how far it can see. Param: length = view distance in engine units. Use in AI init (AIEVENT_CREATE) to buff/nerf vision."),
    "0044DCD0": ("AIFunction_SetAlarmViewLength", "Sets view length WHILE AN ALARM IS ON (separate stat from normal vision). Param: length = distance in engine units. Use in AI init."),
    "0044DD30": ("AIFunction_SetViewAlpha", "Sets view ALPHA - the detection speed/gain of normal vision. Param: alpha = engine detection factor. Higher = spots player faster. Use in AIEVENT_CREATE."),
    "0044DD90": ("AIFunction_SetViewGamma", "Sets view GAMMA - secondary vision shaping factor for detection. Param: gamma = engine factor. Use in AI init alongside SetViewAlpha."),
    "0044DDF0": ("AIFunction_SetSecondaryViewLength", "Sets SECONDARY view length (peripheral/short-range channel). Param: length = distance in engine units."),
    "0044DE80": ("AIFunction_SetSecondaryAlarmViewLength", "Sets secondary view length during alarms. Param: length = distance in engine units."),
    "0044DEE0": ("AIFunction_SetSecondaryViewAlpha", "Sets secondary-view detection gain. Param: alpha = engine factor."),
    "0044DF40": ("AIFunction_SetSecondaryViewGamma", "Sets secondary-view gamma shaping factor. Param: gamma = engine factor."),
    "0044DFA0": ("AIFunction_GetCurrentEventType", "RETURNS the AIEVENT_* value currently being handled - the backbone of every AI script's if/else chain. Enum: CREATE=0, DELETE=1, DEAD=2, ANIMATION=3, IDLE=4, AL"),
    "0044E000": ("AIFunction_GetRandomValue", "RETURNS a random value below 'max' (returns Real per retail table). Param: max = upper bound. Use for randomized behaviour delays/targets in AI scripts."),
    "0044E060": ("AIFunction_DefaultHandler", "The default AI event handler: call this for any AIEVENT_* your script does not handle explicitly (retail template shows it as the else-branch body). Takes no ar"),
    "0044E0C0": ("AIFunction_SetEventPriority", "Sets the priority of the CURRENT event being handled (decides which queued event wins). Param: priority = engine priority number. Use inside an event handler."),
    "0044E150": ("AIFunction_SetInvulnerability", "Makes this AI invulnerable. Param: onOff = 1 immune to damage, 0 normal. Great for boss/scripted NPCs. Use in AIEVENT_CREATE or anytime."),
    "0044E1B0": ("AIFunction_SetInstantDeath", "When on, any hit instantly kills this AI (no damage pooling). Param: onOff = 1 one-shot kills, 0 normal health. Use for scripted one-shot enemies."),
    "0044E210": ("AIFunction_SetDeathAnimation", "Overrides the death animation played when this AI dies. Param: animId = animation entry id. Use in AI init for custom deaths."),
    "0044E270": ("AIFunction_SetAlarmTriggerID", "Binds an ALARM trigger object to this AI (which alarm switch it responds to/runs to). Param: id = alarm trigger id from the level. Retail template: AIFunction_S"),
    "0044E2D0": ("AIFunction_SetAlarmControlID", "Binds the ALARM CONTROL (the raised-alarm device) this AI uses. Param: id = alarm control id from the level. Retail template: AIFunction_SetAlarmControlID(xx)."),
    "0044E330": ("AIFunction_SetAlarmAccess", "Sets HOW the AI treats the alarm route. Param: access = AIALARMACCESS enum: BEFORECOMBAT=0 (run for the alarm first), AFTERCOMBAT=1 (fight first, raise alarm af"),
    "0044E390": ("AIFunction_SetGunnerID", "Assigns which mounted-gunner slot this AI mans. Param: gunnerId = gunner position id. Use in AI init for turret/mounted-gun NPCs."),
    "0044E3F0": ("AIFunction_GetAlarmTriggerID", "RETURNS the id of the alarm trigger bound to this AI (see AIFunction_SetAlarmTriggerID). Takes no args. Use in handlers to check which alarm applies."),
    "0044E430": ("AIFunction_GetAlarmControlID", "RETURNS the bound alarm-control id. Takes no args."),
    "0044E470": ("AIFunction_GetAlarmAccess", "RETURNS the current AIALARMACCESS mode: BEFORECOMBAT=0, AFTERCOMBAT=1. Takes no args."),
    "0044E4B0": ("AIFunction_GetGunnerID", "RETURNS this AI's assigned gunner slot id. Takes no args."),
    "0044E4F0": ("AIFunction_GetAlarmControlStatus", "RETURNS the status/state of the bound alarm control (raised/used state as tracked by the engine). Takes no args."),
    "0044E5E0": ("AIFunction_GetGunnerStatus", "RETURNS the status of this AI's gunner post (manned/state value). Takes no args."),
    "0044E6D0": ("AIFunction_SetScriptIntegerValue", "Writes an AI-script integer variable. Params: varId = script variable index, value = new integer. Use for custom AI state communication between scripts."),
    "0044E740": ("AIFunction_GetScriptIntegerValue", "READS an AI-script integer variable written by AIFunction_SetScriptIntegerValue. Param: varId = variable index. RETURNS the integer."),
    "0044E790": ("AIFunction_SetScriptRealValue", "Writes an AI-script real (float) variable. Params: varId = script variable index, value = float. Pairs with AIFunction_GetScriptRealValue."),
    "0044E800": ("AIFunction_GetScriptRealValue", "READS an AI-script real (float) variable. Param: varId = variable index. RETURNS the float."),
    "0044E860": ("AIFunction_IsEventBehind", "RETURNS non-zero if the current event came from BEHIND the AI (direction test used for reaction animations). Takes no script args per retail table (engine reads"),
    "0044E930": ("AIFunction_GetEventDistance", "RETURNS the DISTANCE to the source of the current event (Real). Takes no args. Use inside event handlers e.g. 'if gunshot closer than X then investigate'."),
    "0044E9B0": ("AIFunction_GetAlarmTriggerDistance", "RETURNS the distance between this AI and its bound ALARM TRIGGER (Real). Takes no args. Use to decide running vs fighting for the alarm."),
    "0044EAF0": ("AIFunction_SetAnimationInterval", "Sets playback INTERVAL for an animation entry. Params: entryIndex = animation entry added via AddAnimationEntry, interval = frame/tick interval. Use when tuning"),
    "0044EBB0": ("AIFunction_AddAnimationEntry", "Adds an animation ENTRY to this AI's available set (builds the pick-list GetAnimationToPlay draws from). Params: animationId = animation resource id, data = ent"),
    "0044ECB0": ("AIFunction_GetAnimationToPlay", "RETURNS which animation entry the engine decided to play for the current event/action (useful to log or override reactions). Per retail table takes no script ar"),
    "0044EE40": ("AIFunction_SendResponse", "Sends the AI's RESPONSE to the current event (used for ALERT_RESPONSE chains so buddy AIs react too). Takes no args. Call inside alert handlers."),
    "0045C440": ("SoldierExecute", "Executes/initializes a SOLDIER AI entity in the level. Params: context = task/context object (2nd arg is the soldier ptr - verified: esi=[esp+0x1C] after prolog"),
    "0045FF80": ("WeaponAmmoPickup", "Gives an AMMO pickup to the player (same struct conventions as Weapon_GunPickup: player carry-flags and pickup-entity fields drive the grant; plays the pickup s"),
    "0045FFC0": ("WeaponGunPickup", "Gives a GUN pickup to the player: checks the player's already-carried flag (player+0xCF5), reads the weapon id from pickupEntity+8 -> word +0x1C, validates the "),
    "00463760": ("HumanViewCam", "Sets the human's VIEW-CAMERA selector: stores camValue into human struct offset +0x4F0 (verified: mov [ecx+0x4F0],eax; ret - 5-byte setter). Params: human = Hum"),
    "004659E0": ("HumanTaskViewReset", "Resets the human's VIEW TANGENT fields to retail defaults: computes tan() of the half-FOV globals 0x5335E8/0x5339C0 (the same globals ENHANCER::FOV_SET writes) "),
    "0047CAB0": ("AmmoTypeOpen", "Open ammo qvm file to memory for all weapons loaded."),
    "0047CAD0": ("DefineAmmoType", "Defines an AMMO TYPE inside an ammo definition block of a .qsc/.cfg script (515-byte parser body; igi.exe embeds str 'DefineAmmoType'). Args follow the Define-a"),
    "004828D0": ("Human_FindNextCamera", "Debug camera cycler: advances to the next camera/view target attached to the human player (decompiled body polls input keys). Param: human = human-player pointe"),
    "00484E60": ("Mission_Open", "Name from igi.exe error string inside function: \"Mission_Open(): Couldn't load script: %s\". Opens a mission definition script and builds its task tree."),
    "00484F60": ("DefineMission", "Defines a MISSION entry during mission-list parsing (480-byte parser). Called by the engine's mission definition grammar; do NOT call from gameplay scripts."),
    "00485970": ("StatusMessageShow", "Displays an on-screen STATUS MESSAGE (the HUD text that also drives FiberPool pumping!). Params: status_timer = display duration ticks, msg = text, sprite = opt"),
    "00485AD0": ("StatusMessageScreen_ClearMessages", "Clears all on-screen status messages. Takes no args."),
    "00488E00": ("LevelFlow_GetBreakCutSceneKey", "RETURNS the key code currently bound to 'skip/break cutscene'. Takes no args. Use in cutscene player loops to detect the skip key press."),
    "00488E50": ("LevelFlow_LevelFailed", "Signals that the level FAILED - triggers the retail failure flow (fail sound, restart/quit menu). Takes no args. Call when your scripted objective fails."),
    "00488E90": ("LevelFlow_IsCountryUSA", "RETURNS 1 if the running build is a USA country build, 0 otherwise (affects censorship/content paths like blood). Takes no args. Check before enabling content t"),
    "0048A440": ("LoadingScreenShow", "Shows the LOADING SCREEN: loads LOCAL:menusystem/loadingscreen.res then displays loading.pic - or loading_us.pic on USA country builds (pairs with LevelFlow_IsC"),
    "0048F1A0": ("AppContextSetDebugged", "Sets the app-level DEBUGGED flag (global 0x5C8BF8). Param: state = 1 mark debugger attached/debug mode, 0 clear. BlankName's IGIPatch calls this by name. Use to"),
    "0048F1E0": ("AppContextSetDebugtextState", "Toggles on-screen DEBUG TEXT output (global 0x5C8BF4). Param: state = 1 show engine debug text, 0 hide. Handy while reverse-engineering other systems."),
    "0048F240": ("AppContextSetLightmapsUsed", "Enables/disables OBJECT lightmaps globally (global 0x5C8BE4) - the verified retail lightmap setter. Param: used = 1 use object lightmaps, 0 flat-lit. Use for gr"),
    "0048F260": ("AppContextSetTerrainLightmapsUsed", "Enables/disables TERRAIN lightmaps globally (global 0x5C8BE8). Param: used = 1 lit terrain, 0 unlit. Pair with AppContext_SetLightmapsUsed for full lighting con"),
    "0048F360": ("AppMainParseCmdLineArgs", "Parses the game COMMAND LINE (window mode, resolution and other launch switches; case-insensitive compare loops verified). IGIPatch hooks this for borderless-wi"),
    "00491A90": ("DisplaySetMode", "Switches the DISPLAY MODE at runtime: validates mode fields vs current (0xC28B44...), repositions/resizes the window (GetSystemMetrics), copies the mode into th"),
    "00491CF0": ("DisplayGetActiveMode", "RETURNS pointer to the ACTIVE display-mode struct (global 0xC28B40): width/height/depth fields live at +0x4/+0x8/+0x10 per Display_SetMode comparisons. Takes no"),
    "00491E70": ("DisplaySetBackgroundColourFn", "Sets the 3D-view BACKGROUND COLOUR (clear colour) - masks each arg to a byte into globals 0xBCADF0/R,G,B. Params: r,g,b = 0-255 colour channels. Use for custom "),
    "00495E70": ("MusicSetVolume", "Sets BOTH music engine volumes (likely front/master pair) after scaling by the global music factor. Params: volume1, volume2 = floats 0.0-1.0 scaled against set"),
    "00495F30": ("MusicSetSfxVolume", "Sets the SFX bus volume feeding the music/sound mix path. Param: volume = float 0.0-1.0 scaled by global factor. Use for live SFX fade."),
    "00497E70": ("TranscontextSetActiveTransContext", "Installs a TRANSFORM CONTEXT as active: copies 0x2A dwords from ctx into global 0xBCAAE0 and bumps state counters at 0x6E5BB0/B4. Param: ctx = transform-context"),
    "004A5350": ("FileOpen", "Open file for reading or writing, Params: Check fopen() in c."),
    "004A53B3": ("GameDataSymbolLoad", "Parses game-data SYMBOL DEFINITIONS from a buffer into the symbol table: tokenizes via 0x4A7720 with per-name limit 0x42 (66 bytes) and count cap 0x7FFFFFFF, nu"),
    "004AF7B0": ("ErrorShow", "Shows a fatal-error dialog: printf-style FORMAT STRING + variadic args (e.g. push \"Level_Load(): Couldn't load script: %s\"; push scriptPath; call). Param: forma"),
    "004AF810": ("WarningShow", "Shows a warning dialog - printf-style variadic like ErrorShow (retail: push str.\"QTasktype \\\"%s\\\"...\"; push eax; call -> add esp,8). Param: format = printf-styl"),
    "004B0BE0": ("MemDeallocAll", "Deallocate allocated memory. Frees EVERY tracked heap block (walks allocation list via 0x4B0D10), then warns \"%d block(s) of memory have not been deallocated.\" "),
    "004B0C60": ("Mem_Alloc", "Engine heap allocator. Params: numBytes = bytes to allocate, tag = allocation bucket shown in the 'Total allocated by user' accounting. RETURNS pointer or 0 on "),
    "004B0D40": ("QHash_ValueSet", "Sets a value in a QHash hash-table (8-byte thunk into the hash engine at 0x4B0D90 family). Pass the table ptr, key string and integer value. Restored after acci"),
    "004B0D60": ("QhashInit", "Init hash table value, Params: hash value 0 or 1."),
    "004B0D90": ("QhashReset", "Reset QTask type hash table."),
    "004B0DB0": ("QHash_ValueGet", "Gets a value from a QHash hash-table (6-byte getter thunk). Pass table ptr + key string, RETURNS the stored integer. Restored after accidental loss - address pa"),
    "004B1510": ("QFileOpen", "Open Qfile (QSC,QVM) for reading or writing, Params: Check fopen() in c."),
    "004B16D0": ("ResourceUnpack", "Unpacks a raw resource ENTRY previously obtained from the resource table into a destination address. Params: resPtr = resource-table entry, destAddr = destinati"),
    "004B18B0": ("ResourcePackUnpack", "Unpacks a PACKED resource file (compressed/packed container format) into memory. Params: resFile = virtual path of the packed resource, outBuffer = receives unp"),
    "004B1AC0": ("QScript_Cleanup", "Cleans up/frees a parsed .qsc script structure (pass1: 5 calls, valid exit). Param: script = pointer to the loaded script object. Call when done with a script l"),
    "004B53B0": ("QspriteRegister4Az", "Registers a QUAD-SPRITE with full transform data: 14 args, float parameters scaled by constant 0x534AB0, writes sprite tables 0xA84A50/0xA84A58 (verified). Low-"),
    "004B5B90": ("IsResourceLoaded", "Checks whether a virtual resource is already loaded and optionally returns its table entry. Params: resourcePath = virtual path to test, outEntry = receives the"),
    "004B5F00": ("ResourceLoad", "Loads a VIRTUAL RESOURCE (path like 'LOCAL:...' or 'MISSION:...') into memory: emits 'Failed to load resource: '%s'' on miss. Params: resourcePath = virtual res"),
    "004B6380": ("Resource_Unload", "Name from igi.exe error string inside function: \"Resource_Unload() : Resource '%s' is not loaded.\" Unloads a resource by name/path."),
    "004B63D0": ("Resource_Flush", "Name from igi.exe error string inside function: \"Resource_Flush() : Couldn't locate resource at %p\". Flushes/finalizes resource entries."),
    "004B6E70": ("PictureGetWidth", "RETURNS the WIDTH in pixels of a loaded picture/surface. Param: picture = pointer from a picture-load call. Thin thunk to fcn.004B7DF0 (byte-verified)."),
    "004B6E80": ("PictureGetHeight", "RETURNS the HEIGHT in pixels of a loaded picture/surface. Param: picture = picture pointer. Thin thunk to fcn.004B7E00."),
    "004B7E80": ("SymbolRegisterInt16", "Registers a int16 game-data symbol: thin thunk that calls the core registrar QTaskHashTableSet (0x4BAAC0) with a fixed argument tail (1,1,0,1,handler 0x4B7F20-f"),
    "004B7EE0": ("SymbolRegisterBool8", "Registers a bool8 (byte 0/1) game-data symbol: thin thunk that calls the core registrar QTaskHashTableSet (0x4BAAC0) with a fixed argument tail (1,1,0,1,handler"),
    "004B7FA0": ("SymbolRegisterInt32", "Registers a int32 game-data symbol: thin thunk that calls the core registrar QTaskHashTableSet (0x4BAAC0) with a fixed argument tail (1,1,0,1,handler 0x4B7F40-f"),
    "004B7FC0": ("SymbolRegisterReal32", "Registers a real32 (float) game-data symbol: thin thunk that calls the core registrar QTaskHashTableSet (0x4BAAC0) with a fixed argument tail (1,1,0,1,handler 0"),
    "004B80A0": ("GameDataSymbolRemove", "Removes game data symbol for game like internal vairables,UI controls,timers etc."),
    "004B80B0": ("QvmLoad", "Compiles and Load any .qvm file into memory, Params: any qvm file name,  Returns filename loaded."),
    "004B83D0": ("CompilerCleanup", "Cleanup files after compiling, Params: File passed to CompileQVM"),
    "004B8410": ("QscCompile", "Compiles a .QSC script source into executable QVM form - body contains the output-extension strings '.qvm' and '.qas' plus 'An error occured when compiling file"),
    "004B85B0": ("QvmCompile", "Compiles a script file into a QVM program, reporting failures with 'Error in QVM program: %s' and 'An error occured in script file: %s'. Param: scriptFile = vir"),
    "004B8810": ("TasktypeSet", "Defines new constants for game and scripts ,Params: task_str (int**)WEAPONTYPE_PISTOL, task_id"),
    "004B8890": ("GameDefineOptions", "Define game options constants , Params: opt_str (int**)'DefineAmmoType'"),
    "004B8930": ("Script_SetSymbolContext", "Name from igi.exe error string inside function: \"Script_SetSymbolContext(): Symbol not found: %s\". Sets the symbol context for subsequent script operations."),
    "004B8C10": ("BreakScript", "Breaks/aborts the currently-executing script at this point (70-byte function). Takes no args. Use as an early-exit inside .qsc scripts."),
    "004B8C60": ("_Script_SetWarningLevel", "Sets how loudly the script system reports warnings while parsing/running (igi.exe embeds its name WITH leading underscore: '_Script_SetWarningLevel'). Param: le"),
    "004BAAC0": ("QTaskHashTableSet", "THE CORE REGISTRAR: inserts an entry into the task/hash table binding a name-value pair to a handler callback. All 7 stack args confirmed by disassembly header "),
    "004BB270": ("QvmAssemble", "Assembles a QVM SCRIPT SOURCE into binary form: runs a full lexer/parser over the source (embedded regex patterns '[a-zA-Z][a-zA-Z0-9_]*:', '[ \\t\\n\\r]+', commen"),
    "004BBC30": ("LogAdd", "Adds a formatted line to the engine log - printf-style variadic (function formats through vsprintf helper fcn.004A5702; r2 header args sp[0x4..0x8]). Param: for"),
    "004BBCB0": ("QvmParse", "Parses a script file and GENERATES ASSEMBLY CODE (own log line: 'Parsing script and generating assembly code.'). Writes the assembly to outputFile ('Failed to o"),
    "004C0200": ("ScriptBufInit", "Initializes the four script-buffer control fields used by the script engine (pure field writer, no calls). Params: buf1/buf2 = buffer structure pointers, buf = "),
    "004C0460": ("SymbolRemove", "Removes a symbol from the game-data symbol table. Params: p1 = symbol-table context, symbol_name = name/reference of the symbol to remove."),
    "004C0560": ("SymbolCheck", "Check symbol in QTask list if already loaded, Params: symbol_name like 'TaskType_Set', p1,p3 ??"),
    "004C4520": ("DefineMagicObj", "Defines a MAGIC OBJECT type during magicobj definition parsing (pairs with the MAGICOBJ\\ folder data). Parser-context only."),
    "004C48E0": ("RigidDyncubeObjRead", "Read rigid dynCube config file , Params: config file of rigid dynCube."),
    "004C4930": ("MagicObjLoad", "Loads magic objects from path, Params: Path 'LOCAL:magicobj'"),
    "004C6760": ("CreateTerrainTileMap", "Creates the TERRAIN TILE MAP for a level during level load (113-byte function). Engine-internal: called by the terrain loader, not meant for gameplay scripts."),
    "004E68D0": ("SoundLoad", "Load all level sounds from path , Params: Path of sound like 'MISSION:sounds'"),
    "004E8C60": ("DefineSound", "Defines a SOUND entry (file + attenuation params) inside sound definition blocks - OpenIGI reimplements it as SoundDefinitionRegistry.Define(SoundDefinitionKind"),
    "004E9EC0": ("DefineTriggerOnce", "Defines a fire-once TRIGGER entry inside definition blocks - OpenIGI maps it to SoundDefinitionKind.TriggerOnce. Parser-context only."),
    "004EAD20": ("DefineGraph", "Defines a GRAPH (sound/graph transition graph) entry inside definition blocks - OpenIGI maps it to SoundDefinitionKind.Graph. Parser-context only."),
    "004EBA90": ("DefineGroup", "Defines a GROUP entry (sound-group/entity grouping) during definition parsing. Parser-context only."),
    "004EC070": ("AnimTrigger_ParseConfigFile", "Name from igi.exe error string INSIDE this function: \"AnimTrigger_ParseConfigFile(): Couldn't load script: %s\" @0x54DB98. Parses an animtrigger config file into"),
    "004EC0C0": ("AnimTriggerLoad", "Loads anim trigger objects from path, Params: Path 'LOCAL:animtrigger'"),
    "004EDFE0": ("PhysicsObjType_ParseConfigFile", "Name from igi.exe error string inside function: \"PhysicsObjType_ParseConfigFile(): Couldn't load script\" @0x54DC7C. Parses a physicsobj type config."),
    "004EE030": ("PhysicsObjLoad", "Loads physics objects from path, Params: Path 'LOCAL:physicsobj'"),
    "004F0740": ("Task_DeclareParameters", "Declares the parameter list of the task currently being defined inside a .qsc task block (OpenIGI TaskScriptCommands implements it reading a type name + paramet"),
    "004F0780": ("Task_New", "Instantiates a new game task from a declared type (731-byte factory; OpenIGI registers Task_New reading the type name then declared params). Call inside task bl"),
    "004F0CF0": ("ConfigCompile", "Compiles CONFIG script text into executable task form - body references 'Task_New' (the task factory it emits calls to). Params: context = compilation context, "),
    "004F0E10": ("Level_LoadObjects", "Loads all OBJECTS for the level: reads the level object set and instantiates each object entity in the world. Takes the level/path argument from the calling loa"),
    "004F0E50": ("ScriptInit", "Initialises the script system for a file. Params: file_name = script path, p2 = byte flag (observed), p3 = int option, p4 = byte flag. Refined types from decomp"),
    "004F0E90": ("QtaskUpdate", "Update QTask hash table call before loading level."),
    "004F9FF0": ("GraphOpen", "Open graph of level,Params: with str 'Graph4019.dat'"),
}

count = 0
for hexaddr, (name, note) in NATIVES.items():
    addr = af.getAddress(hexaddr)
    fn = fm.getFunctionAt(addr)
    if fn is None:
        from ghidra.app.cmd.function import CreateFunctionCmd
        from ghidra.util.task import ConsoleTaskMonitor
        CreateFunctionCmd(addr).applyTo(currentProgram, ConsoleTaskMonitor())
        fn = fm.getFunctionAt(addr)
    if fn:
        st.createLabel(addr, name, SourceType.USER_DEFINED)
        if note:
            from ghidra.program.model.listing import CodeUnit
            cu = currentProgram.getListing().getCodeUnitAt(addr)
            if cu:
                cu.setComment(CodeUnit.PRE_COMMENT, note)
        count += 1
print("Applied %d IGI1 native symbols" % count)
