// Auto-generated from IGI-Natives.json by tools/generate_native_assets.py
#include <idc.idc>
static main() {
  SetBatch(1);
  MakeNameEx(0x004EC070, "AnimTrigger_ParseConfigFile", SN_NOWARN);
  SetFunctionCmt(0x004EC070, "Name from igi.exe error string INSIDE this function: \"AnimTrigger_ParseConfigFile(): Couldn't load script: %s\" @0x54DB98. Parses an animtrigger config file into trigger entries.", 1);
  MakeNameEx(0x004B83D0, "Qvm_Cleanup", SN_NOWARN);
  SetFunctionCmt(0x004B83D0, "Frees a loaded QVM script object: reads qvm+0x8C and releases the program block when non-zero. Param: qvm = pointer from Qvm_Load. Pair with Qvm_Load to avoid leaks.", 1);
  MakeNameEx(0x004F0CF0, "Config_Compile", SN_NOWARN);
  SetFunctionCmt(0x004F0CF0, "Compiles a CONFIG script: validates context, then loads its compiled QVM via QvmLoad (0x4B80B0); references the Task_New name during task-table wiring. Params: context = config context id, cfgName = config path/name, flags = compile flags. Use when (re)loading game configuration programmatically.", 1);
  MakeNameEx(0x00405850, "Config_Read", SN_NOWARN);
  SetFunctionCmt(0x00405850, "Read game config file, Params:  File: 'LOCAL:config.qsc'", 1);
  MakeNameEx(0x00405BD0, "Config_Write", SN_NOWARN);
  SetFunctionCmt(0x00405BD0, "Write game config file, Params: File: 'LOCAL:config.qsc'", 1);
  MakeNameEx(0x00415AB0, "Game_CutsceneDelete", SN_NOWARN);
  SetFunctionCmt(0x00415AB0, "Deletes/ends the running cutscene and frees its resources. Takes no args. | OUTRO USAGE: each level OBJECTS.QVM ends with a ConditionalContainer Task_New named \"Outro cutscene\" (condition e.g. \"AreaActivate_156.nActive && !HumanPlayer_0.isDead\") that calls MenuManager_SetEnabled(FALSE)+Game_DisableMusic()+THIS FUNCTION before playing the exit CutScene (e.g. CutScene_2222 heli escape), then restores menus/music on finish. TO REMOVE OUTROS: either patch that container condition to FALSE per OBJECTS.QVM, or hook CutScene_TaskUpdate 0x4F51D0 to complete instantly (generic - kills intro+outro in all levels). LEVEL4 example verified via OpenIGI QvmDisasm.", 1);
  MakeNameEx(0x004AF7B0, "Error_Show", SN_NOWARN);
  SetFunctionCmt(0x004AF7B0, "Shows a fatal-error dialog: printf-style FORMAT STRING + variadic args (e.g. push \"Level_Load(): Couldn't load script: %s\"; push scriptPath; call). Param: format = printf-style string, followed by substitution args. Variadic - proven by retail call sites (add esp,8 cleanup) and vsprintf helper fcn.004A5702.", 1);
  MakeNameEx(0x00402820, "Frames_Set", SN_NOWARN);
  SetFunctionCmt(0x00402820, "Set game frames, Params: 30,60 max 240FPS.", 1);
  MakeNameEx(0x00408350, "GameMaterial_LoadParameters", SN_NOWARN);
  SetFunctionCmt(0x00408350, "Name from igi.exe error string inside function: \"GameMaterial_LoadParameters: Couldn't load script \\\"%s\\\"\". Loads game-material parameters from its script.", 1);
  MakeNameEx(0x00403B70, "Config_ResetGraphicOptions", SN_NOWARN);
  SetFunctionCmt(0x00403B70, "Resets graphic options to FACTORY DEFAULTS - machine-verified field writes: width=0x280 (640), height=0x1E0 (480), plus clearing adjacent flag bytes on the profile record. Takes no script args. Registered by igi.exe as \"Config_ResetGraphicOptions\" (site 0x40352B) and called by retail MAINMENU.QVM. Use to restore 640x480 defaults programmatically.", 1);
  MakeNameEx(0x004F9FF0, "Graph_Open", SN_NOWARN);
  SetFunctionCmt(0x004F9FF0, "Open graph of level,Params: with str 'Graph4019.dat'", 1);
  MakeNameEx(0x004137A0, "HumanPlayer_LoadParameters", SN_NOWARN);
  SetFunctionCmt(0x004137A0, "Name from igi.exe error string inside function: \"HumanPlayer_LoadParameters: Couldn't load script \\\"%s\\\"\". Loads humanplayer parameters (weapons/ammo/cycle definitions) from script.", 1);
  MakeNameEx(0x004157D0, "Game_DisablePlayerInput", SN_NOWARN);
  SetFunctionCmt(0x004157D0, "Disables ALL player input (keyboard+mouse) - used by cutscenes/menus. Re-enable with Game_EnablePlayerInput.", 1);
  MakeNameEx(0x00415830, "Game_EnablePlayerInput", SN_NOWARN);
  SetFunctionCmt(0x00415830, "Re-enables player input after Game_DisablePlayerInput. Takes no args.", 1);
  MakeNameEx(0x004BBC30, "Log_Add", SN_NOWARN);
  SetFunctionCmt(0x004BBC30, "Appends a formatted line to the engine log (variadic printf-style, giant 0x400 format buffer at esp+0x404). Only logs when log-enabled globals 0xA43EC8/0xA43ED4 are set. Param: format = printf-style string + substitution args. Gate your spammy logs behind the enable flags.", 1);
  MakeNameEx(0x004F0E10, "Level_LoadObjects", SN_NOWARN);
  SetFunctionCmt(0x004F0E10, "Loads all OBJECTS for the level: reads the level object set and instantiates each object entity in the world. Takes the level/path argument from the calling load script. Use during level-load flow before Level_Start. [Name corrected per retail analysis: was LevelLoad/LevelQuit/LevelRestart.]", 1);
  MakeNameEx(0x00416550, "Game_DeleteHandler", SN_NOWARN);
  SetFunctionCmt(0x00416550, "The game's DELETE handler - runs when a level/game session is torn down (quit path), releasing entities and session state. Takes no args. Engine-internal teardown; do not call to 'quit' - it is the cleanup callback. [Name corrected per retail analysis: was LevelLoad/LevelQuit/LevelRestart.]", 1);
  MakeNameEx(0x00416FE0, "Game_Restart", SN_NOWARN);
  SetFunctionCmt(0x00416FE0, "Restarts the CURRENT LEVEL/session: tears down and reloads the running game state (the Ctrl+F4-style restart path). Takes no args. Use to reset the mission without going back to menus. [Name corrected per retail analysis: was LevelLoad/LevelQuit/LevelRestart.]", 1);
  MakeNameEx(0x00415B30, "Level_Start", SN_NOWARN);
  SetFunctionCmt(0x00415B30, "Start new level, Params:  p1: 0057BABC", 1);
  MakeNameEx(0x00418B00, "Menu_Manager", SN_NOWARN);
  SetFunctionCmt(0x00418B00, "MenuManager load for inagame or Mainmenu,Params:  p1: 0057BABC ,p3,p4,p5: 0.", 1);
  MakeNameEx(0x00415A60, "Game_DisableMusic", SN_NOWARN);
  SetFunctionCmt(0x00415A60, "Stops the music engine. Takes no args.", 1);
  MakeNameEx(0x00415A10, "Game_EnableMusic", SN_NOWARN);
  SetFunctionCmt(0x00415A10, "Starts/resumes the music engine. Takes no args.", 1);
  MakeNameEx(0x00495F30, "Music_SetSfxVolume", SN_NOWARN);
  SetFunctionCmt(0x00495F30, "Sets the SFX bus volume feeding the music/sound mix path. Param: volume = float 0.0-1.0 scaled by global factor. Use for live SFX fade.", 1);
  MakeNameEx(0x00495E70, "Music_SetVolume", SN_NOWARN);
  SetFunctionCmt(0x00495E70, "Sets BOTH music engine volumes (likely front/master pair) after scaling by the global music factor. Params: volume1, volume2 = floats 0.0-1.0 scaled against settings. Use for live music fades.", 1);
  MakeNameEx(0x004158E0, "Game_UpdateVolume", SN_NOWARN);
  SetFunctionCmt(0x004158E0, "Applies current profile music/sfx volumes to the live audio engines. Takes no args.", 1);
  MakeNameEx(0x004EDFE0, "PhysicsObjType_ParseConfigFile", SN_NOWARN);
  SetFunctionCmt(0x004EDFE0, "Name from igi.exe error string inside function: \"PhysicsObjType_ParseConfigFile(): Couldn't load script\" @0x54DC7C. Parses a physicsobj type config.", 1);
  MakeNameEx(0x004B0D60, "Qhash_Init", SN_NOWARN);
  SetFunctionCmt(0x004B0D60, "Init hash table value, Params: hash value 0 or 1.", 1);
  MakeNameEx(0x004B0D90, "Qhash_Reset", SN_NOWARN);
  SetFunctionCmt(0x004B0D90, "Reset QTask type hash table.", 1);
  MakeNameEx(0x004B8410, "Qsc_Compile", SN_NOWARN);
  SetFunctionCmt(0x004B8410, "Compiles a .qsc SCRIPT SOURCE into a .qvm binary: resolves the path (fcn_004B5B60), pulls the source through ResourceLoad (0x4B5F00), allocates a 0x94-byte compiler context via Mem_Alloc, emits \".qvm\" output. Param: qscPath = script source path. RETURNS result object/flag.", 1);
  MakeNameEx(0x004F0E90, "Qtask_Update", SN_NOWARN);
  SetFunctionCmt(0x004F0E90, "Update QTask hash table call before loading level.", 1);
  MakeNameEx(0x00401B20, "Qtask_UpdateList", SN_NOWARN);
  SetFunctionCmt(0x00401B20, "Update all QTask list, Params: p1 ??", 1);
  MakeNameEx(0x004BB270, "QScript_Assemble", SN_NOWARN);
  SetFunctionCmt(0x004BB270, "ASSEMBLER stage of the script pipeline: strips comments via regex \"{.*:(.*//)*}.*\", initialises the parser (\"Initialising parser.\"), generates assembly code and WRITES IT TO \"LOCAL:qvmbin.tmp\" (also referenced as /0qvmbin.tmp). Params: srcText = script source buffer, srcLen2 = secondary length/context arg. Returns assembly result.", 1);
  MakeNameEx(0x004B85B0, "Qvm_Execute", SN_NOWARN);
  SetFunctionCmt(0x004B85B0, "EXECUTES a loaded QVM script program (the interpreter entry - despite the old analyst label QvmRead). On runtime failure reports \"Error in QVM program: %s\" / \"An error occured in script file: %s\". Param: qvm = pointer from Qvm_Load. RETURNS script result value.", 1);
  MakeNameEx(0x004B80B0, "Qvm_Load", SN_NOWARN);
  SetFunctionCmt(0x004B80B0, "Loads a COMPILED .qvm script binary from the virtual filesystem (appends/selects \".qvm\"; big 0x130 stack frame builds the script object). Param: qvmPath = path like \"LOCAL:common/ai/guard.qvm\". RETURNS pointer to the loaded QVM object, 0 on failure (calls engine debug-state check 0x48F1D0 first). Use before executing/attaching scripts.", 1);
  MakeNameEx(0x004BBCB0, "QScript_ParseAndAssemble", SN_NOWARN);
  SetFunctionCmt(0x004BBCB0, "PARSE+CODEGEN driver: logs \"Parsing script and generating assembly code.\", runs parser state globals (0xA442D0..), writes output (\"Failed to open file '%s' for writing.\"). Params: srcText = script source, options = parser option word. Part of the QscCompile pipeline feeding QScript_Assemble.", 1);
  MakeNameEx(0x004B63D0, "Resource_Flush", SN_NOWARN);
  SetFunctionCmt(0x004B63D0, "Flushes/finalizes ONE resource entry: walks the global resource list (0x943E38), matches entry+0x34 against the argument, errors \"Resource_Flush() : Couldn't locate resource at %p.\" when absent. Param: resEntry = resource pointer/address to flush.", 1);
  MakeNameEx(0x004B5F00, "Resource_Load", SN_NOWARN);
  SetFunctionCmt(0x004B5F00, "Loads a resource into memory WITH CACHE CHECK: first asks IsResourceLoaded (0x4B5B90); if cached returns the existing entry, otherwise loads and registers it. Params: resourcePath = virtual resource path, outBuffer = receives the data pointer. RETURNS resource entry pointer.", 1);
  MakeNameEx(0x004B6380, "Resource_Unload", SN_NOWARN);
  SetFunctionCmt(0x004B6380, "Name from igi.exe error string inside function: \"Resource_Unload() : Resource '%s' is not loaded.\" Unloads a resource by name/path.", 1);
  MakeNameEx(0x004B5B90, "Is_ResourceLoaded", SN_NOWARN);
  SetFunctionCmt(0x004B5B90, "Checks whether a resource path is ALREADY LOADED in the resource manager (walks path handling backslash 0x5C segments against the registry). Params: resourcePath = virtual path, outEntry = receives matching entry. RETURNS non-zero + fills outEntry when found. Resource_Load calls this first - use it to avoid double-loading.", 1);
  MakeNameEx(0x004B18B0, "Resource_PackUnpack", SN_NOWARN);
  SetFunctionCmt(0x004B18B0, "Opens a PACKED resource file via QFile_ReadWrite (0x4B1510, mode string at 0x53B604) and unpacks its contents through the pack table at 0x9436E8. Params: resFile = packed resource path, outBuffer = receives unpacked data. RETURNS entry/result pointer.", 1);
  MakeNameEx(0x004B16D0, "Resource_Unpack", SN_NOWARN);
  SetFunctionCmt(0x004B16D0, "Unpacks a loaded resource blob to a destination address. Params: resPtr = packed resource pointer, destAddr = destination memory address, resSize = bytes to unpack. RETURNS unpacked size/status.", 1);
  MakeNameEx(0x004F0E50, "Script_Init", SN_NOWARN);
  SetFunctionCmt(0x004F0E50, "Initialises the script system for a file. Params: file_name = script path, p2 = byte flag (observed), p3 = int option, p4 = byte flag. Refined types from decompiled header (two int8_t slots detected).", 1);
  MakeNameEx(0x004B8930, "Script_SetSymbolContext", SN_NOWARN);
  SetFunctionCmt(0x004B8930, "Name from igi.exe error string inside function: \"Script_SetSymbolContext(): Symbol not found: %s\". Sets the symbol context for subsequent script operations.", 1);
  MakeNameEx(0x00485AD0, "StatusMessageScreen_ClearMessages", SN_NOWARN);
  SetFunctionCmt(0x00485AD0, "Clears all on-screen status messages. Takes no args.", 1);
  MakeNameEx(0x00485970, "StatusMessage_ShowFull", SN_NOWARN);
  SetFunctionCmt(0x00485970, "Full-parameter status message: queues an on-screen HUD message with icon and styling (allocates via Mem_Alloc, reads current status word 0x540A8C). Params: timer = display duration, message = text, sprite = HUD sprite/icon ptr, styleByte = display style byte. Use MISC::STATUS_MESSAGE_SHOW wrapper for simple cases.", 1);
  MakeNameEx(0x004C0460, "Symbol_Remove", SN_NOWARN);
  SetFunctionCmt(0x004C0460, "Removes a symbol from the game-data symbol hash table; warns \"Unable to remove symbol \\\"%s\\\" (not registered)\" when absent. Params: symTable = symbol table, symName = symbol name string. RETURNS non-zero on success. Call after dynamically registered symbols are no longer needed.", 1);
  MakeNameEx(0x004B8810, "TaskType_Set", SN_NOWARN);
  SetFunctionCmt(0x004B8810, "Stores the TYPE ID onto a task definition structure (simple field write, verified 2-arg store). Params: taskDef = task definition object, taskTypeId = TASKTYPE_* enum value (TASKTYPE_GUN, TASKTYPE_BUILDING, etc. - full enum embedded in igi.exe .data).", 1);
  MakeNameEx(0x004AF810, "Warning_Show", SN_NOWARN);
  SetFunctionCmt(0x004AF810, "Shows a warning dialog - printf-style variadic like ErrorShow (retail: push str.\"QTasktype \\\"%s\\\"...\"; push eax; call -> add esp,8). Param: format = printf-style string + substitution args.", 1);
  MakeNameEx(0x004071E0, "Weapon_ConfigRead", SN_NOWARN);
  SetFunctionCmt(0x004071E0, "Reads weapon configuration entries from parsed config text: repeated repne-scasb string scans + block copies populate weapon structures. Params: context = weapon system context, cfgText = config text buffer. Use within weapon definition parsing flows.", 1);
  MakeNameEx(0x004C0560, "Symbol_CheckRegister", SN_NOWARN);
  SetFunctionCmt(0x004C0560, "Checks a symbol and registers it if new - ERRORS via ErrorShow(\"Symbol \\\"%s\\\" already registered in hash table\") if the name ALREADY exists, so it doubles as duplicate protection. Params: symTable, symName, extra = registration payload/flags. RETURNS symbol entry or triggers the error dialog.", 1);
  MakeNameEx(0x004B8890, "Game_DefineOptions", SN_NOWARN);
  SetFunctionCmt(0x004B8890, "Define game options constants , Params: opt_str (int**)'DefineAmmoType'", 1);
  MakeNameEx(0x004C0200, "Script_BufInit", SN_NOWARN);
  SetFunctionCmt(0x004C0200, "Initialises the four header fields of a SCRIPT BUFFER structure (verified field-by-field stores: *out=buf2, then buf3, bufSize...). Params: outBuf1 = buffer struct to init, buf2/buf3 = buffer pointers/ids, bufSize = size field. Call before handing a buffer to the QVM assembler/parsers.", 1);
  MakeNameEx(0x004E68D0, "Sound_Load", SN_NOWARN);
  SetFunctionCmt(0x004E68D0, "Load all level sounds from path , Params: Path of sound like 'MISSION:sounds'", 1);
  MakeNameEx(0x004B0C60, "Mem_Alloc", SN_NOWARN);
  SetFunctionCmt(0x004B0C60, "Engine heap allocator. Params: numBytes = bytes to allocate, tag = allocation bucket shown in the 'Total allocated by user' accounting. RETURNS pointer or 0 on failure (error text: 'Mem_Alloc() failed to allocate %d bytes'). Pair with MemoryDealloc/MemDealloc free path.", 1);
  MakeNameEx(0x004B0BE0, "Mem_DeallocAll", SN_NOWARN);
  SetFunctionCmt(0x004B0BE0, "Deallocate allocated memory. Frees EVERY tracked heap block (walks allocation list via 0x4B0D10), then warns \"%d block(s) of memory have not been deallocated.\" Takes no args - NOT a single-pointer free.", 1);
  MakeNameEx(0x00484E60, "Mission_Open", SN_NOWARN);
  SetFunctionCmt(0x00484E60, "Name from igi.exe error string inside function: \"Mission_Open(): Couldn't load script: %s\". Opens a mission definition script and builds its task tree.", 1);
  MakeNameEx(0x004A5350, "File_Open", SN_NOWARN);
  SetFunctionCmt(0x004A5350, "Low-level CRT-style file open used across the engine. Params: path = file path, mode = fopen-style mode string (\"r\",\"w\",\"rb\"...). RETURNS FILE* handle or 0. Prefer QFile_ReadWrite/QResource APIs unless you need raw stdio.", 1);
  MakeNameEx(0x004B1510, "QFile_ReadWrite", SN_NOWARN);
  SetFunctionCmt(0x004B1510, "VIRTUAL-filesystem open: parses the device prefix from vpath (errors \"Illegal device name in path: \\\" and \"Device not present: %s\"), routes to the device handler chain (0x4B1620/0x4B1020/0x4B11A0) and returns a Q-file handle. Params: vpath = virtual path WITH device prefix (e.g. \"LOCAL:...\", \"MENU:\"), mode = access mode. RETURNS handle or 0. This is the correct opener for LOCAL:/MISSION: paths.", 1);
  MakeNameEx(0x004C48E0, "Rigid_DyncubeObjRead", SN_NOWARN);
  SetFunctionCmt(0x004C48E0, "Read rigid dynCube config file , Params: config file of rigid dynCube.", 1);
  MakeNameEx(0x004C4930, "Magic_ObjLoad", SN_NOWARN);
  SetFunctionCmt(0x004C4930, "Loads magic objects from path, Params: Path 'LOCAL:magicobj'", 1);
  MakeNameEx(0x004EC0C0, "Anim_TriggerLoad", SN_NOWARN);
  SetFunctionCmt(0x004EC0C0, "Loads anim trigger objects from path, Params: Path 'LOCAL:animtrigger'", 1);
  MakeNameEx(0x004EE030, "Physics_ObjLoad", SN_NOWARN);
  SetFunctionCmt(0x004EE030, "Loads physics objects from path, Params: Path 'LOCAL:physicsobj'", 1);
  MakeNameEx(0x0047CAB0, "Ammo_TypeOpen", SN_NOWARN);
  SetFunctionCmt(0x0047CAB0, "Open ammo qvm file to memory for all weapons loaded.", 1);
  MakeNameEx(0x00413B70, "Weapon_TypeOpen", SN_NOWARN);
  SetFunctionCmt(0x00413B70, "Open all weapons defined in .qsc file for Humanplayer.", 1);
  MakeNameEx(0x004A53B3, "Game_DataSymbolLoad", SN_NOWARN);
  SetFunctionCmt(0x004A53B3, "Parses game-data SYMBOL DEFINITIONS from a buffer into the symbol table: tokenizes via 0x4A7720 with per-name limit 0x42 (66 bytes) and count cap 0x7FFFFFFF, null-terminates each parsed name. Params: symBuf = symbol buffer base, symPath = source path ref, symName = initial name entry. RETURNS parse status. Feeds the table that Symbol_Register*/GameData_SymbolRemove operate on.", 1);
  MakeNameEx(0x004B80A0, "Game_DataSymbolRemoveThunk", SN_NOWARN);
  SetFunctionCmt(0x004B80A0, "Thin remover for the game-data symbol table: forwards its single argument down the removal chain (verified pure thunk returning eax). Param: symBuf = symbol/buffer to unregister. Prefer this over direct internal calls.", 1);
  MakeNameEx(0x004B7EE0, "SymbolRegister_Bool8", SN_NOWARN);
  SetFunctionCmt(0x004B7EE0, "Registers a BOOL8-TYPED script variable slot in the game-data symbol table (2-arg typed thunk family; each sibling hardcodes its type size). Params: table = symbol table, name = variable name. RETURNS the registered symbol entry. Script code can then read/write it as a bool.", 1);
  MakeNameEx(0x004B7E80, "SymbolRegister_Int16", SN_NOWARN);
  SetFunctionCmt(0x004B7E80, "Registers an INT16-typed script variable slot. Params: table, name. RETURNS symbol entry. Sibling of SymbolRegister_Bool8/Int32/Real32 - same thunk shape, different type tag.", 1);
  MakeNameEx(0x004B7FA0, "SymbolRegister_Int32", SN_NOWARN);
  SetFunctionCmt(0x004B7FA0, "Registers an INT32-typed script variable slot. Params: table, name. RETURNS symbol entry. This is the common integer script-variable registration used by AI/game scripts.", 1);
  MakeNameEx(0x004B7FC0, "SymbolRegister_Real32", SN_NOWARN);
  SetFunctionCmt(0x004B7FC0, "Registers a REAL32 (float)-typed script variable slot. Params: table, name. RETURNS symbol entry. Pairs with AIFunction_Set/GetScriptRealValue for float storage.", 1);
  MakeNameEx(0x0048A440, "LoadingScreen_Show", SN_NOWARN);
  SetFunctionCmt(0x0048A440, "Shows the LOADING SCREEN: allocates a 0x1C-byte screen object, queries the active display mode (0x491CF0), and loads \"LOCAL:menusystem/loadingscreen.res\" with picture \"LOCAL:menusystem/loading.pic\" - or \"loading_us.pic\" for USA country builds. Param: picVariant = loading-screen type selector. Call before long loads so the player sees feedback.", 1);
  MakeNameEx(0x004BAAC0, "Q_TaskHashTableSet", SN_NOWARN);
  SetFunctionCmt(0x004BAAC0, "THE CORE REGISTRAR: inserts an entry into the task/hash table binding a name-value pair to a handler callback. All 7 stack args confirmed by disassembly header (arg_18h..arg_3Ch). Every SymbolRegister* thunk (e.g. 0x4B7EE0 pushes 1,1,0,1,addr,handler,table -> this) and every GAME_DEFINE_OPTIONS registration routes here. Params: table = target hash table, handler = callback invoked for the symbol, nameVal = name/value ref, p4-p7 = type/flag slots (see SymbolRegister thunks for known values).", 1);
  MakeNameEx(0x00413BB0, "Weapons_CountGet", SN_NOWARN);
  SetFunctionCmt(0x00413BB0, "RETURNS the number of weapons defined for the human player: reads global counter 0x57B18C (exactly `mov eax,[0x57B18C]; ret`). That counter is written by the DefineHumanPlayerWeaponCycle definition parser - so this reflects the current weapon-cycle list length. Use to bounds-check weapon indexes before Weapon_GunPickup-style calls.", 1);
  MakeNameEx(0x0045FFC0, "Weapon_GunPickup", SN_NOWARN);
  SetFunctionCmt(0x0045FFC0, "Gives a GUN pickup to the player: checks the player's already-carried flag (player+0xCF5), reads the weapon id from pickupEntity+8 -> word +0x1C, validates the weapon category via 0x401CF0, hands the weapon over (0x477BF0/0x477C50) and plays the 'weaponpickup_1' sound (0x47CE00/0x4E7200). Params: player = player/Human struct ptr, pickupEntity = the picked-up world entity. Use for custom weapon pickups.", 1);
  MakeNameEx(0x0045FF80, "Weapon_AmmoPickup", SN_NOWARN);
  SetFunctionCmt(0x0045FF80, "Gives an AMMO pickup to the player (same struct conventions as Weapon_GunPickup: player carry-flags and pickup-entity fields drive the grant; plays the pickup sound). Params: player = player struct ptr, pickupEntity = ammo world entity. Use for custom ammo pickups.", 1);
  MakeNameEx(0x00416D80, "Human_HitDamage", SN_NOWARN);
  SetFunctionCmt(0x00416D80, "Reads the player XP/hit byte: returns byte [PlayerPtr+0xE1]. Takes no args. Documented alias of HUMAN_HIT_DAMAGE - same address.", 1);
  MakeNameEx(0x00463760, "Human_ViewCam", SN_NOWARN);
  SetFunctionCmt(0x00463760, "Sets the human's VIEW-CAMERA selector: stores camValue into human struct offset +0x4F0 (verified: mov [ecx+0x4F0],eax; ret - 5-byte setter). Params: human = Human/soldier struct ptr, camValue = camera mode index. Use to switch a soldier's view/camera state directly.", 1);
  MakeNameEx(0x004659E0, "Human_TaskViewReset", SN_NOWARN);
  SetFunctionCmt(0x004659E0, "Resets the human's VIEW TANGENT fields to retail defaults: computes tan() of the half-FOV globals 0x5335E8/0x5339C0 (the same globals ENHANCER::FOV_SET writes) and stores them into human+0x1E4 and human+0x1E8, clearing human+0x1EC. Param: human = Human/soldier struct ptr. This is THE retail restore path - call after custom FOV/binocular zoom to return to normal view.", 1);
  MakeNameEx(0x00406220, "Config_GetActivePlayerProfileRecord", SN_NOWARN);
  SetFunctionCmt(0x00406220, "RETURNS pointer to the ACTIVE PROFILE's graphic-options/config record: computed as 0xBC2388 + 0xD14*[0xBC2384] (verified against retail defaults-reset fcn.00403B70 which walks the same layout). Takes no args. Despite the historical name this returns a record pointer, not a bool. Old analyst name IsPlayerProfileActive was wrong - it returns the record pointer, not a bool.", 1);
  MakeNameEx(0x0045C440, "Soldier_Execute", SN_NOWARN);
  SetFunctionCmt(0x0045C440, "Executes/initializes a SOLDIER AI entity in the level. Params: context = task/context object (2nd arg is the soldier ptr - verified: esi=[esp+0x1C] after prologue). The function reads soldier-struct fields +0x800 (ptr), +0x4C4 and +0x254 (sub-object bases passed to spawner 0x4F2060), +0xD1C, then installs a per-soldier callback (0x45C700) into the created object at +0x14 and routes through 0x48A330. Referenced via soldier-task VTABLE at .data 0x53EC90 (not called directly). SOLDIER STRUCT LAYOUT (recovered from the 0x45C190-0x45CA50 vtable family): +0x68 name/string area; +0x254 patrol/waypoint sub-struct (field +0x94 used); +0x2EC param ptr slot; +0x33D flag byte; +0x4C4 object ref; +0x696 active/enable flag (0=off, 1=on); +0x800 ptr; +0xD0C id (0xFFFFFFFF = unset); +0xD14 dword; +0xD1C ptr. Sibling vtable methods: 0x45C190, 0x45C1C0, 0x45C2E0, 0x45C330, 0x45C5A0, 0x45C650, 0x45C750, 0x45C8B0, 0x45CA50 (same struct, enable/disable/reset semantics).", 1);
  MakeNameEx(0x00402780, "Flow_RequestEvent", SN_NOWARN);
  SetFunctionCmt(0x00402780, "Requests a flow-task event by id (drives the level's flow state machine). Param: eventId = flow event number used in the level flow script. Use from mission flow scripts to trigger scripted transitions. FLOW_EVENT enum: None=0, QUIT=1, INTRO=2, MAINMENU=3, GAME=4, RESTART_GAME=5 (events 6-8 exist internally but have no registered constants).", 1);
  MakeNameEx(0x004036B0, "GO_Player", SN_NOWARN);
  SetFunctionCmt(0x004036B0, "Adds a player profile named 'name' to the config while a .cfg/GO script block is being read; subsequent GO_* settings apply to this profile. Param: name = profile display name (string). Use inside config/profile scripts, must come before that profile's GO_* settings. Returns 1.", 1);
  MakeNameEx(0x004037C0, "GO_InRemap", SN_NOWARN);
  SetFunctionCmt(0x004037C0, "Adds one input binding (key remap) to the current profile. Params: key1 = primary key code, key2 = secondary key code, action = in-game action id being bound. Use in input/config scripts, repeat once per binding. Returns 1.", 1);
  MakeNameEx(0x00403870, "GO_InMouInv", SN_NOWARN);
  SetFunctionCmt(0x00403870, "Toggles inverted mouse-look for the current profile. Param: invert = 1 invert Y axis, 0 normal. Use in config scripts. Returns 1.", 1);
  MakeNameEx(0x004038E0, "GO_InMouSens", SN_NOWARN);
  SetFunctionCmt(0x004038E0, "Sets mouse sensitivity for the current profile. Param: sensitivity = float multiplier as saved by the options screen. Use in config scripts. Returns 1.", 1);
  MakeNameEx(0x00403950, "GO_GfxDisp", SN_NOWARN);
  SetFunctionCmt(0x00403950, "Sets display-mode selection for the current profile. Param: displayMode = mode index from the retail display list (see Display_GetActiveMode/display table). Use in config scripts. igi.exe registers it with argc=3 at its site; the extra args go unused by the setter itself.", 1);
  MakeNameEx(0x00404010, "GO_GfxDevice", SN_NOWARN);
  SetFunctionCmt(0x00404010, "Sets render-device (D3D device/GUID) selection for the current profile. Param: deviceIndex = index into the render-device list filled by Config_FillRenderDeviceListBox. Use in config scripts. Returns 1.", 1);
  MakeNameEx(0x00404080, "GO_GfxGamma", SN_NOWARN);
  SetFunctionCmt(0x00404080, "Sets gamma for the current profile. Param: gamma = float, retail default 1.0 (range ~0.5-3.0 clamped elsewhere). Use in config scripts. Returns 1.", 1);
  MakeNameEx(0x00403A00, "GO_GameLang", SN_NOWARN);
  SetFunctionCmt(0x00403A00, "Sets game language for the current profile. Param: language = language index (retail ships English=0 and German builds use their own index). Use in config scripts. Returns 1.", 1);
  MakeNameEx(0x00403AC0, "GO_GameDiff", SN_NOWARN);
  SetFunctionCmt(0x00403AC0, "Sets game difficulty for the current profile. Param: difficulty = 0 easy, 1 medium, 2 hard (retail order). Use in config scripts. Returns 1.", 1);
  MakeNameEx(0x00403DF0, "GO_IsBlood", SN_NOWARN);
  SetFunctionCmt(0x00403DF0, "Toggles blood effects for the current profile. Param: blood = 1 on, 0 off. Use in config scripts. Returns 1.", 1);
  MakeNameEx(0x00403E60, "GO_SoundSpeech", SN_NOWARN);
  SetFunctionCmt(0x00403E60, "Sets speech volume for the current profile. Param: volume = float 0.0-1.0. Use in config scripts. Returns 1.", 1);
  MakeNameEx(0x00403EF0, "GO_SoundMusic", SN_NOWARN);
  SetFunctionCmt(0x00403EF0, "Sets music volume for the current profile. Param: volume = float 0.0-1.0. Use in config scripts. Returns 1.", 1);
  MakeNameEx(0x00403F80, "GO_SoundFX", SN_NOWARN);
  SetFunctionCmt(0x00403F80, "Sets sound-effects volume for the current profile. Param: volume = float 0.0-1.0. Use in config scripts. Returns 1.", 1);
  MakeNameEx(0x004040F0, "GO_GfxPerformance", SN_NOWARN);
  SetFunctionCmt(0x004040F0, "Sets graphics performance/detail flags for the current profile. Param: flags = bitmask from the detail-level mapping (see Config_GraphicOptionsGetPerfFlagsFromLevel). Use in config scripts. Returns 1.", 1);
  MakeNameEx(0x00403750, "GO_ActiveMission", SN_NOWARN);
  SetFunctionCmt(0x00403750, "Sets the active (last-played) mission number for the current player profile. Param: mission = mission index 1..14. Use in profile/config scripts after GO_Player. Returns 1.", 1);
  MakeNameEx(0x00403C10, "GO_ContentControlPW", SN_NOWARN);
  SetFunctionCmt(0x00403C10, "Config-writer form (argc=1): sets the content-control password while a config file is parsed. Param: password = string. Returns 1.", 1);
  MakeNameEx(0x00404FA0, "Config_FillPlayerProfileListBox", SN_NOWARN);
  SetFunctionCmt(0x00404FA0, "Fills the current menu list box with all player profiles (name per row, row index = profile index). Use inside the profile-selection list box collect-items script.", 1);
  MakeNameEx(0x00405010, "Config_GetActivePlayerProfileIndex", SN_NOWARN);
  SetFunctionCmt(0x00405010, "RETURNS the index of the currently-active player profile (0-based). Takes no arguments. Use whenever you need which profile is selected, e.g. before Config_DeletePlayerProfile.", 1);
  MakeNameEx(0x00405050, "Config_SetActivePlayerProfileIndex", SN_NOWARN);
  SetFunctionCmt(0x00405050, "Makes 'index' the active player profile. Param: index = 0-based profile index (must exist; see Config_GetNumberOfPlayerProfiles).", 1);
  MakeNameEx(0x004050A0, "Config_CreateNewPlayerProfile", SN_NOWARN);
  SetFunctionCmt(0x004050A0, "Creates a new player profile. Params: name = new profile name (string), sourceIndex = existing profile index to copy initial settings from. RETURNS 1 on success, 0 on failure (e.g. name taken/slots full). Use on the create-profile screen.", 1);
  MakeNameEx(0x00405400, "Config_DeletePlayerProfile", SN_NOWARN);
  SetFunctionCmt(0x00405400, "Deletes a player profile. Param: index = 0-based profile index to delete. RETURNS 1 on success, 0 on failure. Do not delete the last remaining profile; refresh your list box afterwards.", 1);
  MakeNameEx(0x004057D0, "Config_PlayerGetActiveMission", SN_NOWARN);
  SetFunctionCmt(0x004057D0, "Returns the active (reached) mission number of ANY profile. Param: profileIndex = 0-based profile index. Use on the profile/mission screens to show progress without switching profiles.", 1);
  MakeNameEx(0x004054F0, "Config_GetNumberOfPlayerProfiles", SN_NOWARN);
  SetFunctionCmt(0x004054F0, "RETURNS how many player profiles exist. Use to bounds-check indexes and to size profile lists.", 1);
  MakeNameEx(0x00405660, "Config_FillMissionSelectionBox", SN_NOWARN);
  SetFunctionCmt(0x00405660, "Fills the current menu list box with missions selectable for the active profile (respects unlocked progress). Use inside the mission-selection list box collect-items script.", 1);
  MakeNameEx(0x004056F0, "Config_FillMissionPictureBox", SN_NOWARN);
  SetFunctionCmt(0x004056F0, "Fills the current picture box with the selected mission's briefing image. Use inside the mission-picture control's script right after a mission row is chosen.", 1);
  MakeNameEx(0x00405760, "Config_FillMissionTextBox", SN_NOWARN);
  SetFunctionCmt(0x00405760, "Fills the current text box with the selected mission's briefing text. Use inside the mission-briefing text control's script.", 1);
  MakeNameEx(0x00404450, "Config_FillScreenResolutionListBox", SN_NOWARN);
  SetFunctionCmt(0x00404450, "Fills the currently-active menu list box with the screen resolutions available for a device. Param: deviceIndex = render-device index. Use only inside a menu list box 'collect items' script so the items land in that control.", 1);
  MakeNameEx(0x004046A0, "Config_FillRenderDeviceListBox", SN_NOWARN);
  SetFunctionCmt(0x004046A0, "Fills the currently-active menu list box with installed render devices (Direct3D device GUIDs/names). Use inside a list box collect-items script on the video-options screen.", 1);
  MakeNameEx(0x004041D0, "Config_GameOptionsInputGetInvertMouse", SN_NOWARN);
  SetFunctionCmt(0x004041D0, "RETURNS the invert-mouse setting when the engine writes/reads a config game-options block (1 = inverted, 0 = normal). Takes no args. Pairs with Config_GameOptionsInputSetInvertMouse.", 1);
  MakeNameEx(0x00404290, "Config_GameOptionsInputGetMouseSensitivity", SN_NOWARN);
  SetFunctionCmt(0x00404290, "RETURNS the stored mouse-sensitivity integer from the game-options config context. Takes no args.", 1);
  MakeNameEx(0x00404340, "Config_GameOptionsInputGetBloodEnabled", SN_NOWARN);
  SetFunctionCmt(0x00404340, "RETURNS the blood-enabled flag from the game-options config context (1/0). Takes no args.", 1);
  MakeNameEx(0x00404160, "Config_GameOptionsInputSetInvertMouse", SN_NOWARN);
  SetFunctionCmt(0x00404160, "Sets invert-mouse in the GAME-OPTIONS block while a config file is parsed (the GO_* writer side; runtime getter/setter pair lives on the profile). Param: invert = 1 inverted, 0 normal. Use only inside config .qsc write-out contexts.", 1);
  MakeNameEx(0x00404230, "Config_GameOptionsInputSetMouseSensitivity", SN_NOWARN);
  SetFunctionCmt(0x00404230, "Sets mouse-sensitivity in the config game-options write-out context. Param: value = sensitivity as stored by the options screen (integer scale).", 1);
  MakeNameEx(0x004042E0, "Config_GameOptionsInputSetBloodEnabled", SN_NOWARN);
  SetFunctionCmt(0x004042E0, "Sets blood-enabled in the config game-options write-out context. Param: blood = 1 on, 0 off.", 1);
  MakeNameEx(0x00404510, "Config_GraphicOptionsSetResolution", SN_NOWARN);
  SetFunctionCmt(0x00404510, "Applies a screen resolution to the active profile and re-initialises the display. Param: modeIndex = index from Config_FillScreenResolutionListBox entries. Use in the video-options screen script.", 1);
  MakeNameEx(0x00404960, "Config_GraphicOptionsSetTransparency", SN_NOWARN);
  SetFunctionCmt(0x00404960, "Toggles transparency for the active profile. Param: onOff = 1 enable, 0 disable. Video-options screen.", 1);
  MakeNameEx(0x004047F0, "Config_GraphicOptionsSetDevice", SN_NOWARN);
  SetFunctionCmt(0x004047F0, "Applies a render device to the active profile. Param: deviceIndex = index from Config_FillRenderDeviceListBox. Use in video-options screen script.", 1);
  MakeNameEx(0x00404F00, "Config_GraphicOptionsSetPerformanceFlags", SN_NOWARN);
  SetFunctionCmt(0x00404F00, "Sets the raw graphics performance/detail flag bits on the active profile. Param: flags = bitmask (get a valid one from Config_GraphicOptionsGetPerfFlagsFromLevel).", 1);
  MakeNameEx(0x004045B0, "Config_GraphicOptionsGetResolution", SN_NOWARN);
  SetFunctionCmt(0x004045B0, "Returns the active profile's display-mode/resolution index (same index space as Config_GraphicOptionsSetResolution). Use in video-options UI scripts to preselect the current value.", 1);
  MakeNameEx(0x004049C0, "Config_GraphicOptionsGetTransparency", SN_NOWARN);
  SetFunctionCmt(0x004049C0, "Returns 1 if transparency is enabled for the active profile, else 0.", 1);
  MakeNameEx(0x00404710, "Config_GraphicOptionsGetDevice", SN_NOWARN);
  SetFunctionCmt(0x00404710, "Returns the active profile's render-device index (index into the device list). Use in video-options UI scripts.", 1);
  MakeNameEx(0x00404910, "Config_GraphicOptionsGetGamma", SN_NOWARN);
  SetFunctionCmt(0x00404910, "Returns the active profile's gamma as a float. Use to initialise your own gamma slider/UI.", 1);
  MakeNameEx(0x00404F60, "Config_GraphicOptionsGetPerformanceFlags", SN_NOWARN);
  SetFunctionCmt(0x00404F60, "Returns the active profile's graphics performance flag bitmask.", 1);
  MakeNameEx(0x004055C0, "Config_GraphicOptionsGetPerfFlagsFromLevel", SN_NOWARN);
  SetFunctionCmt(0x004055C0, "Converts a detail LEVEL number into its performance-flag bitmask. Param: level = 0..Config_GraphicOptionsNumPerfLevels()-1. Use when the user picks a named detail preset.", 1);
  MakeNameEx(0x00405530, "Config_GraphicOptionsGetPerfLevelFromFlags", SN_NOWARN);
  SetFunctionCmt(0x00405530, "Converts a performance-flag bitmask back into its detail LEVEL number. Param: flags = bitmask from the profile/performance setting. Use to show the current detail level in UI.", 1);
  MakeNameEx(0x00405620, "Config_GraphicOptionsNumPerfLevels", SN_NOWARN);
  SetFunctionCmt(0x00405620, "RETURNS the number of graphics detail levels the engine supports (constant). Use to build the detail-level slider/list.", 1);
  MakeNameEx(0x00404A10, "Config_SoundOptionsSetSoundsEffects", SN_NOWARN);
  SetFunctionCmt(0x00404A10, "Enables/disables sound effects for the active profile. Param: onOff = 1 on, 0 off.", 1);
  MakeNameEx(0x00404AE0, "Config_SoundOptionsSetSoundsEffectsVolume", SN_NOWARN);
  SetFunctionCmt(0x00404AE0, "Sets SFX volume for the active profile. Param: volume = float 0.0-1.0.", 1);
  MakeNameEx(0x00404B90, "Config_SoundOptionsSetMusic", SN_NOWARN);
  SetFunctionCmt(0x00404B90, "Enables/disables music for the active profile. Param: onOff = 1 on, 0 off.", 1);
  MakeNameEx(0x00404C40, "Config_SoundOptionsSetMusicVolume", SN_NOWARN);
  SetFunctionCmt(0x00404C40, "Sets music volume for the active profile. Param: volume = float 0.0-1.0 (pops a float arg - pass a float!).", 1);
  MakeNameEx(0x00404CF0, "Config_SoundOptionsSetSpeech", SN_NOWARN);
  SetFunctionCmt(0x00404CF0, "Enables/disables radio speech for the active profile. Param: onOff = 1 on, 0 off.", 1);
  MakeNameEx(0x00404DA0, "Config_SoundOptionsSetSpeechVolume", SN_NOWARN);
  SetFunctionCmt(0x00404DA0, "Sets speech volume for the active profile. Param: volume = float 0.0-1.0.", 1);
  MakeNameEx(0x00404E50, "Config_SoundOptionsSetReverseStereo", SN_NOWARN);
  SetFunctionCmt(0x00404E50, "Toggles reversed stereo channels for the active profile. Param: onOff = 1 reverse, 0 normal.", 1);
  MakeNameEx(0x00404A90, "Config_SoundOptionsGetSoundsEffects", SN_NOWARN);
  SetFunctionCmt(0x00404A90, "Returns 1 if sound effects are enabled for the active profile, else 0.", 1);
  MakeNameEx(0x00404B40, "Config_SoundOptionsGetSoundsEffectsVolume", SN_NOWARN);
  SetFunctionCmt(0x00404B40, "Returns the active profile's SFX volume (0.0-1.0).", 1);
  MakeNameEx(0x00404BF0, "Config_SoundOptionsGetMusic", SN_NOWARN);
  SetFunctionCmt(0x00404BF0, "Returns 1 if music is enabled for the active profile, else 0.", 1);
  MakeNameEx(0x00404CA0, "Config_SoundOptionsGetMusicVolume", SN_NOWARN);
  SetFunctionCmt(0x00404CA0, "Returns the active profile's music volume (0.0-1.0).", 1);
  MakeNameEx(0x00404D50, "Config_SoundOptionsGetSpeech", SN_NOWARN);
  SetFunctionCmt(0x00404D50, "Returns 1 if speech is enabled for the active profile, else 0.", 1);
  MakeNameEx(0x00404E00, "Config_SoundOptionsGetSpeechVolume", SN_NOWARN);
  SetFunctionCmt(0x00404E00, "Returns the active profile's speech volume (0.0-1.0).", 1);
  MakeNameEx(0x00404EB0, "Config_SoundOptionsGetReverseStereo", SN_NOWARN);
  SetFunctionCmt(0x00404EB0, "Returns 1 if stereo is reversed for the active profile, else 0.", 1);
  MakeNameEx(0x00403C10, "Config_SetContentControlPassword", SN_NOWARN);
  SetFunctionCmt(0x00403C10, "Menu-script setter form (argc=0): same address registered twice by igi.exe - site 0x4034C1 pushes str \"Config_SetContentControlPassword\" -> registrar 0x4B8890. Password comes from the script context, not an explicit arg. Returns 1.", 1);
  MakeNameEx(0x00403C70, "Config_GetContentControlPassword", SN_NOWARN);
  SetFunctionCmt(0x00403C70, "RETURNS the stored content-control (parental lock) password string. Takes no args. Compare against user input or pass to Config_VerifyContentControlPassword.", 1);
  MakeNameEx(0x00403CC0, "Config_VerifyContentControlPassword", SN_NOWARN);
  SetFunctionCmt(0x00403CC0, "Checks a password attempt against the stored content-control password. Param: password = string to test. RETURNS non-zero when correct, 0 when wrong. Use before unlocking violent-content options.", 1);
  MakeNameEx(0x00403D90, "Config_IsContentControlPasswordEnabled", SN_NOWARN);
  SetFunctionCmt(0x00403D90, "RETURNS 1 if a content-control password is SET (parental lock active), else 0. Takes no args. Use to decide whether to ask for the password.", 1);
  MakeNameEx(0x00403B30, "Config_IsGermany", SN_NOWARN);
  SetFunctionCmt(0x00403B30, "RETURNS 1 when running the GERMAN retail build (censored variant), 0 otherwise. Takes no args. German builds gate blood/gore - check before forcing such effects.", 1);
  MakeNameEx(0x00407E30, "DefineQ_Material", SN_NOWARN);
  SetFunctionCmt(0x00407E30, "Defines a Q-material (surface material) entry while a material definition block is parsed. Called BY the engine's own define-block parser - call only from material .qsc definition contexts; arg layout follows the Define block grammar (registration argc unknown).", 1);
  MakeNameEx(0x00407F50, "Define_GameMaterial", SN_NOWARN);
  SetFunctionCmt(0x00407F50, "Defines a GameMaterial entry during a game-material definition block (855-byte parser function). Call only from gamematerial .qsc definition contexts; arg layout follows the Define block grammar (registration argc unknown).", 1);
  MakeNameEx(0x004101C0, "Define_HumanPlayerWeaponCycle", SN_NOWARN);
  SetFunctionCmt(0x004101C0, "Collects the weapon-cycle list for the human player: loops the parsed entries and stores them into the cycle table at 0x56DF1C with count at 0x56DF18 (verified in igi.exe). Call within a humanplayer weapon-cycle definition block; argc unknown (parser context).", 1);
  MakeNameEx(0x00410240, "Define_HumanPlayerWeaponCategory", SN_NOWARN);
  SetFunctionCmt(0x00410240, "Registers one weapon-category entry for the human player during a humanplayer definition block (argc unknown - parser context). Pairs with DefineHumanPlayerWeaponCycle/Cycle ordering.", 1);
  MakeNameEx(0x004102D0, "Define_HumanPlayerAmmoLimit", SN_NOWARN);
  SetFunctionCmt(0x004102D0, "Registers an ammo-limit entry (max carried ammo class) for the human player during a humanplayer definition block (argc unknown - parser context).", 1);
  MakeNameEx(0x004151E0, "MovieSubtitle_RegisterFont", SN_NOWARN);
  SetFunctionCmt(0x004151E0, "Registers a font used by in-game movie subtitles (16 callsites in body; argc unknown - parser context). Call from subtitle/font definition blocks before any MovieSubtitle_RegisterText that uses it.", 1);
  MakeNameEx(0x00415260, "MovieSubtitle_RegisterText", SN_NOWARN);
  SetFunctionCmt(0x00415260, "Registers one subtitle text entry (string + timing) shown over movies/briefings (argc unknown - parser context). Call after the font registration it should use.", 1);
  MakeNameEx(0x00415890, "Game_SetMission", SN_NOWARN);
  SetFunctionCmt(0x00415890, "Selects the mission the game will run/load next. Param: mission = mission index 1..14. Use before Level_Start/level load flow when jumping straight into a mission.", 1);
  MakeNameEx(0x00415950, "Game_SetMusicVolume", SN_NOWARN);
  SetFunctionCmt(0x00415950, "Live-sets music volume through the profile real-value setter (fcn.004B8A50): retail body constructs 1.0f (0x3FF00000) and stores via fstp. Param: volume = float 0.0-1.0. Called by ingamemenu.qvm options sliders.", 1);
  MakeNameEx(0x004159B0, "Game_SetSFXVolume", SN_NOWARN);
  SetFunctionCmt(0x004159B0, "Live-sets sound-effects volume through the profile real-value setter (fcn.004B8A50), same 1.0f construction pattern. Param: volume = float 0.0-1.0. Called by ingamemenu.qvm options sliders.", 1);
  MakeNameEx(0x004174A0, "MenuManager_RequestScreen", SN_NOWARN);
  SetFunctionCmt(0x004174A0, "Requests a menu screen by id through the menu manager (queued request). Params: screenId = retail screen resource id, flags = request modifier (0 = normal). Use outside the menu stack internals when you just want a screen opened next tick.", 1);
  MakeNameEx(0x00417790, "MenuManager_LeaveMenus", SN_NOWARN);
  SetFunctionCmt(0x00417790, "Leaves/closes the whole menu system returning to gameplay. Params: two ints observed in retail calls (pass 0,0). Use to exit from custom menus.", 1);
  MakeNameEx(0x00417810, "MenuManager_SetLanguage", SN_NOWARN);
  SetFunctionCmt(0x00417810, "Switches menu/UI language at runtime. Param: langIndex = language index matching the LANGUAGE\\ folder tables. Call before pushing screens so texts load in the right language.", 1);
  MakeNameEx(0x00417690, "MenuManager_PushScreen", SN_NOWARN);
  SetFunctionCmt(0x00417690, "Pushes a screen onto the menu stack: allocates the screen object (objsize 0x2898) and stores it in the manager's screen stack at mgr+0x27EC (verified in igi.exe). Param: screenId = retail screen id. Remember to MenuManager_PopScreen when done.", 1);
  MakeNameEx(0x00417710, "MenuManager_PopScreen", SN_NOWARN);
  SetFunctionCmt(0x00417710, "Pops the top screen off the menu stack (destroys it) revealing the one beneath. Param: param = pass-through argument observed in retail calls (pass 0). Pair with MenuManager_PushScreen.", 1);
  MakeNameEx(0x00417880, "MenuManager_ForceUpdateWindow", SN_NOWARN);
  SetFunctionCmt(0x00417880, "Forces the menu manager to redraw/update its windows this frame. Param: observed retail value 0. Use after changing control contents from script.", 1);
  MakeNameEx(0x00417900, "MenuManager_ActivatePopupScreen", SN_NOWARN);
  SetFunctionCmt(0x00417900, "Activates a popup screen on top of the current menus (e.g. confirmation dialogs; retail scripts call MenuManager_ActivatePopupScreen(930)). Param: popupId = retail popup screen id. Use for custom confirmations.", 1);
  MakeNameEx(0x00417960, "MenuManager_DeactivatePopuScreen", SN_NOWARN);
  SetFunctionCmt(0x00417960, "Deactivates the currently-active popup screen and returns to the screen beneath. Takes no args. Pair with MenuManager_ActivatePopupScreen. NOTE: name mirrors the retail registration string exactly, including its \"Popu\" typo - do not \"fix\" it against the binary.", 1);
  MakeNameEx(0x004179B0, "MenuManager_SetEnabled", SN_NOWARN);
  SetFunctionCmt(0x004179B0, "Enables/disables menu-manager input processing. Param: enabled = 1 menus react to input, 0 frozen. Use to freeze menus during scripted sequences.", 1);
  MakeNameEx(0x004231E0, "ControlsMenu_ConvertFloatFromOffset", SN_NOWARN);
  SetFunctionCmt(0x004231E0, "Converts a controls-menu slider/storage OFFSET into its float value (0.0-1.0 range used by the control configuration bars). Param: offset = raw integer offset stored for that control binding. Use when reading/writing control bindings from script.", 1);
  MakeNameEx(0x00423240, "ControlsMenu_ConvertOffsetFromFloat", SN_NOWARN);
  SetFunctionCmt(0x00423240, "Inverse of ControlsMenu_ConvertFloatFromOffset: converts a float control value into the raw storage offset. Param: value = float 0.0-1.0. Use when saving a modified binding back.", 1);
  MakeNameEx(0x0044D0E0, "AIAction_Patrol", SN_NOWARN);
  SetFunctionCmt(0x0044D0E0, "Orders the AI into PATROL behaviour. Params: target = patrol goal/node reference from your script, mustBeZero = retail template always passes 0, flags = AIACTIONFLAG enum: NONE=0, PUSHABLE=1 (action may be replaced by higher priority). Use inside AI event handlers e.g. AIEVENT_IDLE branch. Template in igi.exe: AIAction_Patrol(xxxx, 0, AIACTIONFLAG_NONE).", 1);
  MakeNameEx(0x0044D160, "AIAction_Combat", SN_NOWARN);
  SetFunctionCmt(0x0044D160, "Orders the AI into COMBAT behaviour vs its current enemy. Param: param = combat argument from the calling script (retail guard scripts pass their combat target/context value). Use in AIEVENT_COMBAT branches.", 1);
  MakeNameEx(0x0044D260, "AIAction_Dead", SN_NOWARN);
  SetFunctionCmt(0x0044D260, "Runs the DEATH handling action for the AI (plays death, releases tasks). Param: param = death context value passed by retail scripts. Use in AIEVENT_DEAD handler.", 1);
  MakeNameEx(0x0044D2C0, "AIAction_FallFlat", SN_NOWARN);
  SetFunctionCmt(0x0044D2C0, "Knocks the AI flat on the ground (ragdoll-ish fall, e.g. after explosion/surrender). Params: two ints observed in retail calls (pass 0,0 unless mapping specific values). Use for scripted knockdowns.", 1);
  MakeNameEx(0x0044D420, "AIAction_Activate", SN_NOWARN);
  SetFunctionCmt(0x0044D420, "Generic ACTIVATE action: sends the AI to activate/use an object (switch, door, alarm...). Params: target = object/task reference, param2 = secondary value (retail passes 0), flags = AIACTIONFLAG (NONE=0/PUSHABLE=1). Use in AI handlers for alarm/objective responses.", 1);
  MakeNameEx(0x0044D4A0, "AIAction_WalkToNode", SN_NOWARN);
  SetFunctionCmt(0x0044D4A0, "Walks the AI to a nav node. Params: nodeId = graph/node id from the level nav data, flags = AIACTIONFLAG (NONE=0/PUSHABLE=1). Use for calm movement in AI scripts.", 1);
  MakeNameEx(0x0044D510, "AIAction_RunToNode", SN_NOWARN);
  SetFunctionCmt(0x0044D510, "Runs the AI to a nav node (fast). Same params as AIAction_WalkToNode: nodeId = node id, flags = AIACTIONFLAG (NONE=0/PUSHABLE=1).", 1);
  MakeNameEx(0x0044D580, "AIAction_FireAtNode", SN_NOWARN);
  SetFunctionCmt(0x0044D580, "Makes the AI fire AT a nav-node position. Params: nodeId = target node id, remaining 4 args = firing stance/behaviour values observed in retail AI scripts (map before inventing values). Use in combat handlers when target is a position.", 1);
  MakeNameEx(0x0044D630, "AIAction_FireAtTask", SN_NOWARN);
  SetFunctionCmt(0x0044D630, "Makes the AI fire AT a task/object entity. Params: taskId = target task/entity id, remaining 4 args = firing behaviour values (same layout family as FireAtNode). Use in combat handlers when target is an entity.", 1);
  MakeNameEx(0x0044D6E0, "AIAction_PlayAnimation", SN_NOWARN);
  SetFunctionCmt(0x0044D6E0, "Plays an animation on the AI. Params: animationId = animation entry id (see AIFunction_AddAnimationEntry), flags = AIACTIONFLAG (NONE=0/PUSHABLE=1).", 1);
  MakeNameEx(0x0044D750, "AIAction_PlaySound", SN_NOWARN);
  SetFunctionCmt(0x0044D750, "Plays a sound from the AI (voice barks etc.). Params: soundId = sound/event id, param2 = observed 0 in retail, flags = AIACTIONFLAG (NONE=0/PUSHABLE=1).", 1);
  MakeNameEx(0x0044D7D0, "AIAction_MoveToEvent", SN_NOWARN);
  SetFunctionCmt(0x0044D7D0, "Moves the AI toward the source position of an EVENT it received. Params: eventId = AIEVENT_* whose position to move to, flags = AIACTIONFLAG (NONE=0/PUSHABLE=1). Use in event handlers (gunshot heard -> move there).", 1);
  MakeNameEx(0x0044D870, "AIAction_LookAtEvent", SN_NOWARN);
  SetFunctionCmt(0x0044D870, "Turns the AI to LOOK toward an event's source without moving. Params: eventId = AIEVENT_* value, flags = AIACTIONFLAG (NONE=0/PUSHABLE=1).", 1);
  MakeNameEx(0x0044D8F0, "AIAction_Stunned", SN_NOWARN);
  SetFunctionCmt(0x0044D8F0, "Stuns the AI (flashbang/knockout reaction). Params: param1 = stun duration/context value, flags = AIACTIONFLAG (NONE=0/PUSHABLE=1).", 1);
  MakeNameEx(0x0044D960, "AIAction_KickGrenade", SN_NOWARN);
  SetFunctionCmt(0x0044D960, "Kicks a nearby live grenade away (retail soldier behaviour). Param: param = grenade/context reference from the event. Use in grenade-event handlers.", 1);
  MakeNameEx(0x0044DA00, "AIAction_RunPanicking", SN_NOWARN);
  SetFunctionCmt(0x0044DA00, "Sends the AI into PANIC running (civilians under fire). Params: param1 = panic target/context, flags = AIACTIONFLAG (NONE=0/PUSHABLE=1).", 1);
  MakeNameEx(0x0044DA80, "AIAction_Idle", SN_NOWARN);
  SetFunctionCmt(0x0044DA80, "Puts the AI into IDLE (stands, resumes idle animation countdown). Param: idle context value (retail scripts pass their idle value). Use in AIEVENT_IDLE handler instead of Patrol for stationary guards.", 1);
  MakeNameEx(0x0044DAE0, "AIAction_SetCombat", SN_NOWARN);
  SetFunctionCmt(0x0044DAE0, "Force-sets the AI's COMBAT ENEMY/target. Param: enemyId = enemy entity/id to engage. Use to make an AI attack a specific target regardless of detection.", 1);
  MakeNameEx(0x0044E060, "AIFunction_DefaultHandler", SN_NOWARN);
  SetFunctionCmt(0x0044E060, "The default AI event handler: call this for any AIEVENT_* your script does not handle explicitly (retail template shows it as the else-branch body). Takes no args. Put inside every event if-else chain as fallback.", 1);
  MakeNameEx(0x0044DBC0, "AIFunction_RemoveAlarmActions", SN_NOWARN);
  SetFunctionCmt(0x0044DBC0, "Removes all queued ALARM-related actions from this AI (calms it down). Takes no args. Use to de-escalate an NPC you control.", 1);
  MakeNameEx(0x0044DC40, "AIFunction_SetViewLength", SN_NOWARN);
  SetFunctionCmt(0x0044DC40, "Sets this AI's VIEW LENGTH - how far it can see. Param: length = view distance in engine units. Use in AI init (AIEVENT_CREATE) to buff/nerf vision.", 1);
  MakeNameEx(0x0044DCD0, "AIFunction_SetAlarmViewLength", SN_NOWARN);
  SetFunctionCmt(0x0044DCD0, "Sets view length WHILE AN ALARM IS ON (separate stat from normal vision). Param: length = distance in engine units. Use in AI init.", 1);
  MakeNameEx(0x0044DD30, "AIFunction_SetViewAlpha", SN_NOWARN);
  SetFunctionCmt(0x0044DD30, "Sets view ALPHA - the detection speed/gain of normal vision. Param: alpha = engine detection factor. Higher = spots player faster. Use in AIEVENT_CREATE.", 1);
  MakeNameEx(0x0044DD90, "AIFunction_SetViewGamma", SN_NOWARN);
  SetFunctionCmt(0x0044DD90, "Sets view GAMMA - secondary vision shaping factor for detection. Param: gamma = engine factor. Use in AI init alongside SetViewAlpha.", 1);
  MakeNameEx(0x0044DDF0, "AIFunction_SetSecondaryViewLength", SN_NOWARN);
  SetFunctionCmt(0x0044DDF0, "Sets SECONDARY view length (peripheral/short-range channel). Param: length = distance in engine units.", 1);
  MakeNameEx(0x0044DE80, "AIFunction_SetSecondaryAlarmViewLength", SN_NOWARN);
  SetFunctionCmt(0x0044DE80, "Sets secondary view length during alarms. Param: length = distance in engine units.", 1);
  MakeNameEx(0x0044DEE0, "AIFunction_SetSecondaryViewAlpha", SN_NOWARN);
  SetFunctionCmt(0x0044DEE0, "Sets secondary-view detection gain. Param: alpha = engine factor.", 1);
  MakeNameEx(0x0044DF40, "AIFunction_SetSecondaryViewGamma", SN_NOWARN);
  SetFunctionCmt(0x0044DF40, "Sets secondary-view gamma shaping factor. Param: gamma = engine factor.", 1);
  MakeNameEx(0x0044E0C0, "AIFunction_SetEventPriority", SN_NOWARN);
  SetFunctionCmt(0x0044E0C0, "Sets the priority of the CURRENT event being handled (decides which queued event wins). Param: priority = engine priority number. Use inside an event handler.", 1);
  MakeNameEx(0x0044E150, "AIFunction_SetInvulnerability", SN_NOWARN);
  SetFunctionCmt(0x0044E150, "Makes this AI invulnerable. Param: onOff = 1 immune to damage, 0 normal. Great for boss/scripted NPCs. Use in AIEVENT_CREATE or anytime.", 1);
  MakeNameEx(0x0044E1B0, "AIFunction_SetInstantDeath", SN_NOWARN);
  SetFunctionCmt(0x0044E1B0, "When on, any hit instantly kills this AI (no damage pooling). Param: onOff = 1 one-shot kills, 0 normal health. Use for scripted one-shot enemies.", 1);
  MakeNameEx(0x0044E210, "AIFunction_SetDeathAnimation", SN_NOWARN);
  SetFunctionCmt(0x0044E210, "Overrides the death animation played when this AI dies. Param: animId = animation entry id. Use in AI init for custom deaths.", 1);
  MakeNameEx(0x0044E270, "AIFunction_SetAlarmTriggerID", SN_NOWARN);
  SetFunctionCmt(0x0044E270, "Binds an ALARM trigger object to this AI (which alarm switch it responds to/runs to). Param: id = alarm trigger id from the level. Retail template: AIFunction_SetAlarmTriggerID(xx).", 1);
  MakeNameEx(0x0044E2D0, "AIFunction_SetAlarmControlID", SN_NOWARN);
  SetFunctionCmt(0x0044E2D0, "Binds the ALARM CONTROL (the raised-alarm device) this AI uses. Param: id = alarm control id from the level. Retail template: AIFunction_SetAlarmControlID(xx).", 1);
  MakeNameEx(0x0044E330, "AIFunction_SetAlarmAccess", SN_NOWARN);
  SetFunctionCmt(0x0044E330, "Sets HOW the AI treats the alarm route. Param: access = AIALARMACCESS enum: BEFORECOMBAT=0 (run for the alarm first), AFTERCOMBAT=1 (fight first, raise alarm after). Retail template: AIFunction_SetAlarmAccess(AIALARMACCESS_BEFORECOMBAT).", 1);
  MakeNameEx(0x0044E390, "AIFunction_SetGunnerID", SN_NOWARN);
  SetFunctionCmt(0x0044E390, "Assigns which mounted-gunner slot this AI mans. Param: gunnerId = gunner position id. Use in AI init for turret/mounted-gun NPCs.", 1);
  MakeNameEx(0x0044E6D0, "AIFunction_SetScriptIntegerValue", SN_NOWARN);
  SetFunctionCmt(0x0044E6D0, "Writes an AI-script integer variable. Params: varId = script variable index, value = new integer. Use for custom AI state communication between scripts.", 1);
  MakeNameEx(0x0044E790, "AIFunction_SetScriptRealValue", SN_NOWARN);
  SetFunctionCmt(0x0044E790, "Writes an AI-script real (float) variable. Params: varId = script variable index, value = float. Pairs with AIFunction_GetScriptRealValue.", 1);
  MakeNameEx(0x0044EAF0, "AIFunction_SetAnimationInterval", SN_NOWARN);
  SetFunctionCmt(0x0044EAF0, "Sets playback INTERVAL for an animation entry. Params: entryIndex = animation entry added via AddAnimationEntry, interval = frame/tick interval. Use when tuning scripted animations.", 1);
  MakeNameEx(0x0044EBB0, "AIFunction_AddAnimationEntry", SN_NOWARN);
  SetFunctionCmt(0x0044EBB0, "Adds an animation ENTRY to this AI's available set (builds the pick-list GetAnimationToPlay draws from). Params: animationId = animation resource id, data = entry config value. Use in AIEVENT_CREATE before playing custom animations.", 1);
  MakeNameEx(0x0044EE40, "AIFunction_SendResponse", SN_NOWARN);
  SetFunctionCmt(0x0044EE40, "Sends the AI's RESPONSE to the current event (used for ALERT_RESPONSE chains so buddy AIs react too). Takes no args. Call inside alert handlers.", 1);
  MakeNameEx(0x0047CAD0, "Define_AmmoType", SN_NOWARN);
  SetFunctionCmt(0x0047CAD0, "Defines an AMMO TYPE inside an ammo definition block of a .qsc/.cfg script (515-byte parser body; igi.exe embeds str 'DefineAmmoType'). Args follow the Define-ammo grammar (name, damage, range, clip...) - not fully mapped, treat as parser-internal. Do NOT call outside its define block.", 1);
  MakeNameEx(0x00484F60, "Define_Mission", SN_NOWARN);
  SetFunctionCmt(0x00484F60, "Defines a MISSION entry during mission-list parsing (480-byte parser). Called by the engine's mission definition grammar; do NOT call from gameplay scripts.", 1);
  MakeNameEx(0x00488E00, "LevelFlow_GetBreakCutSceneKey", SN_NOWARN);
  SetFunctionCmt(0x00488E00, "RETURNS the key code currently bound to 'skip/break cutscene'. Takes no args. Use in cutscene player loops to detect the skip key press.", 1);
  MakeNameEx(0x00488E50, "LevelFlow_LevelFailed", SN_NOWARN);
  SetFunctionCmt(0x00488E50, "Signals that the level FAILED - triggers the retail failure flow (fail sound, restart/quit menu). Takes no args. Call when your scripted objective fails.", 1);
  MakeNameEx(0x00488E90, "LevelFlow_IsCountryUSA", SN_NOWARN);
  SetFunctionCmt(0x00488E90, "RETURNS 1 if the running build is a USA country build, 0 otherwise (affects censorship/content paths like blood). Takes no args. Check before enabling content that country builds gate.", 1);
  MakeNameEx(0x004B8C60, "Script_SetWarningLevel", SN_NOWARN);
  SetFunctionCmt(0x004B8C60, "Sets how loudly the script system reports warnings while parsing/running (igi.exe embeds its name WITH leading underscore: '_Script_SetWarningLevel'). Param: level = warning verbosity threshold. Use at the top of scripts you want silenced or extra-chatty.", 1);
  MakeNameEx(0x004B8C10, "Break_Script", SN_NOWARN);
  SetFunctionCmt(0x004B8C10, "Breaks/aborts the currently-executing script at this point (70-byte function). Takes no args. Use as an early-exit inside .qsc scripts.", 1);
  MakeNameEx(0x004C4520, "Define_MagicObj", SN_NOWARN);
  SetFunctionCmt(0x004C4520, "Defines a MAGIC OBJECT type during magicobj definition parsing (pairs with the MAGICOBJ\\ folder data). Parser-context only.", 1);
  MakeNameEx(0x004C6760, "Create_TerrainTileMap", SN_NOWARN);
  SetFunctionCmt(0x004C6760, "Creates the TERRAIN TILE MAP for a level during level load (113-byte function). Engine-internal: called by the terrain loader, not meant for gameplay scripts.", 1);
  MakeNameEx(0x004EBA90, "Define_Group", SN_NOWARN);
  SetFunctionCmt(0x004EBA90, "Defines a GROUP entry (sound-group/entity grouping) during definition parsing. Parser-context only.", 1);
  MakeNameEx(0x004E8C60, "Define_Sound", SN_NOWARN);
  SetFunctionCmt(0x004E8C60, "Defines a SOUND entry (file + attenuation params) inside sound definition blocks - OpenIGI reimplements it as SoundDefinitionRegistry.Define(SoundDefinitionKind.Sound). Call only from sound .qsc define blocks.", 1);
  MakeNameEx(0x004EAD20, "Define_Graph", SN_NOWARN);
  SetFunctionCmt(0x004EAD20, "Defines a GRAPH (sound/graph transition graph) entry inside definition blocks - OpenIGI maps it to SoundDefinitionKind.Graph. Parser-context only.", 1);
  MakeNameEx(0x004E9EC0, "Define_TriggerOnce", SN_NOWARN);
  SetFunctionCmt(0x004E9EC0, "Defines a fire-once TRIGGER entry inside definition blocks - OpenIGI maps it to SoundDefinitionKind.TriggerOnce. Parser-context only.", 1);
  MakeNameEx(0x004F0780, "Task_New", SN_NOWARN);
  SetFunctionCmt(0x004F0780, "Instantiates a new game task from a declared type (731-byte factory; OpenIGI registers Task_New reading the type name then declared params). Call inside task blocks after Task_DeclareParameters; argc unknown (parser context).", 1);
  MakeNameEx(0x004F0740, "Task_DeclareParameters", SN_NOWARN);
  SetFunctionCmt(0x004F0740, "Declares the parameter list of the task currently being defined inside a .qsc task block (OpenIGI TaskScriptCommands implements it reading a type name + parameter names). Call as FIRST statement of a task definition; argc unknown (parser context).", 1);
  MakeNameEx(0x0044E3F0, "AIFunction_GetAlarmTriggerID", SN_NOWARN);
  SetFunctionCmt(0x0044E3F0, "RETURNS the id of the alarm trigger bound to this AI (see AIFunction_SetAlarmTriggerID). Takes no args. Use in handlers to check which alarm applies.", 1);
  MakeNameEx(0x0044E430, "AIFunction_GetAlarmControlID", SN_NOWARN);
  SetFunctionCmt(0x0044E430, "RETURNS the bound alarm-control id. Takes no args.", 1);
  MakeNameEx(0x0044E470, "AIFunction_GetAlarmAccess", SN_NOWARN);
  SetFunctionCmt(0x0044E470, "RETURNS the current AIALARMACCESS mode: BEFORECOMBAT=0, AFTERCOMBAT=1. Takes no args.", 1);
  MakeNameEx(0x0044E4B0, "AIFunction_GetGunnerID", SN_NOWARN);
  SetFunctionCmt(0x0044E4B0, "RETURNS this AI's assigned gunner slot id. Takes no args.", 1);
  MakeNameEx(0x0044E4F0, "AIFunction_GetAlarmControlStatus", SN_NOWARN);
  SetFunctionCmt(0x0044E4F0, "RETURNS the status/state of the bound alarm control (raised/used state as tracked by the engine). Takes no args.", 1);
  MakeNameEx(0x0044E5E0, "AIFunction_GetGunnerStatus", SN_NOWARN);
  SetFunctionCmt(0x0044E5E0, "RETURNS the status of this AI's gunner post (manned/state value). Takes no args.", 1);
  MakeNameEx(0x0044E740, "AIFunction_GetScriptIntegerValue", SN_NOWARN);
  SetFunctionCmt(0x0044E740, "READS an AI-script integer variable written by AIFunction_SetScriptIntegerValue. Param: varId = variable index. RETURNS the integer.", 1);
  MakeNameEx(0x0044DFA0, "AIFunction_GetCurrentEventType", SN_NOWARN);
  SetFunctionCmt(0x0044DFA0, "RETURNS the AIEVENT_* value currently being handled - the backbone of every AI script's if/else chain. Enum: CREATE=0, DELETE=1, DEAD=2, ANIMATION=3, IDLE=4, ALERT=5, ALERT_RESPONSE=6, COMBAT=7, ALARMON=8, ALARMOFF=9, WALK=10, GROUNDIMPACT=11, DOOR=12, FENCE=13, LADDER=14, TAKINGDAMAGE=15, GUNSHOT=16, GRENADETHROWN=17, GRENADELAND=18, FLASHBANG=19, GUNSHOTMISS=20, EXPLOSION=21, ENEMYDETECTION=22, FRIENDLYDETECTION=23. Takes no args.", 1);
  MakeNameEx(0x0044E860, "AIFunction_IsEventBehind", SN_NOWARN);
  SetFunctionCmt(0x0044E860, "RETURNS non-zero if the current event came from BEHIND the AI (direction test used for reaction animations). Takes no script args per retail table (engine reads an internal slot via ebp+8). Use in alert/detection handlers.", 1);
  MakeNameEx(0x0044ECB0, "AIFunction_GetAnimationToPlay", SN_NOWARN);
  SetFunctionCmt(0x0044ECB0, "RETURNS which animation entry the engine decided to play for the current event/action (useful to log or override reactions). Per retail table takes no script args; machine code also touches an [ebp+8] slot (internal context).", 1);
  MakeNameEx(0x004048B0, "Config_GraphicOptionsSetGamma", SN_NOWARN);
  SetFunctionCmt(0x004048B0, "Sets and immediately applies gamma to the active profile (also feeds the live lighting math through the profile record +0x220). Param: gamma = float (retail default 1.0). Use in video-options screen script or your own gamma slider.", 1);
  MakeNameEx(0x0044E800, "AIFunction_GetScriptRealValue", SN_NOWARN);
  SetFunctionCmt(0x0044E800, "READS an AI-script real (float) variable. Param: varId = variable index. RETURNS the float.", 1);
  MakeNameEx(0x0044E000, "AIFunction_GetRandomValue", SN_NOWARN);
  SetFunctionCmt(0x0044E000, "RETURNS a random value below 'max' (returns Real per retail table). Param: max = upper bound. Use for randomized behaviour delays/targets in AI scripts.", 1);
  MakeNameEx(0x0044E930, "AIFunction_GetEventDistance", SN_NOWARN);
  SetFunctionCmt(0x0044E930, "RETURNS the DISTANCE to the source of the current event (Real). Takes no args. Use inside event handlers e.g. 'if gunshot closer than X then investigate'.", 1);
  MakeNameEx(0x0044E9B0, "AIFunction_GetAlarmTriggerDistance", SN_NOWARN);
  SetFunctionCmt(0x0044E9B0, "RETURNS the distance between this AI and its bound ALARM TRIGGER (Real). Takes no args. Use to decide running vs fighting for the alarm.", 1);
  MakeNameEx(0x0048F1A0, "App_ContextSetDebugged", SN_NOWARN);
  SetFunctionCmt(0x0048F1A0, "Sets the app-level DEBUGGED flag (global 0x5C8BF8). Param: state = 1 mark debugger attached/debug mode, 0 clear. BlankName's IGIPatch calls this by name. Use to toggle engine debug paths.", 1);
  MakeNameEx(0x0048F1E0, "App_ContextSetDebugtextState", SN_NOWARN);
  SetFunctionCmt(0x0048F1E0, "Toggles on-screen DEBUG TEXT output (global 0x5C8BF4). Param: state = 1 show engine debug text, 0 hide. Handy while reverse-engineering other systems.", 1);
  MakeNameEx(0x0048F240, "App_ContextSetLightmapsUsed", SN_NOWARN);
  SetFunctionCmt(0x0048F240, "Enables/disables OBJECT lightmaps globally (global 0x5C8BE4) - the verified retail lightmap setter. Param: used = 1 use object lightmaps, 0 flat-lit. Use for graphics enhancers (this is what IGIPatch's lightmap toggles call).", 1);
  MakeNameEx(0x0048F260, "App_ContextSetTerrainLightmapsUsed", SN_NOWARN);
  SetFunctionCmt(0x0048F260, "Enables/disables TERRAIN lightmaps globally (global 0x5C8BE8). Param: used = 1 lit terrain, 0 unlit. Pair with AppContext_SetLightmapsUsed for full lighting control.", 1);
  MakeNameEx(0x00404590, "Config_GetActiveGraphicOptions", SN_NOWARN);
  SetFunctionCmt(0x00404590, "Returns a pointer to the ACTIVE PROFILE's graphic-options record inside the global config array. The record base is 0xBC2394 + 0xD14 * activeProfileIndex (verified in igi.exe). Useful for reading/writing raw graphic fields directly (gamma sits at record+0x220).", 1);
  MakeNameEx(0x00491CF0, "Display_GetActiveMode", SN_NOWARN);
  SetFunctionCmt(0x00491CF0, "RETURNS pointer to the ACTIVE display-mode struct (global 0xC28B40): width/height/depth fields live at +0x4/+0x8/+0x10 per Display_SetMode comparisons. Takes no args. Read current resolution from here.", 1);
  MakeNameEx(0x00491E70, "Display_SetBackgroundColourFn", SN_NOWARN);
  SetFunctionCmt(0x00491E70, "Sets the 3D-view BACKGROUND COLOUR (clear colour) - masks each arg to a byte into globals 0xBCADF0/R,G,B. Params: r,g,b = 0-255 colour channels. Use for custom sky/clear colour effects.", 1);
  MakeNameEx(0x00491A90, "Display_SetMode", SN_NOWARN);
  SetFunctionCmt(0x00491A90, "Switches the DISPLAY MODE at runtime: validates mode fields vs current (0xC28B44...), repositions/resizes the window (GetSystemMetrics), copies the mode into the active-mode struct. Param: modeStruct = pointer to a display-mode struct (same layout Display_GetActiveMode returns). RETURNS 0 on failure, non-zero on success.", 1);
  MakeNameEx(0x004B6E80, "Picture_GetHeight", SN_NOWARN);
  SetFunctionCmt(0x004B6E80, "RETURNS the HEIGHT in pixels of a loaded picture/surface. Param: picture = picture pointer. Thin thunk to fcn.004B7E00.", 1);
  MakeNameEx(0x004B6E70, "Picture_GetWidth", SN_NOWARN);
  SetFunctionCmt(0x004B6E70, "RETURNS the WIDTH in pixels of a loaded picture/surface. Param: picture = pointer from a picture-load call. Thin thunk to fcn.004B7DF0 (byte-verified).", 1);
  MakeNameEx(0x004B53B0, "Qsprite_Register4Az", SN_NOWARN);
  SetFunctionCmt(0x004B53B0, "Registers a QUAD-SPRITE with full transform data: 14 args, float parameters scaled by constant 0x534AB0, writes sprite tables 0xA84A50/0xA84A58 (verified). Low-level renderer API - map arg layout from callers before use.", 1);
  MakeNameEx(0x00497E70, "Transcontext_SetActiveTransContext", SN_NOWARN);
  SetFunctionCmt(0x00497E70, "Installs a TRANSFORM CONTEXT as active: copies 0x2A dwords from ctx into global 0xBCAAE0 and bumps state counters at 0x6E5BB0/B4. Param: ctx = transform-context struct (IGIPatch uses this around custom rendering). Use when injecting your own render passes.", 1);
  MakeNameEx(0x004B0D40, "QHash_ValueSet", SN_NOWARN);
  SetFunctionCmt(0x004B0D40, "Sets a value in a QHash hash-table (8-byte thunk into the hash engine at 0x4B0D90 family). Pass the table ptr, key string and integer value. Restored after accidental loss during batch rewrite - address pass1-verified.", 1);
  MakeNameEx(0x004B0DB0, "QHash_ValueGet", SN_NOWARN);
  SetFunctionCmt(0x004B0DB0, "Gets a value from a QHash hash-table (6-byte getter thunk). Pass table ptr + key string, RETURNS the stored integer. Restored after accidental loss - address pass1-verified.", 1);
  MakeNameEx(0x00415020, "DEBUG_KEYSENABLEINVALID", SN_NOWARN);
  SetFunctionCmt(0x00415020, "TOMBSTONE - DO NOT INVOKE. The retail debug-keys native address is UNKNOWN. The old value 0x0041502 lies outside .text (0x401000-0x532510) and would crash on invoke; no verified replacement found in igi.exe (unknown > fabricated per RE.md). This entry exists only so JSON consumers see the warning instead of silently missing the key.", 1);
  MakeNameEx(0x004B1AC0, "QScript_Cleanup", SN_NOWARN);
  SetFunctionCmt(0x004B1AC0, "Cleans up/frees a parsed .qsc script structure (pass1: 5 calls, valid exit). Param: script = pointer to the loaded script object. Call when done with a script loaded via the Qvm/Qsc loaders to release its memory.", 1);
  MakeNameEx(0x004828D0, "Human_FindNextCamera", SN_NOWARN);
  SetFunctionCmt(0x004828D0, "Debug camera cycler: advances to the next camera/view target attached to the human player (decompiled body polls input keys). Param: human = human-player pointer. Pass1-verified function start; restored - it existed only in the Natives.hpp enum and was never serialized to JSON.", 1);
  MakeNameEx(0x004F4B00, "CutScene_TaskCreate", SN_NOWARN);
  SetFunctionCmt(0x004F4B00, "CREATES the CutScene task during level load: allocates 632-byte \"CutScene\" object via class factory 0x401900, attaches vtable 0x4F4EE0 + update cb 0x4F51D0, registers TASKTYPE_CUTSCENE (@0x4F4EB8). TO DELETE CUTSCENES: early-return from this function so no CutScene task is ever instantiated - flow continues without them. Verified: prologue sub esp,0x278; string refs \"1721_01_1\",\"CutScene\"; corroborated by IGI-MP plugin.", 1);
  MakeNameEx(0x004F51D0, "CutScene_TaskUpdate", SN_NOWARN);
  SetFunctionCmt(0x004F51D0, "Per-frame UPDATE of the running CutScene task. Alternative cutscene-kill point: force an immediate completion return here and any created cutscene ends on frame one. Verified: referenced as update cb inside CutScene_TaskCreate 0x4F4B00.", 1);
  MakeNameEx(0x004109A0, "Human_RunUpdate", SN_NOWARN);
  SetFunctionCmt(0x004109A0, "Main HUMAN PLAYER RUN/MOVEMENT UPDATE - large handler; reads human struct field +0x2EC (lea edi,[esi+0x2ec], matching the documented param-ptr slot) and drives movement state. Hooked by IGI-MP as HumanPlayer_RunUpdate.", 1);
  MakeNameEx(0x00412440, "Human_DamageApply", SN_NOWARN);
  SetFunctionCmt(0x00412440, "Applies DAMAGE/knockback to the human player: reads enable flag byte +0xCF6 and patrol sub-struct +0x254 of the human struct. IGI-MP disables bullet knockback here. Prologue-verified.", 1);
  MakeNameEx(0x00478900, "Weapon_FireUpdate", SN_NOWARN);
  SetFunctionCmt(0x00478900, "Weapon FIRE update - processes firing state using config byte 0x5407B9 and weapon-table entry ([ctx+0x14] -> +0x1C). IGI-MP hooks this as gunhook.", 1);
  MakeNameEx(0x004779E0, "Weapon_FlameUpdate", SN_NOWARN);
  SetFunctionCmt(0x004779E0, "FLAME-weapon effect update: resolves effect object via [ctx+0x14]+0x20 then updates through 0x477C10. IGI-MP hooks this as flamehook.", 1);
  MakeNameEx(0x00479990, "Weapon_ReloadStart", SN_NOWARN);
  SetFunctionCmt(0x00479990, "Starts weapon RELOAD: uses soldier object ref +0x4C4 with spawner 0x4F2060 (arg 0x4C3). IGI-MP hooks this as reloadhook.", 1);
  MakeNameEx(0x00477040, "Throwable_Create", SN_NOWARN);
  SetFunctionCmt(0x00477040, "Creates a GRENADE/THROWABLE projectile: checks+registers it in the hash table via QHash_ValueGet(0x4B0DB0)/QHash_ValueSet(0x4B0D40). IGI-MP hooks for network throwable sync.", 1);
  MakeNameEx(0x00476040, "Mine_ProximityCreate", SN_NOWARN);
  SetFunctionCmt(0x00476040, "Creates a PROXIMITY MINE entity: initializes hash state via QHash_Init(0x4B0D60), reads mine id word 0x5BE3A0. IGI-MP hooks for network mine sync.", 1);
  MakeNameEx(0x004D9870, "Camera_SubmitFrame", SN_NOWARN);
  SetFunctionCmt(0x004D9870, "Submits/presents the camera frame: increments frame counters at camCtx+0x50 against limit at +0x4C. IGI-MP hooks this as Camera_Submit for the lobby camera.", 1);
  MakeNameEx(0x00402870, "Frames_Get", SN_NOWARN);
  SetFunctionCmt(0x00402870, "Returns the configured game frame limit from the global context field +0x3C written by Frames_Set. Menu_Manager stores this value as its frame-rate limit.", 1);
  MakeNameEx(0x00402880, "Game_GetContext", SN_NOWARN);
  SetFunctionCmt(0x00402880, "Returns the global IGI game-context pointer at DAT_00567C8C. Retail callers use it to dispatch context callbacks and initialize the main game state.", 1);
  MakeNameEx(0x00402890, "Game_GetScriptContext", SN_NOWARN);
  SetFunctionCmt(0x00402890, "Returns *(void**)(Game_GetContext()+0x20), the script/task context initialized during game setup. Level_Start passes it through the script-data wrapper; the main-menu path pushes its return value as Menu_Manager's first argument.", 1);
  MakeNameEx(0x004028A0, "Flow_SetState", SN_NOWARN);
  SetFunctionCmt(0x004028A0, "Stores a pending flow state in game-context field +0x2C. The main loop consumes it, copies it to +0x28, clears the pending field, and dispatches state IDs 1 through 8. Flow_RequestEvent reaches this setter after converting its event ID.", 1);
  MakeNameEx(0x004028B0, "Frames_GetUpdateCounter", SN_NOWARN);
  SetFunctionCmt(0x004028B0, "Returns the update-loop counter at game-context field +0x34. Frames_Set resets it and the retail main loop increments it once per simulation/update pass; gameplay timeout code compares against this value.", 1);
  MakeNameEx(0x004028C0, "Frames_GetTaskCounter", SN_NOWARN);
  SetFunctionCmt(0x004028C0, "Returns the second task/processing counter at game-context field +0x38. Frames_Set resets it and the retail main loop increments it during the second processing pass.", 1);
  MakeNameEx(0x004028D0, "Game_TimingBegin", SN_NOWARN);
  SetFunctionCmt(0x004028D0, "Begins a nested timing interval: starts the retail timer when the timing depth is zero, then increments the depth counter. Level_Start and Game_Restart bracket their load work with this helper and Game_TimingEnd.", 1);
  MakeNameEx(0x004028F0, "Game_TimingEnd", SN_NOWARN);
  SetFunctionCmt(0x004028F0, "Ends a nested timing interval: decrements the depth counter and, at zero, adds elapsed timer ticks to game-context field +0x50 and clears the interval start timestamp.", 1);
  MakeNameEx(0x00401900, "TaskType_Register", SN_NOWARN);
  SetFunctionCmt(0x00401900, "Registers and allocates a task type, copies the task handler table, and returns the allocated 16-bit type id. Ghidra/r2 CFG agreement: 18 basic blocks and 23 edges; see verification/natives_discovery_2026-08-26.json.", 1);
  MakeNameEx(0x00401CF0, "TaskType_IsDerivedFrom", SN_NOWARN);
  SetFunctionCmt(0x00401CF0, "Checks equality and walks the task-type parent chain until the sentinel type. Ghidra/r2 CFG agreement: 5 basic blocks and 6 edges; see verification/natives_discovery_2026-08-26.json.", 1);
  MakeNameEx(0x00477C50, "Weapon_EntityCreate", SN_NOWARN);
  SetFunctionCmt(0x00477C50, "Validates the weapon type, allocates/configures the weapon entity, initializes object fields, and dispatches the type handler. Ghidra/r2 CFG agreement: 6 basic blocks and 7 edges; see verification/natives_discovery_2026-08-26.json.", 1);
  MakeNameEx(0x00477C10, "Weapon_FiringStateGet", SN_NOWARN);
  SetFunctionCmt(0x00477C10, "Returns the byte at the retail weapon firing-state configuration global 0x005407B9. Ghidra/r2 CFG agreement: 1 basic block and 0 edges; see verification/natives_discovery_2026-08-26.json.", 1);
  MakeNameEx(0x004E7200, "Sound_EventTrigger", SN_NOWARN);
  SetFunctionCmt(0x004E7200, "Dispatches a named sound/event through active object handlers and queues the resulting event. Ghidra/r2 CFG agreement: 15 basic blocks and 24 edges; see verification/natives_discovery_2026-08-26.json.", 1);
  MakeNameEx(0x004A5702, "String_VFormat", SN_NOWARN);
  SetFunctionCmt(0x004A5702, "Bounded printf-style va_list formatter wrapper around the parser core at 0x004A7720. Catalogued for direct ABI-aware use; no generic NativeHelper wrapper is emitted. Ghidra/r2 CFG agreement: 4 basic blocks and 4 edges; see verification/natives_discovery_2026-08-26.json.", 1);
  MakeNameEx(0x004B1020, "QFile_AliasResolve", SN_NOWARN);
  SetFunctionCmt(0x004B1020, "Resolves semicolon-separated QFile path aliases, copies the resolved path, and returns the alias depth. Ghidra/r2 CFG agreement: 17 basic blocks and 25 edges; see verification/natives_discovery_2026-08-26.json.", 1);
  MakeNameEx(0x004B11A0, "QFile_DeviceIndex", SN_NOWARN);
  SetFunctionCmt(0x004B11A0, "Scans the retail QFile device table and returns its 1-based matching device index, or zero. Ghidra/r2 CFG agreement: 6 basic blocks and 7 edges; see verification/natives_discovery_2026-08-26.json.", 1);
  MakeNameEx(0x004B1620, "QFile_DeviceHandlerLookup", SN_NOWARN);
  SetFunctionCmt(0x004B1620, "Matches a device name against the retail handler-name table and returns the corresponding handler value. Ghidra/r2 CFG agreement: 13 basic blocks and 18 edges; see verification/natives_discovery_2026-08-26.json.", 1);
  MakeNameEx(0x004B8A50, "Profile_ValueSet", SN_NOWARN);
  SetFunctionCmt(0x004B8A50, "Sets a profile value through the profile object/value-table path used by the retail music and sound-effects option setters. Ghidra/r2 CFG agreement: 3 basic blocks and 2 edges; see verification/natives_discovery_2026-08-26.json.", 1);
  SetBatch(0);
}
