#include <idc.idc>

static main(void) {
	Message("Applying IGI1 verified native symbols...\n");
	MakeName(0x00401B20, "QtaskUpdateList");
	SetFunctionCmt(0x00401B20, "Update all QTask list, Params: p1 ??", 1);
	MakeName(0x00402780, "Flow_RequestEvent");
	SetFunctionCmt(0x00402780, "Requests a flow-task event by id (drives the level's flow state machine). Param: eventId = flow event number used in the level flow script. Use from mission flow scripts to trigger", 1);
	MakeName(0x00402820, "FramesSet");
	SetFunctionCmt(0x00402820, "Set game frames, Params: 30,60 max 240FPS.", 1);
	MakeName(0x004036B0, "GOPlayer");
	SetFunctionCmt(0x004036B0, "Adds a player profile named 'name' to the config while a .cfg/GO script block is being read; subsequent GO_* settings apply to this profile. Param: name = profile display name (str", 1);
	MakeName(0x00403750, "GOActiveMission");
	SetFunctionCmt(0x00403750, "Sets the active (last-played) mission number for the current player profile. Param: mission = mission index 1..14. Use in profile/config scripts after GO_Player. Returns 1.", 1);
	MakeName(0x004037C0, "GOInRemap");
	SetFunctionCmt(0x004037C0, "Adds one input binding (key remap) to the current profile. Params: key1 = primary key code, key2 = secondary key code, action = in-game action id being bound. Use in input/config s", 1);
	MakeName(0x00403870, "GOInMouInv");
	SetFunctionCmt(0x00403870, "Toggles inverted mouse-look for the current profile. Param: invert = 1 invert Y axis, 0 normal. Use in config scripts. Returns 1.", 1);
	MakeName(0x004038E0, "GOInMouSens");
	SetFunctionCmt(0x004038E0, "Sets mouse sensitivity for the current profile. Param: sensitivity = float multiplier as saved by the options screen. Use in config scripts. Returns 1.", 1);
	MakeName(0x00403950, "GOGfxDisp");
	SetFunctionCmt(0x00403950, "Sets display-mode selection for the current profile. Param: displayMode = mode index from the retail display list (see Display_GetActiveMode/display table). Use in config scripts. ", 1);
	MakeName(0x00403A00, "GOGameLang");
	SetFunctionCmt(0x00403A00, "Sets game language for the current profile. Param: language = language index (retail ships English=0 and German builds use their own index). Use in config scripts. Returns 1.", 1);
	MakeName(0x00403AC0, "GOGameDiff");
	SetFunctionCmt(0x00403AC0, "Sets game difficulty for the current profile. Param: difficulty = 0 easy, 1 medium, 2 hard (retail order). Use in config scripts. Returns 1.", 1);
	MakeName(0x00403B30, "Config_IsGermany");
	SetFunctionCmt(0x00403B30, "RETURNS 1 when running the GERMAN retail build (censored variant), 0 otherwise. Takes no args. German builds gate blood/gore - check before forcing such effects.", 1);
	MakeName(0x00403B70, "Config_ResetGraphicOptions");
	SetFunctionCmt(0x00403B70, "Resets the ACTIVE PROFILE's graphic options to defaults (display mode, gamma, transparency, performance flags). Takes no script args (registrar argc=0 at site 0x40352B; machine cod", 1);
	MakeName(0x00403C10, "GO_ContentControlPW");
	SetFunctionCmt(0x00403C10, "Config-writer form (argc=1): sets the content-control password while a config file is parsed. Param: password = string. Returns 1.", 1);
	MakeName(0x00403C70, "Config_GetContentControlPassword");
	SetFunctionCmt(0x00403C70, "RETURNS the stored content-control (parental lock) password string. Takes no args. Compare against user input or pass to Config_VerifyContentControlPassword.", 1);
	MakeName(0x00403CC0, "Config_VerifyContentControlPassword");
	SetFunctionCmt(0x00403CC0, "Checks a password attempt against the stored content-control password. Param: password = string to test. RETURNS non-zero when correct, 0 when wrong. Use before unlocking violent-c", 1);
	MakeName(0x00403D90, "Config_IsContentControlPasswordEnabled");
	SetFunctionCmt(0x00403D90, "RETURNS 1 if a content-control password is SET (parental lock active), else 0. Takes no args. Use to decide whether to ask for the password.", 1);
	MakeName(0x00403DF0, "GOIsBlood");
	SetFunctionCmt(0x00403DF0, "Toggles blood effects for the current profile. Param: blood = 1 on, 0 off. Use in config scripts. Returns 1.", 1);
	MakeName(0x00403E60, "GOSoundSpeech");
	SetFunctionCmt(0x00403E60, "Sets speech volume for the current profile. Param: volume = float 0.0-1.0. Use in config scripts. Returns 1.", 1);
	MakeName(0x00403EF0, "GOSoundMusic");
	SetFunctionCmt(0x00403EF0, "Sets music volume for the current profile. Param: volume = float 0.0-1.0. Use in config scripts. Returns 1.", 1);
	MakeName(0x00403F80, "GOSoundFX");
	SetFunctionCmt(0x00403F80, "Sets sound-effects volume for the current profile. Param: volume = float 0.0-1.0. Use in config scripts. Returns 1.", 1);
	MakeName(0x00404010, "GOGfxDevice");
	SetFunctionCmt(0x00404010, "Sets render-device (D3D device/GUID) selection for the current profile. Param: deviceIndex = index into the render-device list filled by Config_FillRenderDeviceListBox. Use in conf", 1);
	MakeName(0x00404080, "GOGfxGamma");
	SetFunctionCmt(0x00404080, "Sets gamma for the current profile. Param: gamma = float, retail default 1.0 (range ~0.5-3.0 clamped elsewhere). Use in config scripts. Returns 1.", 1);
	MakeName(0x004040F0, "GOGfxPerformance");
	SetFunctionCmt(0x004040F0, "Sets graphics performance/detail flags for the current profile. Param: flags = bitmask from the detail-level mapping (see Config_GraphicOptionsGetPerfFlagsFromLevel). Use in config", 1);
	MakeName(0x00404160, "Config_GameOptionsInputSetInvertMouse");
	SetFunctionCmt(0x00404160, "Sets invert-mouse in the GAME-OPTIONS block while a config file is parsed (the GO_* writer side; runtime getter/setter pair lives on the profile). Param: invert = 1 inverted, 0 nor", 1);
	MakeName(0x004041D0, "Config_GameOptionsInputGetInvertMouse");
	SetFunctionCmt(0x004041D0, "RETURNS the invert-mouse setting when the engine writes/reads a config game-options block (1 = inverted, 0 = normal). Takes no args. Pairs with Config_GameOptionsInputSetInvertMous", 1);
	MakeName(0x00404230, "Config_GameOptionsInputSetMouseSensitivity");
	SetFunctionCmt(0x00404230, "Sets mouse-sensitivity in the config game-options write-out context. Param: value = sensitivity as stored by the options screen (integer scale).", 1);
	MakeName(0x00404290, "Config_GameOptionsInputGetMouseSensitivity");
	SetFunctionCmt(0x00404290, "RETURNS the stored mouse-sensitivity integer from the game-options config context. Takes no args.", 1);
	MakeName(0x004042E0, "Config_GameOptionsInputSetBloodEnabled");
	SetFunctionCmt(0x004042E0, "Sets blood-enabled in the config game-options write-out context. Param: blood = 1 on, 0 off.", 1);
	MakeName(0x00404340, "Config_GameOptionsInputGetBloodEnabled");
	SetFunctionCmt(0x00404340, "RETURNS the blood-enabled flag from the game-options config context (1/0). Takes no args.", 1);
	MakeName(0x00404450, "Config_FillScreenResolutionListBox");
	SetFunctionCmt(0x00404450, "Fills the currently-active menu list box with the screen resolutions available for a device. Param: deviceIndex = render-device index. Use only inside a menu list box 'collect item", 1);
	MakeName(0x00404510, "Config_GraphicOptionsSetResolution");
	SetFunctionCmt(0x00404510, "Applies a screen resolution to the active profile and re-initialises the display. Param: modeIndex = index from Config_FillScreenResolutionListBox entries. Use in the video-options", 1);
	MakeName(0x00404590, "ConfigGetActiveGraphicOptions");
	SetFunctionCmt(0x00404590, "Returns a pointer to the ACTIVE PROFILE's graphic-options record inside the global config array. The record base is 0xBC2394 + 0xD14 * activeProfileIndex (verified in igi.exe). Use", 1);
	MakeName(0x004045B0, "Config_GraphicOptionsGetResolution");
	SetFunctionCmt(0x004045B0, "Returns the active profile's display-mode/resolution index (same index space as Config_GraphicOptionsSetResolution). Use in video-options UI scripts to preselect the current value.", 1);
	MakeName(0x004046A0, "Config_FillRenderDeviceListBox");
	SetFunctionCmt(0x004046A0, "Fills the currently-active menu list box with installed render devices (Direct3D device GUIDs/names). Use inside a list box collect-items script on the video-options screen.", 1);
	MakeName(0x00404710, "Config_GraphicOptionsGetDevice");
	SetFunctionCmt(0x00404710, "Returns the active profile's render-device index (index into the device list). Use in video-options UI scripts.", 1);
	MakeName(0x004047F0, "Config_GraphicOptionsSetDevice");
	SetFunctionCmt(0x004047F0, "Applies a render device to the active profile. Param: deviceIndex = index from Config_FillRenderDeviceListBox. Use in video-options screen script.", 1);
	MakeName(0x004048B0, "Config_GraphicOptionsSetGamma");
	SetFunctionCmt(0x004048B0, "Sets and immediately applies gamma to the active profile (also feeds the live lighting math through the profile record +0x220). Param: gamma = float (retail default 1.0). Use in vi", 1);
	MakeName(0x00404910, "Config_GraphicOptionsGetGamma");
	SetFunctionCmt(0x00404910, "Returns the active profile's gamma as a float. Use to initialise your own gamma slider/UI.", 1);
	MakeName(0x00404960, "Config_GraphicOptionsSetTransparency");
	SetFunctionCmt(0x00404960, "Toggles transparency for the active profile. Param: onOff = 1 enable, 0 disable. Video-options screen.", 1);
	MakeName(0x004049C0, "Config_GraphicOptionsGetTransparency");
	SetFunctionCmt(0x004049C0, "Returns 1 if transparency is enabled for the active profile, else 0.", 1);
	MakeName(0x00404A10, "Config_SoundOptionsSetSoundsEffects");
	SetFunctionCmt(0x00404A10, "Enables/disables sound effects for the active profile. Param: onOff = 1 on, 0 off.", 1);
	MakeName(0x00404A90, "Config_SoundOptionsGetSoundsEffects");
	SetFunctionCmt(0x00404A90, "Returns 1 if sound effects are enabled for the active profile, else 0.", 1);
	MakeName(0x00404AE0, "Config_SoundOptionsSetSoundsEffectsVolume");
	SetFunctionCmt(0x00404AE0, "Sets SFX volume for the active profile. Param: volume = float 0.0-1.0.", 1);
	MakeName(0x00404B40, "Config_SoundOptionsGetSoundsEffectsVolume");
	SetFunctionCmt(0x00404B40, "Returns the active profile's SFX volume (0.0-1.0).", 1);
	MakeName(0x00404B90, "Config_SoundOptionsSetMusic");
	SetFunctionCmt(0x00404B90, "Enables/disables music for the active profile. Param: onOff = 1 on, 0 off.", 1);
	MakeName(0x00404BF0, "Config_SoundOptionsGetMusic");
	SetFunctionCmt(0x00404BF0, "Returns 1 if music is enabled for the active profile, else 0.", 1);
	MakeName(0x00404C40, "Config_SoundOptionsSetMusicVolume");
	SetFunctionCmt(0x00404C40, "Sets music volume for the active profile. Param: volume = float 0.0-1.0 (pops a float arg - pass a float!).", 1);
	MakeName(0x00404CA0, "Config_SoundOptionsGetMusicVolume");
	SetFunctionCmt(0x00404CA0, "Returns the active profile's music volume (0.0-1.0).", 1);
	MakeName(0x00404CF0, "Config_SoundOptionsSetSpeech");
	SetFunctionCmt(0x00404CF0, "Enables/disables radio speech for the active profile. Param: onOff = 1 on, 0 off.", 1);
	MakeName(0x00404D50, "Config_SoundOptionsGetSpeech");
	SetFunctionCmt(0x00404D50, "Returns 1 if speech is enabled for the active profile, else 0.", 1);
	MakeName(0x00404DA0, "Config_SoundOptionsSetSpeechVolume");
	SetFunctionCmt(0x00404DA0, "Sets speech volume for the active profile. Param: volume = float 0.0-1.0.", 1);
	MakeName(0x00404E00, "Config_SoundOptionsGetSpeechVolume");
	SetFunctionCmt(0x00404E00, "Returns the active profile's speech volume (0.0-1.0).", 1);
	MakeName(0x00404E50, "Config_SoundOptionsSetReverseStereo");
	SetFunctionCmt(0x00404E50, "Toggles reversed stereo channels for the active profile. Param: onOff = 1 reverse, 0 normal.", 1);
	MakeName(0x00404EB0, "Config_SoundOptionsGetReverseStereo");
	SetFunctionCmt(0x00404EB0, "Returns 1 if stereo is reversed for the active profile, else 0.", 1);
	MakeName(0x00404F00, "Config_GraphicOptionsSetPerformanceFlags");
	SetFunctionCmt(0x00404F00, "Sets the raw graphics performance/detail flag bits on the active profile. Param: flags = bitmask (get a valid one from Config_GraphicOptionsGetPerfFlagsFromLevel).", 1);
	MakeName(0x00404F60, "Config_GraphicOptionsGetPerformanceFlags");
	SetFunctionCmt(0x00404F60, "Returns the active profile's graphics performance flag bitmask.", 1);
	MakeName(0x00404FA0, "Config_FillPlayerProfileListBox");
	SetFunctionCmt(0x00404FA0, "Fills the current menu list box with all player profiles (name per row, row index = profile index). Use inside the profile-selection list box collect-items script.", 1);
	MakeName(0x00405010, "Config_GetActivePlayerProfileIndex");
	SetFunctionCmt(0x00405010, "RETURNS the index of the currently-active player profile (0-based). Takes no arguments. Use whenever you need which profile is selected, e.g. before Config_DeletePlayerProfile.", 1);
	MakeName(0x00405050, "Config_SetActivePlayerProfileIndex");
	SetFunctionCmt(0x00405050, "Makes 'index' the active player profile. Param: index = 0-based profile index (must exist; see Config_GetNumberOfPlayerProfiles).", 1);
	MakeName(0x004050A0, "Config_CreateNewPlayerProfile");
	SetFunctionCmt(0x004050A0, "Creates a new player profile. Params: name = new profile name (string), sourceIndex = existing profile index to copy initial settings from. RETURNS 1 on success, 0 on failure (e.g.", 1);
	MakeName(0x00405400, "Config_DeletePlayerProfile");
	SetFunctionCmt(0x00405400, "Deletes a player profile. Param: index = 0-based profile index to delete. RETURNS 1 on success, 0 on failure. Do not delete the last remaining profile; refresh your list box afterw", 1);
	MakeName(0x004054F0, "Config_GetNumberOfPlayerProfiles");
	SetFunctionCmt(0x004054F0, "RETURNS how many player profiles exist. Use to bounds-check indexes and to size profile lists.", 1);
	MakeName(0x00405530, "Config_GraphicOptionsGetPerfLevelFromFlags");
	SetFunctionCmt(0x00405530, "Converts a performance-flag bitmask back into its detail LEVEL number. Param: flags = bitmask from the profile/performance setting. Use to show the current detail level in UI.", 1);
	MakeName(0x004055C0, "Config_GraphicOptionsGetPerfFlagsFromLevel");
	SetFunctionCmt(0x004055C0, "Converts a detail LEVEL number into its performance-flag bitmask. Param: level = 0..Config_GraphicOptionsNumPerfLevels()-1. Use when the user picks a named detail preset.", 1);
	MakeName(0x00405620, "Config_GraphicOptionsNumPerfLevels");
	SetFunctionCmt(0x00405620, "RETURNS the number of graphics detail levels the engine supports (constant). Use to build the detail-level slider/list.", 1);
	MakeName(0x00405660, "Config_FillMissionSelectionBox");
	SetFunctionCmt(0x00405660, "Fills the current menu list box with missions selectable for the active profile (respects unlocked progress). Use inside the mission-selection list box collect-items script.", 1);
	MakeName(0x004056F0, "Config_FillMissionPictureBox");
	SetFunctionCmt(0x004056F0, "Fills the current picture box with the selected mission's briefing image. Use inside the mission-picture control's script right after a mission row is chosen.", 1);
	MakeName(0x00405760, "Config_FillMissionTextBox");
	SetFunctionCmt(0x00405760, "Fills the current text box with the selected mission's briefing text. Use inside the mission-briefing text control's script.", 1);
	MakeName(0x004057D0, "Config_PlayerGetActiveMission");
	SetFunctionCmt(0x004057D0, "Returns the active (reached) mission number of ANY profile. Param: profileIndex = 0-based profile index. Use on the profile/mission screens to show progress without switching profi", 1);
	MakeName(0x00405850, "ConfigRead");
	SetFunctionCmt(0x00405850, "Read game config file, Params:  File: 'LOCAL:config.qsc'", 1);
	MakeName(0x00405BD0, "ConfigWrite");
	SetFunctionCmt(0x00405BD0, "Write game config file, Params: File: 'LOCAL:config.qsc'", 1);
	MakeName(0x00406220, "Config_GetActivePlayerProfileRecord");
	SetFunctionCmt(0x00406220, "RETURNS pointer to the ACTIVE PROFILE's graphic-options/config record: computed as 0xBC2388 + 0xD14*[0xBC2384] (verified against retail defaults-reset fcn.00403B70 which walks the ", 1);
	MakeName(0x004071E0, "WeaponConfigRead");
	SetFunctionCmt(0x004071E0, "Reads/compiles a WEAPON CONFIG text: strlen-copies cfgText into the engine's static config buffer (0x5690F0) then hands it to ConfigCompile (0x4F0CF0) - the compiled task list driv", 1);
	MakeName(0x00407E30, "DefineQMaterial");
	SetFunctionCmt(0x00407E30, "Defines a Q-material (surface material) entry while a material definition block is parsed. Called BY the engine's own define-block parser - call only from material .qsc definition ", 1);
	MakeName(0x00407F50, "DefineGameMaterial");
	SetFunctionCmt(0x00407F50, "Defines a GameMaterial entry during a game-material definition block (855-byte parser function). Call only from gamematerial .qsc definition contexts; arg layout follows the Define", 1);
	MakeName(0x00408350, "GameMaterial_LoadParameters");
	SetFunctionCmt(0x00408350, "Name from igi.exe error string inside function: \"GameMaterial_LoadParameters: Couldn't load script \\"%s\\"\". Loads game-material parameters from its script.", 1);
	MakeName(0x004101C0, "DefineHumanPlayerWeaponCycle");
	SetFunctionCmt(0x004101C0, "Collects the weapon-cycle list for the human player: loops the parsed entries and stores them into the cycle table at 0x56DF1C with count at 0x56DF18 (verified in igi.exe). Call wi", 1);
	MakeName(0x00410240, "DefineHumanPlayerWeaponCategory");
	SetFunctionCmt(0x00410240, "Registers one weapon-category entry for the human player during a humanplayer definition block (argc unknown - parser context). Pairs with DefineHumanPlayerWeaponCycle/Cycle orderi", 1);
	MakeName(0x004102D0, "DefineHumanPlayerAmmoLimit");
	SetFunctionCmt(0x004102D0, "Registers an ammo-limit entry (max carried ammo class) for the human player during a humanplayer definition block (argc unknown - parser context).", 1);
	MakeName(0x004137A0, "HumanPlayer_LoadParameters");
	SetFunctionCmt(0x004137A0, "Name from igi.exe error string inside function: \"HumanPlayer_LoadParameters: Couldn't load script \\"%s\\"\". Loads humanplayer parameters (weapons/ammo/cycle definitions) from sc", 1);
	MakeName(0x00413B70, "WeaponTypeOpen");
	SetFunctionCmt(0x00413B70, "Open all weapons defined in .qsc file for Humanplayer.", 1);
	MakeName(0x00413BB0, "WeaponsCountGet");
	SetFunctionCmt(0x00413BB0, "RETURNS the number of weapons defined for the human player: reads global counter 0x57B18C (exactly `mov eax,[0x57B18C]; ret`). That counter is written by the DefineHumanPlayerWeapo", 1);
	MakeName(0x00415020, "DEBUG_KEYS_ENABLE_INVALID");
	SetFunctionCmt(0x00415020, "TOMBSTONE - DO NOT INVOKE. The retail debug-keys native address is UNKNOWN. The old value 0x0041502 lies outside .text (0x401000-0x532510) and would crash on invoke; no verified re", 1);
	MakeName(0x004151E0, "MovieSubtitle_RegisterFont");
	SetFunctionCmt(0x004151E0, "Registers a font used by in-game movie subtitles (16 callsites in body; argc unknown - parser context). Call from subtitle/font definition blocks before any MovieSubtitle_RegisterT", 1);
	MakeName(0x00415260, "MovieSubtitle_RegisterText");
	SetFunctionCmt(0x00415260, "Registers one subtitle text entry (string + timing) shown over movies/briefings (argc unknown - parser context). Call after the font registration it should use.", 1);
	MakeName(0x004157D0, "Game_DisablePlayerInput");
	SetFunctionCmt(0x004157D0, "Disables ALL player input (keyboard+mouse) - used by cutscenes/menus. Re-enable with Game_EnablePlayerInput.", 1);
	MakeName(0x00415830, "Game_EnablePlayerInput");
	SetFunctionCmt(0x00415830, "Re-enables player input after Game_DisablePlayerInput. Takes no args.", 1);
	MakeName(0x00415890, "Game_SetMission");
	SetFunctionCmt(0x00415890, "Selects the mission the game will run/load next. Param: mission = mission index 1..14. Use before Level_Start/level load flow when jumping straight into a mission.", 1);
	MakeName(0x004158E0, "Game_UpdateVolume");
	SetFunctionCmt(0x004158E0, "Applies current profile music/sfx volumes to the live audio engines. Takes no args.", 1);
	MakeName(0x00415950, "Game_SetMusicVolume");
	SetFunctionCmt(0x00415950, "Live-sets music volume through the profile real-value setter (fcn.004B8A50): retail body constructs 1.0f (0x3FF00000) and stores via fstp. Param: volume = float 0.0-1.0. Called by ", 1);
	MakeName(0x004159B0, "Game_SetSFXVolume");
	SetFunctionCmt(0x004159B0, "Live-sets sound-effects volume through the profile real-value setter (fcn.004B8A50), same 1.0f construction pattern. Param: volume = float 0.0-1.0. Called by ingamemenu.qvm options", 1);
	MakeName(0x00415A10, "Game_EnableMusic");
	SetFunctionCmt(0x00415A10, "Starts/resumes the music engine. Takes no args.", 1);
	MakeName(0x00415A60, "Game_DisableMusic");
	SetFunctionCmt(0x00415A60, "Stops the music engine. Takes no args.", 1);
	MakeName(0x00415AB0, "Game_CutsceneDelete");
	SetFunctionCmt(0x00415AB0, "Deletes/ends the running cutscene and frees its resources. Takes no args.", 1);
	MakeName(0x00415B30, "LevelStart");
	SetFunctionCmt(0x00415B30, "Start new level, Params:  p1: 0057BABC", 1);
	MakeName(0x00416550, "Game_DeleteHandler");
	SetFunctionCmt(0x00416550, "The game's DELETE handler - runs when a level/game session is torn down (quit path), releasing entities and session state. Takes no args. Engine-internal teardown; do not call to '", 1);
	MakeName(0x00416D80, "Human_HitDamage");
	SetFunctionCmt(0x00416D80, "Reads the player XP/hit byte: returns byte [PlayerPtr+0xE1]. Takes no args. Documented alias of HUMAN_HIT_DAMAGE - same address.", 1);
	MakeName(0x00416FE0, "Game_Restart");
	SetFunctionCmt(0x00416FE0, "Restarts the CURRENT LEVEL/session: tears down and reloads the running game state (the Ctrl+F4-style restart path). Takes no args. Use to reset the mission without going back to me", 1);
	MakeName(0x004174A0, "MenuManager_RequestScreen");
	SetFunctionCmt(0x004174A0, "Requests a menu screen by id through the menu manager (queued request). Params: screenId = retail screen resource id, flags = request modifier (0 = normal). Use outside the menu st", 1);
	MakeName(0x00417690, "MenuManager_PushScreen");
	SetFunctionCmt(0x00417690, "Pushes a screen onto the menu stack: allocates the screen object (objsize 0x2898) and stores it in the manager's screen stack at mgr+0x27EC (verified in igi.exe). Param: screenId =", 1);
	MakeName(0x00417710, "MenuManager_PopScreen");
	SetFunctionCmt(0x00417710, "Pops the top screen off the menu stack (destroys it) revealing the one beneath. Param: param = pass-through argument observed in retail calls (pass 0). Pair with MenuManager_PushSc", 1);
	MakeName(0x00417790, "MenuManager_LeaveMenus");
	SetFunctionCmt(0x00417790, "Leaves/closes the whole menu system returning to gameplay. Params: two ints observed in retail calls (pass 0,0). Use to exit from custom menus.", 1);
	MakeName(0x00417810, "MenuManager_SetLanguage");
	SetFunctionCmt(0x00417810, "Switches menu/UI language at runtime. Param: langIndex = language index matching the LANGUAGE\ folder tables. Call before pushing screens so texts load in the right language.", 1);
	MakeName(0x00417880, "MenuManager_ForceUpdateWindow");
	SetFunctionCmt(0x00417880, "Forces the menu manager to redraw/update its windows this frame. Param: observed retail value 0. Use after changing control contents from script.", 1);
	MakeName(0x00417900, "MenuManager_ActivatePopupScreen");
	SetFunctionCmt(0x00417900, "Activates a popup screen on top of the current menus (e.g. confirmation dialogs; retail scripts call MenuManager_ActivatePopupScreen(930)). Param: popupId = retail popup screen id.", 1);
	MakeName(0x00417960, "MenuManager_DeactivatePopuScreen");
	SetFunctionCmt(0x00417960, "Deactivates the currently-active popup screen and returns to the screen beneath. Takes no args. Pair with MenuManager_ActivatePopupScreen. NOTE: name mirrors the retail registratio", 1);
	MakeName(0x004179B0, "MenuManager_SetEnabled");
	SetFunctionCmt(0x004179B0, "Enables/disables menu-manager input processing. Param: enabled = 1 menus react to input, 0 frozen. Use to freeze menus during scripted sequences.", 1);
	MakeName(0x00418B00, "MenuManager");
	SetFunctionCmt(0x00418B00, "MenuManager load for inagame or Mainmenu,Params:  p1: 0057BABC ,p3,p4,p5: 0.", 1);
	MakeName(0x004231E0, "ControlsMenu_ConvertFloatFromOffset");
	SetFunctionCmt(0x004231E0, "Converts a controls-menu slider/storage OFFSET into its float value (0.0-1.0 range used by the control configuration bars). Param: offset = raw integer offset stored for that contr", 1);
	MakeName(0x00423240, "ControlsMenu_ConvertOffsetFromFloat");
	SetFunctionCmt(0x00423240, "Inverse of ControlsMenu_ConvertFloatFromOffset: converts a float control value into the raw storage offset. Param: value = float 0.0-1.0. Use when saving a modified binding back.", 1);
	MakeName(0x0044D0E0, "AIAction_Patrol");
	SetFunctionCmt(0x0044D0E0, "Orders the AI into PATROL behaviour. Params: target = patrol goal/node reference from your script, mustBeZero = retail template always passes 0, flags = AIACTIONFLAG enum: NONE=0, ", 1);
	MakeName(0x0044D160, "AIAction_Combat");
	SetFunctionCmt(0x0044D160, "Orders the AI into COMBAT behaviour vs its current enemy. Param: param = combat argument from the calling script (retail guard scripts pass their combat target/context value). Use ", 1);
	MakeName(0x0044D260, "AIAction_Dead");
	SetFunctionCmt(0x0044D260, "Runs the DEATH handling action for the AI (plays death, releases tasks). Param: param = death context value passed by retail scripts. Use in AIEVENT_DEAD handler.", 1);
	MakeName(0x0044D2C0, "AIAction_FallFlat");
	SetFunctionCmt(0x0044D2C0, "Knocks the AI flat on the ground (ragdoll-ish fall, e.g. after explosion/surrender). Params: two ints observed in retail calls (pass 0,0 unless mapping specific values). Use for sc", 1);
	MakeName(0x0044D420, "AIAction_Activate");
	SetFunctionCmt(0x0044D420, "Generic ACTIVATE action: sends the AI to activate/use an object (switch, door, alarm...). Params: target = object/task reference, param2 = secondary value (retail passes 0), flags ", 1);
	MakeName(0x0044D4A0, "AIAction_WalkToNode");
	SetFunctionCmt(0x0044D4A0, "Walks the AI to a nav node. Params: nodeId = graph/node id from the level nav data, flags = AIACTIONFLAG (NONE=0/PUSHABLE=1). Use for calm movement in AI scripts.", 1);
	MakeName(0x0044D510, "AIAction_RunToNode");
	SetFunctionCmt(0x0044D510, "Runs the AI to a nav node (fast). Same params as AIAction_WalkToNode: nodeId = node id, flags = AIACTIONFLAG (NONE=0/PUSHABLE=1).", 1);
	MakeName(0x0044D580, "AIAction_FireAtNode");
	SetFunctionCmt(0x0044D580, "Makes the AI fire AT a nav-node position. Params: nodeId = target node id, remaining 4 args = firing stance/behaviour values observed in retail AI scripts (map before inventing val", 1);
	MakeName(0x0044D630, "AIAction_FireAtTask");
	SetFunctionCmt(0x0044D630, "Makes the AI fire AT a task/object entity. Params: taskId = target task/entity id, remaining 4 args = firing behaviour values (same layout family as FireAtNode). Use in combat hand", 1);
	MakeName(0x0044D6E0, "AIAction_PlayAnimation");
	SetFunctionCmt(0x0044D6E0, "Plays an animation on the AI. Params: animationId = animation entry id (see AIFunction_AddAnimationEntry), flags = AIACTIONFLAG (NONE=0/PUSHABLE=1).", 1);
	MakeName(0x0044D750, "AIAction_PlaySound");
	SetFunctionCmt(0x0044D750, "Plays a sound from the AI (voice barks etc.). Params: soundId = sound/event id, param2 = observed 0 in retail, flags = AIACTIONFLAG (NONE=0/PUSHABLE=1).", 1);
	MakeName(0x0044D7D0, "AIAction_MoveToEvent");
	SetFunctionCmt(0x0044D7D0, "Moves the AI toward the source position of an EVENT it received. Params: eventId = AIEVENT_* whose position to move to, flags = AIACTIONFLAG (NONE=0/PUSHABLE=1). Use in event handl", 1);
	MakeName(0x0044D870, "AIAction_LookAtEvent");
	SetFunctionCmt(0x0044D870, "Turns the AI to LOOK toward an event's source without moving. Params: eventId = AIEVENT_* value, flags = AIACTIONFLAG (NONE=0/PUSHABLE=1).", 1);
	MakeName(0x0044D8F0, "AIAction_Stunned");
	SetFunctionCmt(0x0044D8F0, "Stuns the AI (flashbang/knockout reaction). Params: param1 = stun duration/context value, flags = AIACTIONFLAG (NONE=0/PUSHABLE=1).", 1);
	MakeName(0x0044D960, "AIAction_KickGrenade");
	SetFunctionCmt(0x0044D960, "Kicks a nearby live grenade away (retail soldier behaviour). Param: param = grenade/context reference from the event. Use in grenade-event handlers.", 1);
	MakeName(0x0044DA00, "AIAction_RunPanicking");
	SetFunctionCmt(0x0044DA00, "Sends the AI into PANIC running (civilians under fire). Params: param1 = panic target/context, flags = AIACTIONFLAG (NONE=0/PUSHABLE=1).", 1);
	MakeName(0x0044DA80, "AIAction_Idle");
	SetFunctionCmt(0x0044DA80, "Puts the AI into IDLE (stands, resumes idle animation countdown). Param: idle context value (retail scripts pass their idle value). Use in AIEVENT_IDLE handler instead of Patrol fo", 1);
	MakeName(0x0044DAE0, "AIAction_SetCombat");
	SetFunctionCmt(0x0044DAE0, "Force-sets the AI's COMBAT ENEMY/target. Param: enemyId = enemy entity/id to engage. Use to make an AI attack a specific target regardless of detection.", 1);
	MakeName(0x0044DBC0, "AIFunction_RemoveAlarmActions");
	SetFunctionCmt(0x0044DBC0, "Removes all queued ALARM-related actions from this AI (calms it down). Takes no args. Use to de-escalate an NPC you control.", 1);
	MakeName(0x0044DC40, "AIFunction_SetViewLength");
	SetFunctionCmt(0x0044DC40, "Sets this AI's VIEW LENGTH - how far it can see. Param: length = view distance in engine units. Use in AI init (AIEVENT_CREATE) to buff/nerf vision.", 1);
	MakeName(0x0044DCD0, "AIFunction_SetAlarmViewLength");
	SetFunctionCmt(0x0044DCD0, "Sets view length WHILE AN ALARM IS ON (separate stat from normal vision). Param: length = distance in engine units. Use in AI init.", 1);
	MakeName(0x0044DD30, "AIFunction_SetViewAlpha");
	SetFunctionCmt(0x0044DD30, "Sets view ALPHA - the detection speed/gain of normal vision. Param: alpha = engine detection factor. Higher = spots player faster. Use in AIEVENT_CREATE.", 1);
	MakeName(0x0044DD90, "AIFunction_SetViewGamma");
	SetFunctionCmt(0x0044DD90, "Sets view GAMMA - secondary vision shaping factor for detection. Param: gamma = engine factor. Use in AI init alongside SetViewAlpha.", 1);
	MakeName(0x0044DDF0, "AIFunction_SetSecondaryViewLength");
	SetFunctionCmt(0x0044DDF0, "Sets SECONDARY view length (peripheral/short-range channel). Param: length = distance in engine units.", 1);
	MakeName(0x0044DE80, "AIFunction_SetSecondaryAlarmViewLength");
	SetFunctionCmt(0x0044DE80, "Sets secondary view length during alarms. Param: length = distance in engine units.", 1);
	MakeName(0x0044DEE0, "AIFunction_SetSecondaryViewAlpha");
	SetFunctionCmt(0x0044DEE0, "Sets secondary-view detection gain. Param: alpha = engine factor.", 1);
	MakeName(0x0044DF40, "AIFunction_SetSecondaryViewGamma");
	SetFunctionCmt(0x0044DF40, "Sets secondary-view gamma shaping factor. Param: gamma = engine factor.", 1);
	MakeName(0x0044DFA0, "AIFunction_GetCurrentEventType");
	SetFunctionCmt(0x0044DFA0, "RETURNS the AIEVENT_* value currently being handled - the backbone of every AI script's if/else chain. Enum: CREATE=0, DELETE=1, DEAD=2, ANIMATION=3, IDLE=4, ALERT=5, ALERT_RESPONS", 1);
	MakeName(0x0044E000, "AIFunction_GetRandomValue");
	SetFunctionCmt(0x0044E000, "RETURNS a random value below 'max' (returns Real per retail table). Param: max = upper bound. Use for randomized behaviour delays/targets in AI scripts.", 1);
	MakeName(0x0044E060, "AIFunction_DefaultHandler");
	SetFunctionCmt(0x0044E060, "The default AI event handler: call this for any AIEVENT_* your script does not handle explicitly (retail template shows it as the else-branch body). Takes no args. Put inside every", 1);
	MakeName(0x0044E0C0, "AIFunction_SetEventPriority");
	SetFunctionCmt(0x0044E0C0, "Sets the priority of the CURRENT event being handled (decides which queued event wins). Param: priority = engine priority number. Use inside an event handler.", 1);
	MakeName(0x0044E150, "AIFunction_SetInvulnerability");
	SetFunctionCmt(0x0044E150, "Makes this AI invulnerable. Param: onOff = 1 immune to damage, 0 normal. Great for boss/scripted NPCs. Use in AIEVENT_CREATE or anytime.", 1);
	MakeName(0x0044E1B0, "AIFunction_SetInstantDeath");
	SetFunctionCmt(0x0044E1B0, "When on, any hit instantly kills this AI (no damage pooling). Param: onOff = 1 one-shot kills, 0 normal health. Use for scripted one-shot enemies.", 1);
	MakeName(0x0044E210, "AIFunction_SetDeathAnimation");
	SetFunctionCmt(0x0044E210, "Overrides the death animation played when this AI dies. Param: animId = animation entry id. Use in AI init for custom deaths.", 1);
	MakeName(0x0044E270, "AIFunction_SetAlarmTriggerID");
	SetFunctionCmt(0x0044E270, "Binds an ALARM trigger object to this AI (which alarm switch it responds to/runs to). Param: id = alarm trigger id from the level. Retail template: AIFunction_SetAlarmTriggerID(xx)", 1);
	MakeName(0x0044E2D0, "AIFunction_SetAlarmControlID");
	SetFunctionCmt(0x0044E2D0, "Binds the ALARM CONTROL (the raised-alarm device) this AI uses. Param: id = alarm control id from the level. Retail template: AIFunction_SetAlarmControlID(xx).", 1);
	MakeName(0x0044E330, "AIFunction_SetAlarmAccess");
	SetFunctionCmt(0x0044E330, "Sets HOW the AI treats the alarm route. Param: access = AIALARMACCESS enum: BEFORECOMBAT=0 (run for the alarm first), AFTERCOMBAT=1 (fight first, raise alarm after). Retail templat", 1);
	MakeName(0x0044E390, "AIFunction_SetGunnerID");
	SetFunctionCmt(0x0044E390, "Assigns which mounted-gunner slot this AI mans. Param: gunnerId = gunner position id. Use in AI init for turret/mounted-gun NPCs.", 1);
	MakeName(0x0044E3F0, "AIFunction_GetAlarmTriggerID");
	SetFunctionCmt(0x0044E3F0, "RETURNS the id of the alarm trigger bound to this AI (see AIFunction_SetAlarmTriggerID). Takes no args. Use in handlers to check which alarm applies.", 1);
	MakeName(0x0044E430, "AIFunction_GetAlarmControlID");
	SetFunctionCmt(0x0044E430, "RETURNS the bound alarm-control id. Takes no args.", 1);
	MakeName(0x0044E470, "AIFunction_GetAlarmAccess");
	SetFunctionCmt(0x0044E470, "RETURNS the current AIALARMACCESS mode: BEFORECOMBAT=0, AFTERCOMBAT=1. Takes no args.", 1);
	MakeName(0x0044E4B0, "AIFunction_GetGunnerID");
	SetFunctionCmt(0x0044E4B0, "RETURNS this AI's assigned gunner slot id. Takes no args.", 1);
	MakeName(0x0044E4F0, "AIFunction_GetAlarmControlStatus");
	SetFunctionCmt(0x0044E4F0, "RETURNS the status/state of the bound alarm control (raised/used state as tracked by the engine). Takes no args.", 1);
	MakeName(0x0044E5E0, "AIFunction_GetGunnerStatus");
	SetFunctionCmt(0x0044E5E0, "RETURNS the status of this AI's gunner post (manned/state value). Takes no args.", 1);
	MakeName(0x0044E6D0, "AIFunction_SetScriptIntegerValue");
	SetFunctionCmt(0x0044E6D0, "Writes an AI-script integer variable. Params: varId = script variable index, value = new integer. Use for custom AI state communication between scripts.", 1);
	MakeName(0x0044E740, "AIFunction_GetScriptIntegerValue");
	SetFunctionCmt(0x0044E740, "READS an AI-script integer variable written by AIFunction_SetScriptIntegerValue. Param: varId = variable index. RETURNS the integer.", 1);
	MakeName(0x0044E790, "AIFunction_SetScriptRealValue");
	SetFunctionCmt(0x0044E790, "Writes an AI-script real (float) variable. Params: varId = script variable index, value = float. Pairs with AIFunction_GetScriptRealValue.", 1);
	MakeName(0x0044E800, "AIFunction_GetScriptRealValue");
	SetFunctionCmt(0x0044E800, "READS an AI-script real (float) variable. Param: varId = variable index. RETURNS the float.", 1);
	MakeName(0x0044E860, "AIFunction_IsEventBehind");
	SetFunctionCmt(0x0044E860, "RETURNS non-zero if the current event came from BEHIND the AI (direction test used for reaction animations). Takes no script args per retail table (engine reads an internal slot vi", 1);
	MakeName(0x0044E930, "AIFunction_GetEventDistance");
	SetFunctionCmt(0x0044E930, "RETURNS the DISTANCE to the source of the current event (Real). Takes no args. Use inside event handlers e.g. 'if gunshot closer than X then investigate'.", 1);
	MakeName(0x0044E9B0, "AIFunction_GetAlarmTriggerDistance");
	SetFunctionCmt(0x0044E9B0, "RETURNS the distance between this AI and its bound ALARM TRIGGER (Real). Takes no args. Use to decide running vs fighting for the alarm.", 1);
	MakeName(0x0044EAF0, "AIFunction_SetAnimationInterval");
	SetFunctionCmt(0x0044EAF0, "Sets playback INTERVAL for an animation entry. Params: entryIndex = animation entry added via AddAnimationEntry, interval = frame/tick interval. Use when tuning scripted animations", 1);
	MakeName(0x0044EBB0, "AIFunction_AddAnimationEntry");
	SetFunctionCmt(0x0044EBB0, "Adds an animation ENTRY to this AI's available set (builds the pick-list GetAnimationToPlay draws from). Params: animationId = animation resource id, data = entry config value. Use", 1);
	MakeName(0x0044ECB0, "AIFunction_GetAnimationToPlay");
	SetFunctionCmt(0x0044ECB0, "RETURNS which animation entry the engine decided to play for the current event/action (useful to log or override reactions). Per retail table takes no script args; machine code als", 1);
	MakeName(0x0044EE40, "AIFunction_SendResponse");
	SetFunctionCmt(0x0044EE40, "Sends the AI's RESPONSE to the current event (used for ALERT_RESPONSE chains so buddy AIs react too). Takes no args. Call inside alert handlers.", 1);
	MakeName(0x0045C440, "SoldierExecute");
	SetFunctionCmt(0x0045C440, "Executes/initializes a SOLDIER AI entity in the level. Params: context = task/context object (2nd arg is the soldier ptr - verified: esi=[esp+0x1C] after prologue). The function re", 1);
	MakeName(0x0045FF80, "WeaponAmmoPickup");
	SetFunctionCmt(0x0045FF80, "Gives an AMMO pickup to the player (same struct conventions as Weapon_GunPickup: player carry-flags and pickup-entity fields drive the grant; plays the pickup sound). Params: playe", 1);
	MakeName(0x0045FFC0, "WeaponGunPickup");
	SetFunctionCmt(0x0045FFC0, "Gives a GUN pickup to the player: checks the player's already-carried flag (player+0xCF5), reads the weapon id from pickupEntity+8 -> word +0x1C, validates the weapon category via ", 1);
	MakeName(0x00463760, "HumanViewCam");
	SetFunctionCmt(0x00463760, "Sets the human's VIEW-CAMERA selector: stores camValue into human struct offset +0x4F0 (verified: mov [ecx+0x4F0],eax; ret - 5-byte setter). Params: human = Human/soldier struct pt", 1);
	MakeName(0x004659E0, "HumanTaskViewReset");
	SetFunctionCmt(0x004659E0, "Resets the human's VIEW TANGENT fields to retail defaults: computes tan() of the half-FOV globals 0x5335E8/0x5339C0 (the same globals ENHANCER::FOV_SET writes) and stores them into", 1);
	MakeName(0x0047CAB0, "AmmoTypeOpen");
	SetFunctionCmt(0x0047CAB0, "Open ammo qvm file to memory for all weapons loaded.", 1);
	MakeName(0x0047CAD0, "DefineAmmoType");
	SetFunctionCmt(0x0047CAD0, "Defines an AMMO TYPE inside an ammo definition block of a .qsc/.cfg script (515-byte parser body; igi.exe embeds str 'DefineAmmoType'). Args follow the Define-ammo grammar (name, d", 1);
	MakeName(0x004828D0, "Human_FindNextCamera");
	SetFunctionCmt(0x004828D0, "Debug camera cycler: advances to the next camera/view target attached to the human player (decompiled body polls input keys). Param: human = human-player pointer. Pass1-verified fu", 1);
	MakeName(0x00484E60, "Mission_Open");
	SetFunctionCmt(0x00484E60, "Name from igi.exe error string inside function: \"Mission_Open(): Couldn't load script: %s\". Opens a mission definition script and builds its task tree.", 1);
	MakeName(0x00484F60, "DefineMission");
	SetFunctionCmt(0x00484F60, "Defines a MISSION entry during mission-list parsing (480-byte parser). Called by the engine's mission definition grammar; do NOT call from gameplay scripts.", 1);
	MakeName(0x00485970, "StatusMessageShow");
	SetFunctionCmt(0x00485970, "Displays an on-screen STATUS MESSAGE (the HUD text that also drives FiberPool pumping!). Params: status_timer = display duration ticks, msg = text, sprite = optional icon sprite, s", 1);
	MakeName(0x00485AD0, "StatusMessageScreen_ClearMessages");
	SetFunctionCmt(0x00485AD0, "Clears all on-screen status messages. Takes no args.", 1);
	MakeName(0x00488E00, "LevelFlow_GetBreakCutSceneKey");
	SetFunctionCmt(0x00488E00, "RETURNS the key code currently bound to 'skip/break cutscene'. Takes no args. Use in cutscene player loops to detect the skip key press.", 1);
	MakeName(0x00488E50, "LevelFlow_LevelFailed");
	SetFunctionCmt(0x00488E50, "Signals that the level FAILED - triggers the retail failure flow (fail sound, restart/quit menu). Takes no args. Call when your scripted objective fails.", 1);
	MakeName(0x00488E90, "LevelFlow_IsCountryUSA");
	SetFunctionCmt(0x00488E90, "RETURNS 1 if the running build is a USA country build, 0 otherwise (affects censorship/content paths like blood). Takes no args. Check before enabling content that country builds g", 1);
	MakeName(0x0048A440, "LoadingScreenShow");
	SetFunctionCmt(0x0048A440, "Shows the LOADING SCREEN: loads LOCAL:menusystem/loadingscreen.res then displays loading.pic - or loading_us.pic on USA country builds (pairs with LevelFlow_IsCountryUSA), wires up", 1);
	MakeName(0x0048F1A0, "AppContextSetDebugged");
	SetFunctionCmt(0x0048F1A0, "Sets the app-level DEBUGGED flag (global 0x5C8BF8). Param: state = 1 mark debugger attached/debug mode, 0 clear. BlankName's IGIPatch calls this by name. Use to toggle engine debug", 1);
	MakeName(0x0048F1E0, "AppContextSetDebugtextState");
	SetFunctionCmt(0x0048F1E0, "Toggles on-screen DEBUG TEXT output (global 0x5C8BF4). Param: state = 1 show engine debug text, 0 hide. Handy while reverse-engineering other systems.", 1);
	MakeName(0x0048F240, "AppContextSetLightmapsUsed");
	SetFunctionCmt(0x0048F240, "Enables/disables OBJECT lightmaps globally (global 0x5C8BE4) - the verified retail lightmap setter. Param: used = 1 use object lightmaps, 0 flat-lit. Use for graphics enhancers (th", 1);
	MakeName(0x0048F260, "AppContextSetTerrainLightmapsUsed");
	SetFunctionCmt(0x0048F260, "Enables/disables TERRAIN lightmaps globally (global 0x5C8BE8). Param: used = 1 lit terrain, 0 unlit. Pair with AppContext_SetLightmapsUsed for full lighting control.", 1);
	MakeName(0x0048F360, "AppMainParseCmdLineArgs");
	SetFunctionCmt(0x0048F360, "Parses the game COMMAND LINE (window mode, resolution and other launch switches; case-insensitive compare loops verified). IGIPatch hooks this for borderless-window support. Engine", 1);
	MakeName(0x00491A90, "DisplaySetMode");
	SetFunctionCmt(0x00491A90, "Switches the DISPLAY MODE at runtime: validates mode fields vs current (0xC28B44...), repositions/resizes the window (GetSystemMetrics), copies the mode into the active-mode struct", 1);
	MakeName(0x00491CF0, "DisplayGetActiveMode");
	SetFunctionCmt(0x00491CF0, "RETURNS pointer to the ACTIVE display-mode struct (global 0xC28B40): width/height/depth fields live at +0x4/+0x8/+0x10 per Display_SetMode comparisons. Takes no args. Read current ", 1);
	MakeName(0x00491E70, "DisplaySetBackgroundColourFn");
	SetFunctionCmt(0x00491E70, "Sets the 3D-view BACKGROUND COLOUR (clear colour) - masks each arg to a byte into globals 0xBCADF0/R,G,B. Params: r,g,b = 0-255 colour channels. Use for custom sky/clear colour eff", 1);
	MakeName(0x00495E70, "MusicSetVolume");
	SetFunctionCmt(0x00495E70, "Sets BOTH music engine volumes (likely front/master pair) after scaling by the global music factor. Params: volume1, volume2 = floats 0.0-1.0 scaled against settings. Use for live ", 1);
	MakeName(0x00495F30, "MusicSetSfxVolume");
	SetFunctionCmt(0x00495F30, "Sets the SFX bus volume feeding the music/sound mix path. Param: volume = float 0.0-1.0 scaled by global factor. Use for live SFX fade.", 1);
	MakeName(0x00497E70, "TranscontextSetActiveTransContext");
	SetFunctionCmt(0x00497E70, "Installs a TRANSFORM CONTEXT as active: copies 0x2A dwords from ctx into global 0xBCAAE0 and bumps state counters at 0x6E5BB0/B4. Param: ctx = transform-context struct (IGIPatch us", 1);
	MakeName(0x004A5350, "FileOpen");
	SetFunctionCmt(0x004A5350, "Open file for reading or writing, Params: Check fopen() in c.", 1);
	MakeName(0x004A53B3, "GameDataSymbolLoad");
	SetFunctionCmt(0x004A53B3, "Parses game-data SYMBOL DEFINITIONS from a buffer into the symbol table: tokenizes via 0x4A7720 with per-name limit 0x42 (66 bytes) and count cap 0x7FFFFFFF, null-terminates each p", 1);
	MakeName(0x004AF7B0, "ErrorShow");
	SetFunctionCmt(0x004AF7B0, "Shows a fatal-error dialog: printf-style FORMAT STRING + variadic args (e.g. push \"Level_Load(): Couldn't load script: %s\"; push scriptPath; call). Param: format = printf-style s", 1);
	MakeName(0x004AF810, "WarningShow");
	SetFunctionCmt(0x004AF810, "Shows a warning dialog - printf-style variadic like ErrorShow (retail: push str.\"QTasktype \\"%s\\"...\"; push eax; call -> add esp,8). Param: format = printf-style string + subst", 1);
	MakeName(0x004B0BE0, "MemDeallocAll");
	SetFunctionCmt(0x004B0BE0, "Deallocate allocated memory. Frees EVERY tracked heap block (walks allocation list via 0x4B0D10), then warns \"%d block(s) of memory have not been deallocated.\" Takes no args - NO", 1);
	MakeName(0x004B0C60, "Mem_Alloc");
	SetFunctionCmt(0x004B0C60, "Engine heap allocator. Params: numBytes = bytes to allocate, tag = allocation bucket shown in the 'Total allocated by user' accounting. RETURNS pointer or 0 on failure (error text:", 1);
	MakeName(0x004B0D40, "QHash_ValueSet");
	SetFunctionCmt(0x004B0D40, "Sets a value in a QHash hash-table (8-byte thunk into the hash engine at 0x4B0D90 family). Pass the table ptr, key string and integer value. Restored after accidental loss during b", 1);
	MakeName(0x004B0D60, "QhashInit");
	SetFunctionCmt(0x004B0D60, "Init hash table value, Params: hash value 0 or 1.", 1);
	MakeName(0x004B0D90, "QhashReset");
	SetFunctionCmt(0x004B0D90, "Reset QTask type hash table.", 1);
	MakeName(0x004B0DB0, "QHash_ValueGet");
	SetFunctionCmt(0x004B0DB0, "Gets a value from a QHash hash-table (6-byte getter thunk). Pass table ptr + key string, RETURNS the stored integer. Restored after accidental loss - address pass1-verified.", 1);
	MakeName(0x004B1510, "QFileOpen");
	SetFunctionCmt(0x004B1510, "Open Qfile (QSC,QVM) for reading or writing, Params: Check fopen() in c.", 1);
	MakeName(0x004B16D0, "ResourceUnpack");
	SetFunctionCmt(0x004B16D0, "Unpacks a raw resource ENTRY previously obtained from the resource table into a destination address. Params: resPtr = resource-table entry, destAddr = destination memory address, r", 1);
	MakeName(0x004B18B0, "ResourcePackUnpack");
	SetFunctionCmt(0x004B18B0, "Unpacks a PACKED resource file (compressed/packed container format) into memory. Params: resFile = virtual path of the packed resource, outBuffer = receives unpacked data pointer. ", 1);
	MakeName(0x004B1AC0, "QScript_Cleanup");
	SetFunctionCmt(0x004B1AC0, "Cleans up/frees a parsed .qsc script structure (pass1: 5 calls, valid exit). Param: script = pointer to the loaded script object. Call when done with a script loaded via the Qvm/Qs", 1);
	MakeName(0x004B53B0, "QspriteRegister4Az");
	SetFunctionCmt(0x004B53B0, "Registers a QUAD-SPRITE with full transform data: 14 args, float parameters scaled by constant 0x534AB0, writes sprite tables 0xA84A50/0xA84A58 (verified). Low-level renderer API -", 1);
	MakeName(0x004B5B90, "IsResourceLoaded");
	SetFunctionCmt(0x004B5B90, "Checks whether a virtual resource is already loaded and optionally returns its table entry. Params: resourcePath = virtual path to test, outEntry = receives the resource-table entr", 1);
	MakeName(0x004B5F00, "ResourceLoad");
	SetFunctionCmt(0x004B5F00, "Loads a VIRTUAL RESOURCE (path like 'LOCAL:...' or 'MISSION:...') into memory: emits 'Failed to load resource: '%s'' on miss. Params: resourcePath = virtual resource path, outBuffe", 1);
	MakeName(0x004B6380, "Resource_Unload");
	SetFunctionCmt(0x004B6380, "Name from igi.exe error string inside function: \"Resource_Unload() : Resource '%s' is not loaded.\" Unloads a resource by name/path.", 1);
	MakeName(0x004B63D0, "Resource_Flush");
	SetFunctionCmt(0x004B63D0, "Name from igi.exe error string inside function: \"Resource_Flush() : Couldn't locate resource at %p\". Flushes/finalizes resource entries.", 1);
	MakeName(0x004B6E70, "PictureGetWidth");
	SetFunctionCmt(0x004B6E70, "RETURNS the WIDTH in pixels of a loaded picture/surface. Param: picture = pointer from a picture-load call. Thin thunk to fcn.004B7DF0 (byte-verified).", 1);
	MakeName(0x004B6E80, "PictureGetHeight");
	SetFunctionCmt(0x004B6E80, "RETURNS the HEIGHT in pixels of a loaded picture/surface. Param: picture = picture pointer. Thin thunk to fcn.004B7E00.", 1);
	MakeName(0x004B7E80, "SymbolRegisterInt16");
	SetFunctionCmt(0x004B7E80, "Registers a int16 game-data symbol: thin thunk that calls the core registrar QTaskHashTableSet (0x4BAAC0) with a fixed argument tail (1,1,0,1,handler 0x4B7F20-family) binding 'name", 1);
	MakeName(0x004B7EE0, "SymbolRegisterBool8");
	SetFunctionCmt(0x004B7EE0, "Registers a bool8 (byte 0/1) game-data symbol: thin thunk that calls the core registrar QTaskHashTableSet (0x4BAAC0) with a fixed argument tail (1,1,0,1,handler 0x4B7F00) binding '", 1);
	MakeName(0x004B7FA0, "SymbolRegisterInt32");
	SetFunctionCmt(0x004B7FA0, "Registers a int32 game-data symbol: thin thunk that calls the core registrar QTaskHashTableSet (0x4BAAC0) with a fixed argument tail (1,1,0,1,handler 0x4B7F40-family) binding 'name", 1);
	MakeName(0x004B7FC0, "SymbolRegisterReal32");
	SetFunctionCmt(0x004B7FC0, "Registers a real32 (float) game-data symbol: thin thunk that calls the core registrar QTaskHashTableSet (0x4BAAC0) with a fixed argument tail (1,1,0,1,handler 0x4B7FA0-family) bind", 1);
	MakeName(0x004B80A0, "GameDataSymbolRemove");
	SetFunctionCmt(0x004B80A0, "Removes game data symbol for game like internal vairables,UI controls,timers etc.", 1);
	MakeName(0x004B80B0, "QvmLoad");
	SetFunctionCmt(0x004B80B0, "Compiles and Load any .qvm file into memory, Params: any qvm file name,  Returns filename loaded.", 1);
	MakeName(0x004B83D0, "CompilerCleanup");
	SetFunctionCmt(0x004B83D0, "Cleanup files after compiling, Params: File passed to CompileQVM", 1);
	MakeName(0x004B8410, "QscCompile");
	SetFunctionCmt(0x004B8410, "Compiles a .QSC script source into executable QVM form - body contains the output-extension strings '.qvm' and '.qas' plus 'An error occured when compiling file: %s'. Param: qscFil", 1);
	MakeName(0x004B85B0, "QvmCompile");
	SetFunctionCmt(0x004B85B0, "Compiles a script file into a QVM program, reporting failures with 'Error in QVM program: %s' and 'An error occured in script file: %s'. Param: scriptFile = virtual path of the scr", 1);
	MakeName(0x004B8810, "TasktypeSet");
	SetFunctionCmt(0x004B8810, "Defines new constants for game and scripts ,Params: task_str (int**)WEAPONTYPE_PISTOL, task_id", 1);
	MakeName(0x004B8890, "GameDefineOptions");
	SetFunctionCmt(0x004B8890, "Define game options constants , Params: opt_str (int**)'DefineAmmoType'", 1);
	MakeName(0x004B8930, "Script_SetSymbolContext");
	SetFunctionCmt(0x004B8930, "Name from igi.exe error string inside function: \"Script_SetSymbolContext(): Symbol not found: %s\". Sets the symbol context for subsequent script operations.", 1);
	MakeName(0x004B8C10, "BreakScript");
	SetFunctionCmt(0x004B8C10, "Breaks/aborts the currently-executing script at this point (70-byte function). Takes no args. Use as an early-exit inside .qsc scripts.", 1);
	MakeName(0x004B8C60, "_Script_SetWarningLevel");
	SetFunctionCmt(0x004B8C60, "Sets how loudly the script system reports warnings while parsing/running (igi.exe embeds its name WITH leading underscore: '_Script_SetWarningLevel'). Param: level = warning verbos", 1);
	MakeName(0x004BAAC0, "QTaskHashTableSet");
	SetFunctionCmt(0x004BAAC0, "THE CORE REGISTRAR: inserts an entry into the task/hash table binding a name-value pair to a handler callback. All 7 stack args confirmed by disassembly header (arg_18h..arg_3Ch). ", 1);
	MakeName(0x004BB270, "QvmAssemble");
	SetFunctionCmt(0x004BB270, "Assembles a QVM SCRIPT SOURCE into binary form: runs a full lexer/parser over the source (embedded regex patterns '[a-zA-Z][a-zA-Z0-9_]*:', '[ \t\n\r]+', comment stripping '{.*:(.*", 1);
	MakeName(0x004BBC30, "LogAdd");
	SetFunctionCmt(0x004BBC30, "Adds a formatted line to the engine log - printf-style variadic (function formats through vsprintf helper fcn.004A5702; r2 header args sp[0x4..0x8]). Param: format = printf-style s", 1);
	MakeName(0x004BBCB0, "QvmParse");
	SetFunctionCmt(0x004BBCB0, "Parses a script file and GENERATES ASSEMBLY CODE (own log line: 'Parsing script and generating assembly code.'). Writes the assembly to outputFile ('Failed to open file \"%s\" for ", 1);
	MakeName(0x004C0200, "ScriptBufInit");
	SetFunctionCmt(0x004C0200, "Initializes the four script-buffer control fields used by the script engine (pure field writer, no calls). Params: buf1/buf2 = buffer structure pointers, buf = data buffer, bufSize", 1);
	MakeName(0x004C0460, "SymbolRemove");
	SetFunctionCmt(0x004C0460, "Removes a symbol from the game-data symbol table. Params: p1 = symbol-table context, symbol_name = name/reference of the symbol to remove.", 1);
	MakeName(0x004C0560, "SymbolCheck");
	SetFunctionCmt(0x004C0560, "Check symbol in QTask list if already loaded, Params: symbol_name like 'TaskType_Set', p1,p3 ??", 1);
	MakeName(0x004C4520, "DefineMagicObj");
	SetFunctionCmt(0x004C4520, "Defines a MAGIC OBJECT type during magicobj definition parsing (pairs with the MAGICOBJ\ folder data). Parser-context only.", 1);
	MakeName(0x004C48E0, "RigidDyncubeObjRead");
	SetFunctionCmt(0x004C48E0, "Read rigid dynCube config file , Params: config file of rigid dynCube.", 1);
	MakeName(0x004C4930, "MagicObjLoad");
	SetFunctionCmt(0x004C4930, "Loads magic objects from path, Params: Path 'LOCAL:magicobj'", 1);
	MakeName(0x004C6760, "CreateTerrainTileMap");
	SetFunctionCmt(0x004C6760, "Creates the TERRAIN TILE MAP for a level during level load (113-byte function). Engine-internal: called by the terrain loader, not meant for gameplay scripts.", 1);
	MakeName(0x004E68D0, "SoundLoad");
	SetFunctionCmt(0x004E68D0, "Load all level sounds from path , Params: Path of sound like 'MISSION:sounds'", 1);
	MakeName(0x004E8C60, "DefineSound");
	SetFunctionCmt(0x004E8C60, "Defines a SOUND entry (file + attenuation params) inside sound definition blocks - OpenIGI reimplements it as SoundDefinitionRegistry.Define(SoundDefinitionKind.Sound). Call only f", 1);
	MakeName(0x004E9EC0, "DefineTriggerOnce");
	SetFunctionCmt(0x004E9EC0, "Defines a fire-once TRIGGER entry inside definition blocks - OpenIGI maps it to SoundDefinitionKind.TriggerOnce. Parser-context only.", 1);
	MakeName(0x004EAD20, "DefineGraph");
	SetFunctionCmt(0x004EAD20, "Defines a GRAPH (sound/graph transition graph) entry inside definition blocks - OpenIGI maps it to SoundDefinitionKind.Graph. Parser-context only.", 1);
	MakeName(0x004EBA90, "DefineGroup");
	SetFunctionCmt(0x004EBA90, "Defines a GROUP entry (sound-group/entity grouping) during definition parsing. Parser-context only.", 1);
	MakeName(0x004EC070, "AnimTrigger_ParseConfigFile");
	SetFunctionCmt(0x004EC070, "Name from igi.exe error string INSIDE this function: \"AnimTrigger_ParseConfigFile(): Couldn't load script: %s\" @0x54DB98. Parses an animtrigger config file into trigger entries.", 1);
	MakeName(0x004EC0C0, "AnimTriggerLoad");
	SetFunctionCmt(0x004EC0C0, "Loads anim trigger objects from path, Params: Path 'LOCAL:animtrigger'", 1);
	MakeName(0x004EDFE0, "PhysicsObjType_ParseConfigFile");
	SetFunctionCmt(0x004EDFE0, "Name from igi.exe error string inside function: \"PhysicsObjType_ParseConfigFile(): Couldn't load script\" @0x54DC7C. Parses a physicsobj type config.", 1);
	MakeName(0x004EE030, "PhysicsObjLoad");
	SetFunctionCmt(0x004EE030, "Loads physics objects from path, Params: Path 'LOCAL:physicsobj'", 1);
	MakeName(0x004F0740, "Task_DeclareParameters");
	SetFunctionCmt(0x004F0740, "Declares the parameter list of the task currently being defined inside a .qsc task block (OpenIGI TaskScriptCommands implements it reading a type name + parameter names). Call as F", 1);
	MakeName(0x004F0780, "Task_New");
	SetFunctionCmt(0x004F0780, "Instantiates a new game task from a declared type (731-byte factory; OpenIGI registers Task_New reading the type name then declared params). Call inside task blocks after Task_Decl", 1);
	MakeName(0x004F0CF0, "ConfigCompile");
	SetFunctionCmt(0x004F0CF0, "Compiles CONFIG script text into executable task form - body references 'Task_New' (the task factory it emits calls to). Params: context = compilation context, cfgText = config sou", 1);
	MakeName(0x004F0E10, "Level_LoadObjects");
	SetFunctionCmt(0x004F0E10, "Loads all OBJECTS for the level: reads the level object set and instantiates each object entity in the world. Takes the level/path argument from the calling load script. Use during", 1);
	MakeName(0x004F0E50, "ScriptInit");
	SetFunctionCmt(0x004F0E50, "Initialises the script system for a file. Params: file_name = script path, p2 = byte flag (observed), p3 = int option, p4 = byte flag. Refined types from decompiled header (two int", 1);
	MakeName(0x004F0E90, "QtaskUpdate");
	SetFunctionCmt(0x004F0E90, "Update QTask hash table call before loading level.", 1);
	MakeName(0x004F9FF0, "GraphOpen");
	SetFunctionCmt(0x004F9FF0, "Open graph of level,Params: with str 'Graph4019.dat'", 1);
	Message("Done.\n");
}
